In [47]:
import re
import nltk
import math
import pandas as pd
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.util import trigrams,ngrams
from nltk.tokenize import sent_tokenize, word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [48]:
with open("/content/Alice in wonderland.txt", "r",encoding='utf-8') as f:
  corpus = f.read()

In [49]:
corpus

'Down the Rabbit-Hole Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, “and what is the use of a book,” thought Alice “without pictures or conversations?” So she was considering in her own mind (as well as she could, for the hot day made her feel very sleepy and stupid), whether the pleasure of making a daisy-chain would be worth the trouble of getting up and picking the daisies, when suddenly a White Rabbit with pink eyes ran close by her.\nThere was nothing so _very_ remarkable in that; nor did Alice think it so _very_ much out of the way to hear the Rabbit say to itself, “Oh dear!\nOh dear!\nI shall be late!” (when she thought it over afterwards, it occurred to her that she ought to have wondered at this, but at the time it all seemed quite natural); but when the Rabbit actually _took a watch out of its waistcoat-pocket_, and looked at it, and then hurried on, Alice started to her feet, for it flashed across her mind that she had never before seen a rabbit with either a waistcoat-pocket, or a watch to take out of it, and burning with curiosity, she ran across the field after it, and fortunately was just in time to see it pop down a large rabbit-hole under the hedge.\nIn another moment down went Alice after it, never once considering how in the world she was to get out again.\nThe rabbit-hole went straight on like a tunnel for some way, and then dipped suddenly down, so suddenly that Alice had not a moment to think about stopping herself before she found herself falling down a very deep well.\nEither the well was very deep, or she fell very slowly, for she had plenty of time as she went down to look about her and to wonder what was going to happen next.\nFirst, she tried to look down and make out what she was coming to, but it was too dark to see anything; then she looked at the sides of the well, and noticed that they were filled with cupboards and book-shelves; here and there she saw maps and pictures hung upon pegs.\nShe took down a jar from one of the shelves as she passed; it was labelled “ORANGE MARMALADE”, but to her great disappointment it was empty: she did not like to drop the jar for fear of killing somebody underneath, so managed to put it into one of the cupboards as she fell past it.\n“Well!” thought Alice to herself, “after such a fall as this, I shall think nothing of tumbling down stairs!\nHow brave they’ll all think me at home!\nWhy, I wouldn’t say anything about it, even if I fell off the top of the house!” (Which was very likely true.)\nDown, down, down.\nWould the fall _never_ come to an end?\n“I wonder how many miles I’ve fallen by this time?” she said aloud.\n“I must be getting somewhere near the centre of the earth.\nLet me see: that would be four thousand miles down, I think—” (for, you see, Alice had learnt several things of this sort in her lessons in the schoolroom, and though this was not a _very_ good opportunity for showing off her knowledge, as there was no one to listen to her, still it was good practice to say it over) “—yes, that’s about the right distance—but then I wonder what Latitude or Longitude I’ve got to?” (Alice had no idea what Latitude was, or Longitude either, but thought they were nice grand words to say.)\nPresently she began again.\n“I wonder if I shall fall right _through_ the earth!\nHow funny it’ll seem to come out among the people that walk with their heads downward!\nThe Antipathies, I think—” (she was rather glad there _was_ no one listening, this time, as it didn’t sound at all the right word) “—but I shall have to ask them what the name of the country is, you know.\nPlease, Ma’am, is this New Zealand or Australia?” (and she tried to curtsey as she spoke—fancy _curtseying_ as you’re falling through the air!\nDo you think you could manage it?)\n“And what an ignorant little girl she’ll think me for asking!\nNo, it’ll never do to ask: perhaps I shall see it written up somewhere.” Down, down, down.\nThere was nothing else to do, so Alice soon began talking again.\n“Dinah’ll miss me very much to-night, I should think!” (Dinah was the cat.)\n“I hope they’ll remember her saucer of milk at tea-time.\nDinah my dear!\nI wish you were down here with me!\nThere are no mice in the air, I’m afraid, but you might catch a bat, and that’s very like a mouse, you know.\nBut do cats eat bats, I wonder?” And here Alice began to get rather sleepy, and went on saying to herself, in a dreamy sort of way, “Do cats eat bats?\nDo cats eat bats?” and sometimes, “Do bats eat cats?” for, you see, as she couldn’t answer either question, it didn’t much matter which way she put it.\nShe felt that she was dozing off, and had just begun to dream that she was walking hand in hand with Dinah, and saying to her very earnestly, “Now, Dinah, tell me the truth: did you ever eat a bat?” when suddenly, thump!\nthump!\ndown she came upon a heap of sticks and dry leaves, and the fall was over.\nAlice was not a bit hurt, and she jumped up on to her feet in a moment: she looked up, but it was all dark overhead; before her was another long passage, and the White Rabbit was still in sight, hurrying down it.\nThere was not a moment to be lost: away went Alice like the wind, and was just in time to hear it say, as it turned a corner, “Oh my ears and whiskers, how late it’s getting!” She was close behind it when she turned the corner, but the Rabbit was no longer to be seen: she found herself in a long, low hall, which was lit up by a row of lamps hanging from the roof.\nThere were doors all round the hall, but they were all locked; and when Alice had been all the way down one side and up the other, trying every door, she walked sadly down the middle, wondering how she was ever to get out again.\nSuddenly she came upon a little three-legged table, all made of solid glass; there was nothing on it except a tiny golden key, and Alice’s first thought was that it might belong to one of the doors of the hall; but, alas!\neither the locks were too large, or the key was too small, but at any rate it would not open any of them.\nHowever, on the second time round, she came upon a low curtain she had not noticed before, and behind it was a little door about fifteen inches high: she tried the little golden key in the lock, and to her great delight it fitted!\nAlice opened the door and found that it led into a small passage, not much larger than a rat-hole: she knelt down and looked along the passage into the loveliest garden you ever saw.\nHow she longed to get out of that dark hall, and wander about among those beds of bright flowers and those cool fountains, but she could not even get her head through the doorway; “and even if my head would go through,” thought poor Alice, “it would be of very little use without my shoulders.\nOh, how I wish I could shut up like a telescope!\nI think I could, if I only knew how to begin.” For, you see, so many out-of-the-way things had happened lately, that Alice had begun to think that very few things indeed were really impossible.\nThere seemed to be no use in waiting by the little door, so she went back to the table, half hoping she might find another key on it, or at any rate a book of rules for shutting people up like telescopes: this time she found a little bottle on it, (“which certainly was not here before,” said Alice,) and round the neck of the bottle was a paper label, with the words “DRINK ME,” beautifully printed on it in large letters.\nIt was all very well to say “Drink me,” but the wise little Alice was not going to do _that_ in a hurry.\n“No, I’ll look first,” she said, “and see whether it’s marked ‘_poison_’ or not”; for she had read several nice little histories about children who had got burnt, and eaten up by wild beasts and other unpleasant things, all because they _would_ not remember the simple rules their friends had taught them: such as, that a red-hot poker will burn you if you hold it too long; and that if you cut your finger _very_ deeply with a knife, it usually bleeds; and she had never forgotten that, if you drink much from a bottle marked “poison,” it is almost certain to disagree with you, sooner or later.\nHowever, this bottle was _not_ marked “poison,” so Alice ventured to taste it, and finding it very nice, (it had, in fact, a sort of mixed flavour of cherry-tart, custard, pine-apple, roast turkey, toffee, and hot buttered toast,) she very soon finished it off.\n“What a curious feeling!” said Alice; “I must be shutting up like a telescope.” And so it was indeed: she was now only ten inches high, and her face brightened up at the thought that she was now the right size for going through the little door into that lovely garden.\nFirst, however, she waited for a few minutes to see if she was going to shrink any further: she felt a little nervous about this; “for it might end, you know,” said Alice to herself, “in my going out altogether, like a candle.\nI wonder what I should be like then?” And she tried to fancy what the flame of a candle is like after the candle is blown out, for she could not remember ever having seen such a thing.\nAfter a while, finding that nothing more happened, she decided on going into the garden at once; but, alas for poor Alice!\nwhen she got to the door, she found she had forgotten the little golden key, and when she went back to the table for it, she found she could not possibly reach it: she could see it quite plainly through the glass, and she tried her best to climb up one of the legs of the table, but it was too slippery; and when she had tired herself out with trying, the poor little thing sat down and cried.\n“Come, there’s no use in crying like that!” said Alice to herself, rather sharply; “I advise you to leave off this minute!” She generally gave herself very good advice, (though she very seldom followed it), and sometimes she scolded herself so severely as to bring tears into her eyes; and once she remembered trying to box her own ears for having cheated herself in a game of croquet she was playing against herself, for this curious child was very fond of pretending to be two people.\n“But it’s no use now,” thought poor Alice, “to pretend to be two people!\nWhy, there’s hardly enough of me left to make _one_ respectable person!” Soon her eye fell on a little glass box that was lying under the table: she opened it, and found in it a very small cake, on which the words “EAT ME” were beautifully marked in currants.\n“Well, I’ll eat it,” said Alice, “and if it makes me grow larger, I can reach the key; and if it makes me grow smaller, I can creep under the door; so either way I’ll get into the garden, and I don’t care which happens!” She ate a little bit, and said anxiously to herself, “Which way?\nWhich way?”, holding her hand on the top of her head to feel which way it was growing, and she was quite surprised to find that she remained the same size: to be sure, this generally happens when one eats cake, but Alice had got so much into the way of expecting nothing but out-of-the-way things to happen, that it seemed quite dull and stupid for life to go on in the common way.\nSo she set to work, and very soon finished off the cake.\n\nThe Pool of Tears “Curiouser and curiouser!” cried Alice (she was so much surprised, that for the moment she quite forgot how to speak good English); “now I’m opening out like the largest telescope that ever was!\nGood-bye, feet!” (for when she looked down at her feet, they seemed to be almost out of sight, they were getting so far off).\n“Oh, my poor little feet, I wonder who will put on your shoes and stockings for you now, dears?\nI’m sure _I_ shan’t be able!\nI shall be a great deal too far off to trouble myself about you: you must manage the best way you can;—but I must be kind to them,” thought Alice, “or perhaps they won’t walk the way I want to go!\nLet me see: I’ll give them a new pair of boots every Christmas.” And she went on planning to herself how she would manage it.\n“They must go by the carrier,” she thought; “and how funny it’ll seem, sending presents to one’s own feet!\nAnd how odd the directions will look!\n_Alice’s Right Foot, Esq., Hearthrug, near the Fender,_ (_with Alice’s love_).\nOh dear, what nonsense I’m talking!” Just then her head struck against the roof of the hall: in fact she was now more than nine feet high, and she at once took up the little golden key and hurried off to the garden door.\nPoor Alice!\nIt was as much as she could do, lying down on one side, to look through into the garden with one eye; but to get through was more hopeless than ever: she sat down and began to cry again.\n“You ought to be ashamed of yourself,” said Alice, “a great girl like you,” (she might well say this), “to go on crying in this way!\nStop this moment, I tell you!” But she went on all the same, shedding gallons of tears, until there was a large pool all round her, about four inches deep and reaching half down the hall.\nAfter a time she heard a little pattering of feet in the distance, and she hastily dried her eyes to see what was coming.\nIt was the White Rabbit returning, splendidly dressed, with a pair of white kid gloves in one hand and a large fan in the other: he came trotting along in a great hurry, muttering to himself as he came, “Oh!\nthe Duchess, the Duchess!\nOh!\nwon’t she be savage if I’ve kept her waiting!” Alice felt so desperate that she was ready to ask help of any one; so, when the Rabbit came near her, she began, in a low, timid voice, “If you please, sir—” The Rabbit started violently, dropped the white kid gloves and the fan, and skurried away into the darkness as hard as he could go.\nAlice took up the fan and gloves, and, as the hall was very hot, she kept fanning herself all the time she went on talking: “Dear, dear!\nHow queer everything is to-day!\nAnd yesterday things went on just as usual.\nI wonder if I’ve been changed in the night?\nLet me think: was I the same when I got up this morning?\nI almost think I can remember feeling a little different.\nBut if I’m not the same, the next question is, Who in the world am I?\nAh, _that’s_ the great puzzle!” And she began thinking over all the children she knew that were of the same age as herself, to see if she could have been changed for any of them.\n“I’m sure I’m not Ada,” she said, “for her hair goes in such long ringlets, and mine doesn’t go in ringlets at all; and I’m sure I can’t be Mabel, for I know all sorts of things, and she, oh!\nshe knows such a very little!\nBesides, _she’s_ she, and _I’m_ I, and—oh dear, how puzzling it all is!\nI’ll try if I know all the things I used to know.\nLet me see: four times five is twelve, and four times six is thirteen, and four times seven is—oh dear!\nI shall never get to twenty at that rate!\nHowever, the Multiplication Table doesn’t signify: let’s try Geography.\nLondon is the capital of Paris, and Paris is the capital of Rome, and Rome—no, _that’s_ all wrong, I’m certain!\nI must have been changed for Mabel!\nI’ll try and say ‘_How doth the little_—’” and she crossed her hands on her lap as if she were saying lessons, and began to repeat it, but her voice sounded hoarse and strange, and the words did not come the same as they used to do:— “How doth the little crocodile Improve his shining tail, And pour the waters of the Nile On every golden scale!\n“How cheerfully he seems to grin, How neatly spread his claws, And welcome little fishes in With gently smiling jaws!” “I’m sure those are not the right words,” said poor Alice, and her eyes filled with tears again as she went on, “I must be Mabel after all, and I shall have to go and live in that poky little house, and have next to no toys to play with, and oh!\never so many lessons to learn!\nNo, I’ve made up my mind about it; if I’m Mabel, I’ll stay down here!\nIt’ll be no use their putting their heads down and saying ‘Come up again, dear!’ I shall only look up and say ‘Who am I then?\nTell me that first, and then, if I like being that person, I’ll come up: if not, I’ll stay down here till I’m somebody else’—but, oh dear!” cried Alice, with a sudden burst of tears, “I do wish they _would_ put their heads down!\nI am so _very_ tired of being all alone here!” As she said this she looked down at her hands, and was surprised to see that she had put on one of the Rabbit’s little white kid gloves while she was talking.\n“How _can_ I have done that?” she thought.\n“I must be growing small again.” She got up and went to the table to measure herself by it, and found that, as nearly as she could guess, she was now about two feet high, and was going on shrinking rapidly: she soon found out that the cause of this was the fan she was holding, and she dropped it hastily, just in time to avoid shrinking away altogether.\n“That _was_ a narrow escape!” said Alice, a good deal frightened at the sudden change, but very glad to find herself still in existence; “and now for the garden!” and she ran with all speed back to the little door: but, alas!\nthe little door was shut again, and the little golden key was lying on the glass table as before, “and things are worse than ever,” thought the poor child, “for I never was so small as this before, never!\nAnd I declare it’s too bad, that it is!” As she said these words her foot slipped, and in another moment, splash!\nshe was up to her chin in salt water.\nHer first idea was that she had somehow fallen into the sea, “and in that case I can go back by railway,” she said to herself.\n(Alice had been to the seaside once in her life, and had come to the general conclusion, that wherever you go to on the English coast you find a number of bathing machines in the sea, some children digging in the sand with wooden spades, then a row of lodging houses, and behind them a railway station.)\nHowever, she soon made out that she was in the pool of tears which she had wept when she was nine feet high.\n“I wish I hadn’t cried so much!” said Alice, as she swam about, trying to find her way out.\n“I shall be punished for it now, I suppose, by being drowned in my own tears!\nThat _will_ be a queer thing, to be sure!\nHowever, everything is queer to-day.” Just then she heard something splashing about in the pool a little way off, and she swam nearer to make out what it was: at first she thought it must be a walrus or hippopotamus, but then she remembered how small she was now, and she soon made out that it was only a mouse that had slipped in like herself.\n“Would it be of any use, now,” thought Alice, “to speak to this mouse?\nEverything is so out-of-the-way down here, that I should think very likely it can talk: at any rate, there’s no harm in trying.” So she began: “O Mouse, do you know the way out of this pool?\nI am very tired of swimming about here, O Mouse!” (Alice thought this must be the right way of speaking to a mouse: she had never done such a thing before, but she remembered having seen in her brother’s Latin Grammar, “A mouse—of a mouse—to a mouse—a mouse—O mouse!”) The Mouse looked at her rather inquisitively, and seemed to her to wink with one of its little eyes, but it said nothing.\n“Perhaps it doesn’t understand English,” thought Alice; “I daresay it’s a French mouse, come over with William the Conqueror.” (For, with all her knowledge of history, Alice had no very clear notion how long ago anything had happened.)\nSo she began again: “Où est ma chatte?” which was the first sentence in her French lesson-book.\nThe Mouse gave a sudden leap out of the water, and seemed to quiver all over with fright.\n“Oh, I beg your pardon!” cried Alice hastily, afraid that she had hurt the poor animal’s feelings.\n“I quite forgot you didn’t like cats.” “Not like cats!” cried the Mouse, in a shrill, passionate voice.\n“Would _you_ like cats if you were me?” “Well, perhaps not,” said Alice in a soothing tone: “don’t be angry abou

In [50]:
len(corpus)

142387

In [51]:
def clean_text(segment):
  text = re.sub("_", "", segment)
  text = re.sub('[^\w\s\.\?\-]',' ', text) # why space? because i noticed this: ( important—unimportant—unimportant—important— ) when — is removed all 4 become 1 word
  text = re.sub("\s+", " ", text)
  text = re.sub("\.{2,}","", text)
  text = re.sub("\?{2,}","", text)

  return text

In [52]:
corpus = clean_text(corpus)

In [53]:
corpus

'Down the Rabbit-Hole Alice was beginning to get very tired of sitting by her sister on the bank and of having nothing to do once or twice she had peeped into the book her sister was reading but it had no pictures or conversations in it and what is the use of a book thought Alice without pictures or conversations? So she was considering in her own mind as well as she could for the hot day made her feel very sleepy and stupid whether the pleasure of making a daisy-chain would be worth the trouble of getting up and picking the daisies when suddenly a White Rabbit with pink eyes ran close by her. There was nothing so very remarkable in that nor did Alice think it so very much out of the way to hear the Rabbit say to itself Oh dear Oh dear I shall be late when she thought it over afterwards it occurred to her that she ought to have wondered at this but at the time it all seemed quite natural but when the Rabbit actually took a watch out of its waistcoat-pocket and looked at it and then hurried on Alice started to her feet for it flashed across her mind that she had never before seen a rabbit with either a waistcoat-pocket or a watch to take out of it and burning with curiosity she ran across the field after it and fortunately was just in time to see it pop down a large rabbit-hole under the hedge. In another moment down went Alice after it never once considering how in the world she was to get out again. The rabbit-hole went straight on like a tunnel for some way and then dipped suddenly down so suddenly that Alice had not a moment to think about stopping herself before she found herself falling down a very deep well. Either the well was very deep or she fell very slowly for she had plenty of time as she went down to look about her and to wonder what was going to happen next. First she tried to look down and make out what she was coming to but it was too dark to see anything then she looked at the sides of the well and noticed that they were filled with cupboards and book-shelves here and there she saw maps and pictures hung upon pegs. She took down a jar from one of the shelves as she passed it was labelled ORANGE MARMALADE but to her great disappointment it was empty she did not like to drop the jar for fear of killing somebody underneath so managed to put it into one of the cupboards as she fell past it. Well thought Alice to herself after such a fall as this I shall think nothing of tumbling down stairs How brave they ll all think me at home Why I wouldn t say anything about it even if I fell off the top of the house Which was very likely true. Down down down. Would the fall never come to an end? I wonder how many miles I ve fallen by this time? she said aloud. I must be getting somewhere near the centre of the earth. Let me see that would be four thousand miles down I think for you see Alice had learnt several things of this sort in her lessons in the schoolroom and though this was not a very good opportunity for showing off her knowledge as there was no one to listen to her still it was good practice to say it over yes that s about the right distance but then I wonder what Latitude or Longitude I ve got to? Alice had no idea what Latitude was or Longitude either but thought they were nice grand words to say. Presently she began again. I wonder if I shall fall right through the earth How funny it ll seem to come out among the people that walk with their heads downward The Antipathies I think she was rather glad there was no one listening this time as it didn t sound at all the right word but I shall have to ask them what the name of the country is you know. Please Ma am is this New Zealand or Australia? and she tried to curtsey as she spoke fancy curtseying as you re falling through the air Do you think you could manage it? And what an ignorant little girl she ll think me for asking No it ll never do to ask perhaps I shall see it written up somewhere. Down down down. There was nothing else to do so Alice soon began talking again. Dinah ll miss me very much to-night I should think Dinah was the cat. I hope they ll remember her saucer of milk at tea-time. Dinah my dear I wish you were down here with me There are no mice in the air I m afraid but you might catch a bat and that s very like a mouse you know. But do cats eat bats I wonder? And here Alice began to get rather sleepy and went on saying to herself in a dreamy sort of way Do cats eat bats? Do cats eat bats? and sometimes Do bats eat cats? for you see as she couldn t answer either question it didn t much matter which way she put it. She felt that she was dozing off and had just begun to dream that she was walking hand in hand with Dinah and saying to her very earnestly Now Dinah tell me the truth did you ever eat a bat? when suddenly thump thump down she came upon a heap of sticks and dry leaves and the fall was over. Alice was not a bit hurt and she jumped up on to her feet in a moment she looked up but it was all dark overhead before her was another long passage and the White Rabbit was still in sight hurrying down it. There was not a moment to be lost away went Alice like the wind and was just in time to hear it say as it turned a corner Oh my ears and whiskers how late it s getting She was close behind it when she turned the corner but the Rabbit was no longer to be seen she found herself in a long low hall which was lit up by a row of lamps hanging from the roof. There were doors all round the hall but they were all locked and when Alice had been all the way down one side and up the other trying every door she walked sadly down the middle wondering how she was ever to get out again. Suddenly she came upon a little three-legged table all made of solid glass there was nothing on it except a tiny golden key and Alice s first thought was that it might belong to one of the doors of the hall but alas either the locks were too large or the key was too small but at any rate it would not open any of them. However on the second time round she came upon a low curtain she had not noticed before and behind it was a little door about fifteen inches high she tried the little golden key in the lock and to her great delight it fitted Alice opened the door and found that it led into a small passage not much larger than a rat-hole she knelt down and looked along the passage into the loveliest garden you ever saw. How she longed to get out of that dark hall and wander about among those beds of bright flowers and those cool fountains but she could not even get her head through the doorway and even if my head would go through thought poor Alice it would be of very little use without my shoulders. Oh how I wish I could shut up like a telescope I think I could if I only knew how to begin. For you see so many out-of-the-way things had happened lately that Alice had begun to think that very few things indeed were really impossible. There seemed to be no use in waiting by the little door so she went back to the table half hoping she might find another key on it or at any rate a book of rules for shutting people up like telescopes this time she found a little bottle on it which certainly was not here before said Alice and round the neck of the bottle was a paper label with the words DRINK ME beautifully printed on it in large letters. It was all very well to say Drink me but the wise little Alice was not going to do that in a hurry. No I ll look first she said and see whether it s marked poison or not for she had read several nice little histories about children who had got burnt and eaten up by wild beasts and other unpleasant things all because they would not remember the simple rules their friends had taught them such as that a red-hot poker will burn you if you hold it too long and that if you cut your finger very deeply with a knife it usually bleeds and she had never forgotten that if you drink much from a bottle marked poison it is almost certain to disagree with you sooner or later. However this bottle was not marked poison so Alice ventured to taste it and finding it very nice it had in fact a sort of mixed flavour of cherry-tart custard pine-apple roast turkey toffee and hot buttered toast she very soon finished it off. What a curious feeling said Alice I must be shutting up like a telescope. And so it was indeed she was now only ten inches high and her face brightened up at the thought that she was now the right size for going through the little door into that lovely garden. First however she waited for a few minutes to see if she was going to shrink any further she felt a little nervous about this for it might end you know said Alice to herself in my going out altogether like a candle. I wonder what I should be like then? And she tried to fancy what the flame of a candle is like after the candle is blown out for she could not remember ever having seen such a thing. After a while finding that nothing more happened she decided on going into the garden at once but alas for poor Alice when she got to the door she found she had forgotten the little golden key and when she went back to the table for it she found she could not possibly reach it she could see it quite plainly through the glass and she tried her best to climb up one of the legs of the table but it was too slippery and when she had tired herself out with trying the poor little thing sat down and cried. Come there s no use in crying like that said Alice to herself rather sharply I advise you to leave off this minute She generally gave herself very good advice though she very seldom followed it and sometimes she scolded herself so severely as to bring tears into her eyes and once she remembered trying to box her own ears for having cheated herself in a game of croquet she was playing against herself for this curious child was very fond of pretending to be two people. But it s no use now thought poor Alice to pretend to be two people Why there s hardly enough of me left to make one respectable person Soon her eye fell on a little glass box that was lying under the table she opened it and found in it a very small cake on which the words EAT ME were beautifully marked in currants. Well I ll eat it said Alice and if it makes me grow larger I can reach the key and if it makes me grow smaller I can creep under the door so either way I ll get into the garden and I don t care which happens She ate a little bit and said anxiously to herself Which way? Which way? holding her hand on the top of her head to feel which way it was growing and she was quite surprised to find that she remained the same size to be sure this generally happens when one eats cake but Alice had got so much into the way of expecting nothing but out-of-the-way things to happen that it seemed quite dull and stupid for life to go on in the common way. So she set to work and very soon finished off the cake. The Pool of Tears Curiouser and curiouser cried Alice she was so much surprised that for the moment she quite forgot how to speak good English now I m opening out like the largest telescope that ever was Good-bye feet for when she looked down at her feet they seemed to be almost out of sight they were getting so far off . Oh my poor little feet I wonder who will put on your shoes and stockings for you now dears? I m sure I shan t be able I shall be a great deal too far off to trouble myself about you you must manage the best way you can but I must be kind to them thought Alice or perhaps they won t walk the way I want to go Let me see I ll give them a new pair of boots every Christmas. And she went on planning to herself how she would manage it. They must go by the carrier she thought and how funny it ll seem sending presents to one s own feet And how odd the directions will look Alice s Right Foot Esq. Hearthrug near the Fender with Alice s love . Oh dear what nonsense I m talking Just then her head struck against the roof of the hall in fact she was now more than nine feet high and she at once took up the little golden key and hurried off to the garden door. Poor Alice It was as much as she could do lying down on one side to look through into the garden with one eye but to get through was more hopeless than ever she sat down and began to cry again. You ought to be ashamed of yourself said Alice a great girl like you she might well say this to go on crying in this way Stop this moment I tell you But she went on all the same shedding gallons of tears until there was a large pool all round her about four inches deep and reaching half down the hall. After a time she heard a little pattering of feet in the distance and she hastily dried her eyes to see what was coming. It was the White Rabbit returning splendidly dressed with a pair of white kid gloves in one hand and a large fan in the other he came trotting along in a great hurry muttering to himself as he came Oh the Duchess the Duchess Oh won t she be savage if I ve kept her waiting Alice felt so desperate that she was ready to ask help of any one so when the Rabbit came near her she began in a low timid voice If you please sir The Rabbit started violently dropped the white kid gloves and the fan and skurried away into the darkness as hard as he could go. Alice took up the fan and gloves and as the hall was very hot she kept fanning herself all the time she went on talking Dear dear How queer everything is to-day And yesterday things went on just as usual. I wonder if I ve been changed in the night? Let me think was I the same when I got up this morning? I almost think I can remember feeling a little different. But if I m not the same the next question is Who in the world am I? Ah that s the great puzzle And she began thinking over all the children she knew that were of the same age as herself to see if she could have been changed for any of them. I m sure I m not Ada she said for her hair goes in such long ringlets and mine doesn t go in ringlets at all and I m sure I can t be Mabel for I know all sorts of things and she oh she knows such a very little Besides she s she and I m I and oh dear how puzzling it all is I ll try if I know all the things I used to know. Let me see four times five is twelve and four times six is thirteen and four times seven is oh dear I shall never get to twenty at that rate However the Multiplication Table doesn t signify let s try Geography. London is the capital of Paris and Paris is the capital of Rome and Rome no that s all wrong I m certain I must have been changed for Mabel I ll try and say How doth the little and she crossed her hands on her lap as if she were saying lessons and began to repeat it but her voice sounded hoarse and strange and the words did not come the same as they used to do How doth the little crocodile Improve his shining tail And pour the waters of the Nile On every golden scale How cheerfully he seems to grin How neatly spread his claws And welcome little fishes in With gently smiling jaws I m sure those are not the right words said poor Alice and her eyes filled with tears again as she went on I must be Mabel after all and I shall have to go and live in that poky little house and have next to no toys to play with and oh ever so many lessons to learn No I ve made up my mind about it if I m Mabel I ll stay down here It ll be no use their putting their heads down and saying Come up again dear I shall only look up and say Who am I then? Tell me that first and then if I like being that person I ll come up if not I ll stay down here till I m somebody else but oh dear cried Alice with a sudden burst of tears I do wish they would put their heads down I am so very tired of being all alone here As she said this she looked down at her hands and was surprised to see that she had put on one of the Rabbit s little white kid gloves while she was talking. How can I have done that? she thought. I must be growing small again. She got up and went to the table to measure herself by it and found that as nearly as she could guess she was now about two feet high and was going on shrinking rapidly she soon found out that the cause of this was the fan she was holding and she dropped it hastily just in time to avoid shrinking away altogether. That was a narrow escape said Alice a good deal frightened at the sudden change but very glad to find herself still in existence and now for the garden and she ran with all speed back to the little door but alas the little door was shut again and the little golden key was lying on the glass table as before and things are worse than ever thought the poor child for I never was so small as this before never And I declare it s too bad that it is As she said these words her foot slipped and in another moment splash she was up to her chin in salt water. Her first idea was that she had somehow fallen into the sea and in that case I can go back by railway she said to herself. Alice had been to the seaside once in her life and had come to the general conclusion that wherever you go to on the English coast you find a number of bathing machines in the sea some children digging in the sand with wooden spades then a row of lodging houses and behind them a railway station. However she soon made out that she was in the pool of tears which she had wept when she was nine feet high. I wish I hadn t cried so much said Alice as she swam about trying to find her way out. I shall be punished for it now I suppose by being drowned in my own tears That will be a queer thing to be sure However everything is queer to-day. Just then she heard something splashing about in the pool a little way off and she swam nearer to make out what it was at first she thought it must be a walrus or hippopotamus but then she remembered how small she was now and she soon made out that it was only a mouse that had slipped in like herself. Would it be of any use now thought Alice to speak to this mouse? Everything is so out-of-the-way down here that I should think very likely it can talk at any rate there s no harm in trying. So she began O Mouse do you know the way out of this pool? I am very tired of swimming about here O Mouse Alice thought this must be the right way of speaking to a mouse she had never done such a thing before but she remembered having seen in her brother s Latin Grammar A mouse of a mouse to a mouse a mouse O mouse The Mouse looked at her rather inquisitively and seemed to her to wink with one of its little eyes but it said nothing. Perhaps it doesn t understand English thought Alice I daresay it s a French mouse come over with William the Conqueror. For with all her knowledge of history Alice had no very clear notion how long ago anything had happened. So she began again Où est ma chatte? which was the first sentence in her French lesson-book. The Mouse gave a sudden leap out of the water and seemed to quiver all over with fright. Oh I beg your pardon cried Alice hastily afraid that she had hurt the poor animal s feelings. I quite forgot you didn t like cats. Not like cats cried the Mouse in a shrill passionate voice. Would you like cats if you were me? Well perhaps not said Alice in a soothing tone don t be angry about it. And yet I wish I could show you our cat Dinah I think you d take a fancy to cats if you could only see her. She is such a dear quiet thing Alice went on half to herself as she swam lazily about in the pool and she sits purring so nicely by the fire licking her paws and washing her face and she is such a nice soft thing to nurse and she s such a capital one for catching mice oh I beg your pardon cried Alice again for this time the Mouse was bristling all over and she felt certain it must be really offended. We won t talk about her any more if you d rather not. We indeed cried the Mouse who was trembling down to the end of his tail. As if I would talk on such a subject Our family always hated cats nasty low vulgar things Don t let me hear the name again I won t indeed said Alice in a great hurry to change the subject of conversation. Are 

In [54]:
len(corpus)

136095

In [55]:
stop_words = stopwords.words('english')
stop_words

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [56]:
words = word_tokenize(corpus)
filtered_text = []

for token in words:
  if token.lower() not in stop_words:
    filtered_text.append(token)

print(filtered_text)
print(words)

['Rabbit-Hole', 'Alice', 'beginning', 'get', 'tired', 'sitting', 'sister', 'bank', 'nothing', 'twice', 'peeped', 'book', 'sister', 'reading', 'pictures', 'conversations', 'use', 'book', 'thought', 'Alice', 'without', 'pictures', 'conversations', '?', 'considering', 'mind', 'well', 'could', 'hot', 'day', 'made', 'feel', 'sleepy', 'stupid', 'whether', 'pleasure', 'making', 'daisy-chain', 'would', 'worth', 'trouble', 'getting', 'picking', 'daisies', 'suddenly', 'White', 'Rabbit', 'pink', 'eyes', 'ran', 'close', '.', 'nothing', 'remarkable', 'Alice', 'think', 'much', 'way', 'hear', 'Rabbit', 'say', 'Oh', 'dear', 'Oh', 'dear', 'shall', 'late', 'thought', 'afterwards', 'occurred', 'ought', 'wondered', 'time', 'seemed', 'quite', 'natural', 'Rabbit', 'actually', 'took', 'watch', 'waistcoat-pocket', 'looked', 'hurried', 'Alice', 'started', 'feet', 'flashed', 'across', 'mind', 'never', 'seen', 'rabbit', 'either', 'waistcoat-pocket', 'watch', 'take', 'burning', 'curiosity', 'ran', 'across', 'field', 'fortunately', 'time', 'see', 'pop', 'large', 'rabbit-hole', 'hedge', '.', 'another', 'moment', 'went', 'Alice', 'never', 'considering', 'world', 'get', '.', 'rabbit-hole', 'went', 'straight', 'like', 'tunnel', 'way', 'dipped', 'suddenly', 'suddenly', 'Alice', 'moment', 'think', 'stopping', 'found', 'falling', 'deep', 'well', '.', 'Either', 'well', 'deep', 'fell', 'slowly', 'plenty', 'time', 'went', 'look', 'wonder', 'going', 'happen', 'next', '.', 'First', 'tried', 'look', 'make', 'coming', 'dark', 'see', 'anything', 'looked', 'sides', 'well', 'noticed', 'filled', 'cupboards', 'book-shelves', 'saw', 'maps', 'pictures', 'hung', 'upon', 'pegs', '.', 'took', 'jar', 'one', 'shelves', 'passed', 'labelled', 'ORANGE', 'MARMALADE', 'great', 'disappointment', 'empty', 'like', 'drop', 'jar', 'fear', 'killing', 'somebody', 'underneath', 'managed', 'put', 'one', 'cupboards', 'fell', 'past', '.', 'Well', 'thought', 'Alice', 'fall', 'shall', 'think', 'nothing', 'tumbling', 'stairs', 'brave', 'think', 'home', 'say', 'anything', 'even', 'fell', 'top', 'house', 'likely', 'true', '.', '.', 'Would', 'fall', 'never', 'come', 'end', '?', 'wonder', 'many', 'miles', 'fallen', 'time', '?', 'said', 'aloud', '.', 'must', 'getting', 'somewhere', 'near', 'centre', 'earth', '.', 'Let', 'see', 'would', 'four', 'thousand', 'miles', 'think', 'see', 'Alice', 'learnt', 'several', 'things', 'sort', 'lessons', 'schoolroom', 'though', 'good', 'opportunity', 'showing', 'knowledge', 'one', 'listen', 'still', 'good', 'practice', 'say', 'yes', 'right', 'distance', 'wonder', 'Latitude', 'Longitude', 'got', '?', 'Alice', 'idea', 'Latitude', 'Longitude', 'either', 'thought', 'nice', 'grand', 'words', 'say', '.', 'Presently', 'began', '.', 'wonder', 'shall', 'fall', 'right', 'earth', 'funny', 'seem', 'come', 'among', 'people', 'walk', 'heads', 'downward', 'Antipathies', 'think', 'rather', 'glad', 'one', 'listening', 'time', 'sound', 'right', 'word', 'shall', 'ask', 'name', 'country', 'know', '.', 'Please', 'New', 'Zealand', 'Australia', '?', 'tried', 'curtsey', 'spoke', 'fancy', 'curtseying', 'falling', 'air', 'think', 'could', 'manage', '?', 'ignorant', 'little', 'girl', 'think', 'asking', 'never', 'ask', 'perhaps', 'shall', 'see', 'written', 'somewhere', '.', '.', 'nothing', 'else', 'Alice', 'soon', 'began', 'talking', '.', 'Dinah', 'miss', 'much', 'to-night', 'think', 'Dinah', 'cat', '.', 'hope', 'remember', 'saucer', 'milk', 'tea-time', '.', 'Dinah', 'dear', 'wish', 'mice', 'air', 'afraid', 'might', 'catch', 'bat', 'like', 'mouse', 'know', '.', 'cats', 'eat', 'bats', 'wonder', '?', 'Alice', 'began', 'get', 'rather', 'sleepy', 'went', 'saying', 'dreamy', 'sort', 'way', 'cats', 'eat', 'bats', '?', 'cats', 'eat', 'bats', '?', 'sometimes', 'bats', 'eat', 'cats', '?', 'see', 'answer', 'either', 'question', 'much', 'matter', 'way', 'put', '.', 'felt', 'dozing', 'begun', 'dream', 'walking', 'hand', 'hand', 'Dinah', 'saying', 'earnestly', 'Dinah', 'tell', 'truth', 'ever', 'eat', 'bat', '?', 'suddenly', 'thump', 'thump', 'came', 'upon', 'heap', 'sticks', 'dry', 'leaves', 'fall', '.', 'Alice', 'bit', 'hurt', 'jumped', 'feet', 'moment', 'looked', 'dark', 'overhead', 'another', 'long', 'passage', 'White', 'Rabbit', 'still', 'sight', 'hurrying', '.', 'moment', 'lost', 'away', 'went', 'Alice', 'like', 'wind', 'time', 'hear', 'say', 'turned', 'corner', 'Oh', 'ears', 'whiskers', 'late', 'getting', 'close', 'behind', 'turned', 'corner', 'Rabbit', 'longer', 'seen', 'found', 'long', 'low', 'hall', 'lit', 'row', 'lamps', 'hanging', 'roof', '.', 'doors', 'round', 'hall', 'locked', 'Alice', 'way', 'one', 'side', 'trying', 'every', 'door', 'walked', 'sadly', 'middle', 'wondering', 'ever', 'get', '.', 'Suddenly', 'came', 'upon', 'little', 'three-legged', 'table', 'made', 'solid', 'glass', 'nothing', 'except', 'tiny', 'golden', 'key', 'Alice', 'first', 'thought', 'might', 'belong', 'one', 'doors', 'hall', 'alas', 'either', 'locks', 'large', 'key', 'small', 'rate', 'would', 'open', '.', 'However', 'second', 'time', 'round', 'came', 'upon', 'low', 'curtain', 'noticed', 'behind', 'little', 'door', 'fifteen', 'inches', 'high', 'tried', 'little', 'golden', 'key', 'lock', 'great', 'delight', 'fitted', 'Alice', 'opened', 'door', 'found', 'led', 'small', 'passage', 'much', 'larger', 'rat-hole', 'knelt', 'looked', 'along', 'passage', 'loveliest', 'garden', 'ever', 'saw', '.', 'longed', 'get', 'dark', 'hall', 'wander', 'among', 'beds', 'bright', 'flowers', 'cool', 'fountains', 'could', 'even', 'get', 'head', 'doorway', 'even', 'head', 'would', 'go', 'thought', 'poor', 'Alice', 'would', 'little', 'use', 'without', 'shoulders', '.', 'Oh', 'wish', 'could', 'shut', 'like', 'telescope', 'think', 'could', 'knew', 'begin', '.', 'see', 'many', 'out-of-the-way', 'things', 'happened', 'lately', 'Alice', 'begun', 'think', 'things', 'indeed', 'really', 'impossible', '.', 'seemed', 'use', 'waiting', 'little', 'door', 'went', 'back', 'table', 'half', 'hoping', 'might', 'find', 'another', 'key', 'rate', 'book', 'rules', 'shutting', 'people', 'like', 'telescopes', 'time', 'found', 'little', 'bottle', 'certainly', 'said', 'Alice', 'round', 'neck', 'bottle', 'paper', 'label', 'words', 'DRINK', 'beautifully', 'printed', 'large', 'letters', '.', 'well', 'say', 'Drink', 'wise', 'little', 'Alice', 'going', 'hurry', '.', 'look', 'first', 'said', 'see', 'whether', 'marked', 'poison', 'read', 'several', 'nice', 'little', 'histories', 'children', 'got', 'burnt', 'eaten', 'wild', 'beasts', 'unpleasant', 'things', 'would', 'remember', 'simple', 'rules', 'friends', 'taught', 'red-hot', 'poker', 'burn', 'hold', 'long', 'cut', 'finger', 'deeply', 'knife', 'usually', 'bleeds', 'never', 'forgotten', 'drink', 'much', 'bottle', 'marked', 'poison', 'almost', 'certain', 'disagree', 'sooner', 'later', '.', 'However', 'bottle', 'marked', 'poison', 'Alice', 'ventured', 'taste', 'finding', 'nice', 'fact', 'sort', 'mixed', 'flavour', 'cherry-tart', 'custard', 'pine-apple', 'roast', 'turkey', 'toffee', 'hot', 'buttered', 'toast', 'soon', 'finished', '.', 'curious', 'feeling', 'said', 'Alice', 'must', 'shutting', 'like', 'telescope', '.', 'indeed', 'ten', 'inches', 'high', 'face', 'brightened', 'thought', 'right', 'size', 'going', 'little', 'door', 'lovely', 'garden', '.', 'First', 'however', 'waited', 'minutes', 'see', 'going', 'shrink', 'felt', 'little', 'nervous', 'might', 'end', 'know', 'said', 'Alice', 'going', 'altogether', 'like', 'candle', '.', 'wonder', 'like', '?', 'tried', 'fancy', 'flame', 'candle', 'like', 'candle', 'blown', 'could', 'remember', 'ever', 'seen', 'thing', '.', 'finding', 'nothing', 'happened', 'decided', 'going', 'garden', 'alas', 'poor', 'Alice', 'got', 'door', 'found', 'forgotten', 'little', 'golden', 'key', 'went', 'back', 'table', 'found', 'could', 'possibly', 'reach', 'could', 'see', 'quite', 'plainly', 'glass', 'tried', 'best', 'climb', 'one', 'legs', 'table', 'slippery', 'tired', 'trying', 'poor', 'little', 'thing', 'sat', 'cried', '.', 'Come', 'use', 'crying', 'like', 'said', 'Alice', 'rather', 'sharply', 'advise', 'leave', 'minute', 'generally', 'gave', 'good', 'advice', 'though', 'seldom', 'followed', 'sometimes', 'scolded', 'severely', 'bring', 'tears', 'eyes', 'remembered', 'trying', 'box', 'ears', 'cheated', 'game', 'croquet', 'playing', 'curious', 'child', 'fond', 'pretending', 'two', 'people', '.', 'use', 'thought', 'poor', 'Alice', 'pretend', 'two', 'people', 'hardly', 'enough', 'left', 'make', 'one', 'respectable', 'person', 'Soon', 'eye', 'fell', 'little', 'glass', 'box', 'lying', 'table', 'opened', 'found', 'small', 'cake', 'words', 'EAT', 'beautifully', 'marked', 'currants', '.', 'Well', 'eat', 'said', 'Alice', 'makes', 'grow', 'larger', 'reach', 'key', 'makes', 'grow', 'smaller', 'creep', 'door', 'either', 'way', 'get', 'garden', 'care', 'happens', 'ate', 'little', 'bit', 'said', 'anxiously', 'way', '?', 'way', '?', 'holding', 'hand', 'top', 'head', 'feel', 'way', 'growing', 'quite', 'surprised', 'find', 'remained', 'size', 'sure', 'generally', 'happens', 'one', 'eats', 'cake', 'Alice', 'got', 'much', 'way', 'expecting', 'nothing', 'out-of-the-way', 'things', 'happen', 'seemed', 'quite', 'dull', 'stupid', 'life', 'go', 'common', 'way', '.', 'set', 'work', 'soon', 'finished', 'cake', '.', 'Pool', 'Tears', 'Curiouser', 'curiouser', 'cried', 'Alice', 'much', 'surprised', 'moment', 'quite', 'forgot', 'speak', 'good', 'English', 'opening', 'like', 'largest', 'telescope', 'ever', 'Good-bye', 'feet', 'looked', 'feet', 'seemed', 'almost', 'sight', 'getting', 'far', '.', 'Oh', 'poor', 'little', 'feet', 'wonder', 'put', 'shoes', 'stockings', 'dears', '?', 'sure', 'able', 'shall', 'great', 'deal', 'far', 'trouble', 'must', 'manage', 'best', 'way', 'must', 'kind', 'thought', 'Alice', 'perhaps', 'walk', 'way', 'want', 'go', 'Let', 'see', 'give', 'new', 'pair', 'boots', 'every', 'Christmas', '.', 'went', 'planning', 'would', 'manage', '.', 'must', 'go', 'carrier', 'thought', 'funny', 'seem', 'sending', 'presents', 'one', 'feet', 'odd', 'directions', 'look', 'Alice', 'Right', 'Foot', 'Esq', '.', 'Hearthrug', 'near', 'Fender', 'Alice', 'love', '.', 'Oh', 'dear', 'nonsense', 'talking', 'head', 'struck', 'roof', 'hall', 'fact', 'nine', 'feet', 'high', 'took', 'little', 'golden', 'key', 'hurried', 'garden', 'door', '.', 'Poor', 'Alice', 'much', 'could', 'lying', 'one', 'side', 'look', 'garden', 'one', 'eye', 'get', 'hopeless', 'ever', 'sat', 'began', 'cry', '.', 'ought', 'ashamed', 'said', 'Alice', 'great', 'girl', 'like', 'might', 'well', 'say', 'go', 'crying', 'way', 'Stop', 'moment', 'tell', 'went', 'shedding', 'gallons', 'tears', 'large', 'pool', 'round', 'four', 'inches', 'deep', 'reaching', 'half', 'hall', '.', 'time', 'heard', 'little', 'pattering', 'feet', 'distance', 'hastily', 'dried', 'eyes', 'see', 'coming', '.', 'White', 'Rabbit', 'returning', 'splendidly', 'dressed', 'pair', 'white', 'kid', 'gloves', 'one', 'hand', 'large', 'fan', 'came', 'trotting', 'along', 'great', 'hurry', 'muttering', 'came', 'Oh', 'Duchess', 'Duchess', 'Oh', 'savage', 'kept', 'waiting', 'Alice', 'felt', 'desperate', 'ready', 'ask', 'help', 'one', 'Rabbit', 'came', 'near', 'began', 'low', 'timid', 'voice', 'please', 'sir', 'Rabbit', 'started', 'violently', 'dropped', 'white', 'kid', 'gloves', 'fan', 'skurried', 'away', 'darkness', 'hard', 'could', 'go', '.', 'Alice', 'took', 'fan', 'gloves', 'hall', 'hot', 'kept', 'fanning', 'time', 'went', 'talking', 'Dear', 'dear', 'queer', 'everything', 'to-day', 'yesterday', 'things', 'went', 'usual', '.', 'wonder', 'changed', 'night', '?', 'Let', 'think', 'got', 'morning', '?', 'almost', 'think', 'remember', 'feeling', 'little', 'different', '.', 'next', 'question', 'world', '?', 'Ah', 'great', 'puzzle', 'began', 'thinking', 'children', 'knew', 'age', 'see', 'could', 'changed', '.', 'sure', 'Ada', 'said', 'hair', 'goes', 'long', 'ringlets', 'mine', 'go', 'ringlets', 'sure', 'Mabel', 'know', 'sorts', 'things', 'oh', 'knows', 'little', 'Besides', 'oh', 'dear', 'puzzling', 'try', 'know', 'things', 'used', 'know', '.', 'Let', 'see', 'four', 'times', 'five', 'twelve', 'four', 'times', 'six', 'thirteen', 'four', 'times', 'seven', 'oh', 'dear', 'shall', 'never', 'get', 'twenty', 'rate', 'However', 'Multiplication', 'Table', 'signify', 'let', 'try', 'Geography', '.', 'London', 'capital', 'Paris', 'Paris', 'capital', 'Rome', 'Rome', 'wrong', 'certain', 'must', 'changed', 'Mabel', 'try', 'say', 'doth', 'little', 'crossed', 'hands', 'lap', 'saying', 'lessons', 'began', 'repeat', 'voice', 'sounded', 'hoarse', 'strange', 'words', 'come', 'used', 'doth', 'little', 'crocodile', 'Improve', 'shining', 'tail', 'pour', 'waters', 'Nile', 'every', 'golden', 'scale', 'cheerfully', 'seems', 'grin', 'neatly', 'spread', 'claws', 'welcome', 'little', 'fishes', 'gently', 'smiling', 'jaws', 'sure', 'right', 'words', 'said', 'poor', 'Alice', 'eyes', 'filled', 'tears', 'went', 'must', 'Mabel', 'shall', 'go', 'live', 'poky', 'little', 'house', 'next', 'toys', 'play', 'oh', 'ever', 'many', 'lessons', 'learn', 'made', 'mind', 'Mabel', 'stay', 'use', 'putting', 'heads', 'saying', 'Come', 'dear', 'shall', 'look', 'say', '?', 'Tell', 'first', 'like', 'person', 'come', 'stay', 'till', 'somebody', 'else', 'oh', 'dear', 'cried', 'Alice', 'sudden', 'burst', 'tears', 'wish', 'would', 'put', 'heads', 'tired', 'alone', 'said', 'looked', 'hands', 'surprised', 'see', 'put', 'one', 'Rabbit', 'little', 'white', 'kid', 'gloves', 'talking', '.', 'done', '?', 'thought', '.', 'must', 'growing', 'small', '.', 'got', 'went', 'table', 'measure', 'found', 'nearly', 'could', 'guess', 'two', 'feet', 'high', 'going', 'shrinking', 'rapidly', 'soon', 'found', 'cause', 'fan', 'holding', 'dropped', 'hastily', 'time', 'avoid', 'shrinking', 'away', 'altogether', '.', 'narrow', 'escape', 'said', 'Alice', 'good', 'deal', 'frightened', 'sudden', 'change', 'glad', 'find', 'still', 'existence', 'garden', 'ran', 'speed', 'back', 'little', 'door', 'alas', 'little', 'door', 'shut', 'little', 'golden', 'key', 'lying', 'glass', 'table', 'things', 'worse', 'ever', 'thought', 'poor', 'child', 'never', 'small', 'never', 'declare', 'bad', 'said', 'words', 'foot', 'slipped', 'another', 'moment', 'splash', 'chin', 'salt', 'water', '.', 'first', 'idea', 'somehow', 'fallen', 'sea', 'case', 'go', 'back', 'railway', 'said', '.', 'Alice', 'seaside', 'life', 'come', 'general', 'conclusion', 'wherever', 'go', 'English', 'coast', 'find', 'number', 'bathing', 'machines', 'sea', 'children', 'digging', 'sand', 'wooden', 'spades', 'row', 'lodging', 'houses', 'behind', 'railway', 'station', '.', 'However', 'soon', 'made', 'pool', 'tears', 'wept', 'nine', 'feet', 'high', '.', 'wish', 'cried', 'much', 'said', 'Alice', 'swam', 'trying', 'find', 'way', '.', 'shall', 'punished', 'suppose', 'drowned', 'tears', 'queer', 'thing', 'sure', 'However', 'everything', 'queer', 'to-day', '.', 'heard', 'something', 'splashing', 'pool', 'little', 'way', 'swam', 'nearer', 'make', 'first', 'thought', 'must', 'walrus', 'hippopotamus', 'remembered', 'small', 'soon', 'made', 'mouse', 'slipped', 'like', '.', 'Would', 'use', 'thought', 'Alice', 'speak', 'mouse', '?', 'Everything', 'out-of-the-way', 'think', 'likely', 'talk', 'rate', 'harm', 'trying', '.', 'began', 'Mouse', 'know', 'way', 'pool', '?', 'tired', 'swimming', 'Mouse', 'Alice', 'thought', 'must', 'right', 'way', 'speaking', 'mouse', 'never', 'done', 'thing', 'remembered', 'seen', 'brother', 'Latin', 'Grammar', 'mouse', 'mouse', 'mouse', 'mouse', 'mouse', 'Mouse', 'looked', 'rather', 'inquisitively', 'seemed', 'wink', 'one', 'little', 'eyes', 'said', 'nothing', '.', 'Perhaps', 'understand', 'English', 'thought', 'Alice', 'daresay', 'French', 'mouse', 'come', 'William', 'Conqueror', '.', 'knowledge', 'history', 'Alice', 'clear', 'notion', 'long', 'ago', 'anything', 'happened', '.', 'began', 'Où', 'est', 'chatte', '?', 'first', 'sentence', 'French', 'lesson-book', '.', 'Mouse', 'gave', 'sudden', 'leap', 'water', 'seemed', 'quiver', 'fright', '.', 'Oh', 'beg', 'pardon', 'cried', 'Alice', 'hastily', 'afraid', 'hurt', 'poor', 'animal', 'feelings', '.', 'quite', 'forgot', 'like', 'cats', '.', 'like', 'cats', 'cried', 'Mouse', 'shrill', 'passionate', 'voice', '.', 'Would', 'like', 'cats', '?', 'Well', 'perhaps', 'said', 'Alice', 'soothing', 'tone', 'angry', '.', 'yet', 'wish', 'could', 'show', 'cat', 'Dinah', 'think', 'take', 'fancy', 'cats', 'could', 'see', '.', 'dear', 'quiet', 'thing', 'Alice', 'went', 'half', 'swam', 'lazily', 'pool', 'sits', 'purring', 'nicely', 'fire', 'licking', 'paws', 'washing', 'face', 'nice', 'soft', 'thing', 'nurse', 'capital', 'one', 'catching', 'mice', 'oh', 'beg', 'pardon', 'cried', 'Alice', 'time', 'Mouse', 'bristling', 'felt', 'certain', 'must', 'really', 'offended', '.', 'talk', 'rather', '.', 'indeed', 'cried', 'Mouse', 'trembling', 'end', 'tail', '.', 'would', 'talk', 'subject', 'family', 'always', 'hated', 'cats', 'nasty', 'low', 'vulgar', 'things', 'let', 'hear', 'name', 'indeed', 'said', 'Alice', 'great', 'hurry', 'change', 'subject', 'conversation', '.', 'fond', 'dogs', '?', 'Mouse', 'answer', 'Alice', 'went', 'eagerly', 'nice', 'little', 'dog', 'near', 'house', 'like', 'show', 'little', 'bright-eyed', 'terrier', 'know', 'oh', 'long', 'curly', 'brown', 'hair', 'fetch', 'things', 'throw', 'sit', 'beg', 'dinner', 'sorts', 'things', 'remember', 'half', 'belongs', 'farmer', 'know', 'says', 'useful', 'worth', 'hundred', 'pounds', 'says', 'kills', 'rats', 'oh', 'dear', 'cried', 'Alice', 'sorrowful', 'tone', 'afraid', 'offended', 'Mouse', 'swimming', 'away', 'hard', 'could', 'go', 'making', 'quite', 'commotion', 'pool', 'went', '.', 'called', 'softly', 'Mouse', 'dear', 'come', 'back', 'talk', 'cats', 'dogs', 'either', 'like', 'Mouse', 'heard', 'turned', 'round', 'swam', 'slowly', 'back', 'face', 'quite', 'pale', 'passion', 'Alice', 'thought', 'said', 'low', 'trembling', 'voice', 'Let', 'us', 'get', 'shore', 'tell', 'history', 'understand', 'hate', 'cats', 'dogs', '.', 'high', 'time', 'go', 'pool', 'getting', 'quite', 'crowded', 'birds', 'animals', 'fallen', 'Duck', 'Dodo', 'Lory', 'Eaglet', 'several', 'curious', 'creatures', '.', 'Alice', 'led', 'way', 'whole', 'party', 'swam', 'shore', '.', 'Caucus-Race', 'Long', 'Tale', 'indeed', 'queer-looking', 'party', 'assembled', 'bank', 'birds', 'draggled', 'feathers', 'animals', 'fur', 'clinging', 'close', 'dripping', 'wet', 'cross', 'uncomfortable', '.', 'first', 'question', 'course', 'get', 'dry', 'consultation', 'minutes', 'seemed', 'quite', 'natural', 'Alice', 'find', 'talking', 'familiarly', 'known', 'life', '.', 'Indeed', 'quite', 'long', 'argument', 'Lory', 'last', 'turned', 'sulky', 'would', 'say', 'older', 'must', 'know', 'better', 'Alice', 'would', 'allow', 'without', 'knowing', 'old', 'Lory', 'positively', 'refused', 'tell', 'age', 'said', '.', 'last', 'Mouse', 'seemed', 'person', 'authority', 'among', 'called', 'Sit', 'listen', 'soon', 'make', 'dry', 'enough', 'sat', 'large', 'ring', 'Mouse', 'middle', '.', 'Alice', 'kept', 'eyes', 'anxiously', 'fixed', 'felt', 'sure', 'would', 'catch', 'bad', 'cold', 'get', 'dry', 'soon', '.', 'Ahem', 'said', 'Mouse', 'important', 'air', 'ready', '?', 'driest', 'thing', 'know', '.', 'Silence', 'round', 'please', 'William', 'Conqueror', 'whose', 'cause', 'favoured', 'pope', 'soon', 'submitted', 'English', 'wanted', 'leaders', 'late', 'much', 'accustomed', 'usurpation', 'conquest', '.', 'Edwin', 'Morcar', 'earls', 'Mercia', 'Northumbria', 'Ugh', 'said', 'Lory', 'shiver', '.', 'beg', 'pardon', 'said', 'Mouse', 'frowning', 'politely', 'speak', '?', 'said', 'Lory', 'hastily', '.', 'thought', 'said', 'Mouse', '.', 'proceed', '.', 'Edwin', 'Morcar', 'earls', 'Mercia', 'Northumbria', 'declared', 'even', 'Stigand', 'patriotic', 'archbishop', 'Canterbury', 'found', 'advisable', 'Found', '?', 'said', 'Duck', '.', 'Found', 'Mouse', 'replied', 'rather', 'crossly', 'course', 'know', 'means', '.', 'know', 'means', 'well', 'enough', 'find', 'thing'

In [57]:
corpus = ' '.join(filtered_text)
corpus

'Rabbit-Hole Alice beginning get tired sitting sister bank nothing twice peeped book sister reading pictures conversations use book thought Alice without pictures conversations ? considering mind well could hot day made feel sleepy stupid whether pleasure making daisy-chain would worth trouble getting picking daisies suddenly White Rabbit pink eyes ran close . nothing remarkable Alice think much way hear Rabbit say Oh dear Oh dear shall late thought afterwards occurred ought wondered time seemed quite natural Rabbit actually took watch waistcoat-pocket looked hurried Alice started feet flashed across mind never seen rabbit either waistcoat-pocket watch take burning curiosity ran across field fortunately time see pop large rabbit-hole hedge . another moment went Alice never considering world get . rabbit-hole went straight like tunnel way dipped suddenly suddenly Alice moment think stopping found falling deep well . Either well deep fell slowly plenty time went look wonder going happen next . First tried look make coming dark see anything looked sides well noticed filled cupboards book-shelves saw maps pictures hung upon pegs . took jar one shelves passed labelled ORANGE MARMALADE great disappointment empty like drop jar fear killing somebody underneath managed put one cupboards fell past . Well thought Alice fall shall think nothing tumbling stairs brave think home say anything even fell top house likely true . . Would fall never come end ? wonder many miles fallen time ? said aloud . must getting somewhere near centre earth . Let see would four thousand miles think see Alice learnt several things sort lessons schoolroom though good opportunity showing knowledge one listen still good practice say yes right distance wonder Latitude Longitude got ? Alice idea Latitude Longitude either thought nice grand words say . Presently began . wonder shall fall right earth funny seem come among people walk heads downward Antipathies think rather glad one listening time sound right word shall ask name country know . Please New Zealand Australia ? tried curtsey spoke fancy curtseying falling air think could manage ? ignorant little girl think asking never ask perhaps shall see written somewhere . . nothing else Alice soon began talking . Dinah miss much to-night think Dinah cat . hope remember saucer milk tea-time . Dinah dear wish mice air afraid might catch bat like mouse know . cats eat bats wonder ? Alice began get rather sleepy went saying dreamy sort way cats eat bats ? cats eat bats ? sometimes bats eat cats ? see answer either question much matter way put . felt dozing begun dream walking hand hand Dinah saying earnestly Dinah tell truth ever eat bat ? suddenly thump thump came upon heap sticks dry leaves fall . Alice bit hurt jumped feet moment looked dark overhead another long passage White Rabbit still sight hurrying . moment lost away went Alice like wind time hear say turned corner Oh ears whiskers late getting close behind turned corner Rabbit longer seen found long low hall lit row lamps hanging roof . doors round hall locked Alice way one side trying every door walked sadly middle wondering ever get . Suddenly came upon little three-legged table made solid glass nothing except tiny golden key Alice first thought might belong one doors hall alas either locks large key small rate would open . However second time round came upon low curtain noticed behind little door fifteen inches high tried little golden key lock great delight fitted Alice opened door found led small passage much larger rat-hole knelt looked along passage loveliest garden ever saw . longed get dark hall wander among beds bright flowers cool fountains could even get head doorway even head would go thought poor Alice would little use without shoulders . Oh wish could shut like telescope think could knew begin . see many out-of-the-way things happened lately Alice begun think things indeed really impossible . seemed use waiting little door went back table half hoping might find another key rate book rules shutting people like telescopes time found little bottle certainly said Alice round neck bottle paper label words DRINK beautifully printed large letters . well say Drink wise little Alice going hurry . look first said see whether marked poison read several nice little histories children got burnt eaten wild beasts unpleasant things would remember simple rules friends taught red-hot poker burn hold long cut finger deeply knife usually bleeds never forgotten drink much bottle marked poison almost certain disagree sooner later . However bottle marked poison Alice ventured taste finding nice fact sort mixed flavour cherry-tart custard pine-apple roast turkey toffee hot buttered toast soon finished . curious feeling said Alice must shutting like telescope . indeed ten inches high face brightened thought right size going little door lovely garden . First however waited minutes see going shrink felt little nervous might end know said Alice going altogether like candle . wonder like ? tried fancy flame candle like candle blown could remember ever seen thing . finding nothing happened decided going garden alas poor Alice got door found forgotten little golden key went back table found could possibly reach could see quite plainly glass tried best climb one legs table slippery tired trying poor little thing sat cried . Come use crying like said Alice rather sharply advise leave minute generally gave good advice though seldom followed sometimes scolded severely bring tears eyes remembered trying box ears cheated game croquet playing curious child fond pretending two people . use thought poor Alice pretend two people hardly enough left make one respectable person Soon eye fell little glass box lying table opened found small cake words EAT beautifully marked currants . Well eat said Alice makes grow larger reach key makes grow smaller creep door either way get garden care happens ate little bit said anxiously way ? way ? holding hand top head feel way growing quite surprised find remained size sure generally happens one eats cake Alice got much way expecting nothing out-of-the-way things happen seemed quite dull stupid life go common way . set work soon finished cake . Pool Tears Curiouser curiouser cried Alice much surprised moment quite forgot speak good English opening like largest telescope ever Good-bye feet looked feet seemed almost sight getting far . Oh poor little feet wonder put shoes stockings dears ? sure able shall great deal far trouble must manage best way must kind thought Alice perhaps walk way want go Let see give new pair boots every Christmas . went planning would manage . must go carrier thought funny seem sending presents one feet odd directions look Alice Right Foot Esq . Hearthrug near Fender Alice love . Oh dear nonsense talking head struck roof hall fact nine feet high took little golden key hurried garden door . Poor Alice much could lying one side look garden one eye get hopeless ever sat began cry . ought ashamed said Alice great girl like might well say go crying way Stop moment tell went shedding gallons tears large pool round four inches deep reaching half hall . time heard little pattering feet distance hastily dried eyes see coming . White Rabbit returning splendidly dressed pair white kid gloves one hand large fan came trotting along great hurry muttering came Oh Duchess Duchess Oh savage kept waiting Alice felt desperate ready ask help one Rabbit came near began low timid voice please sir Rabbit started violently dropped white kid gloves fan skurried away darkness hard could go . Alice took fan gloves hall hot kept fanning time went talking Dear dear queer everything to-day yesterday things went usual . wonder changed night ? Let think got morning ? almost think remember feeling little different . next question world ? Ah great puzzle began thinking children knew age see could changed . sure Ada said hair goes long ringlets mine go ringlets sure Mabel know sorts things oh knows little Besides oh dear puzzling try know things used know . Let see four times five twelve four times six thirteen four times seven oh dear shall never get twenty rate However Multiplication Table signify let try Geography . London capital Paris Paris capital Rome Rome wrong certain must changed Mabel try say doth little crossed hands lap saying lessons began repeat voice sounded hoarse strange words come used doth little crocodile Improve shining tail pour waters Nile every golden scale cheerfully seems grin neatly spread claws welcome little fishes gently smiling jaws sure right words said poor Alice eyes filled tears went must Mabel shall go live poky little house next toys play oh ever many lessons learn made mind Mabel stay use putting heads saying Come dear shall look say ? Tell first like person come stay till somebody else oh dear cried Alice sudden burst tears wish would put heads tired alone said looked hands surprised see put one Rabbit little white kid gloves talking . done ? thought . must growing small . got went table measure found nearly could guess two feet high going shrinking rapidly soon found cause fan holding dropped hastily time avoid shrinking away altogether . narrow escape said Alice good deal frightened sudden change glad find still existence garden ran speed back little door alas little door shut little golden key lying glass table things worse ever thought poor child never small never declare bad said words foot slipped another moment splash chin salt water . first idea somehow fallen sea case go back railway said . Alice seaside life come general conclusion wherever go English coast find number bathing machines sea children digging sand wooden spades row lodging houses behind railway station . However soon made pool tears wept nine feet high . wish cried much said Alice swam trying find way . shall punished suppose drowned tears queer thing sure However everything queer to-day . heard something splashing pool little way swam nearer make first thought must walrus hippopotamus remembered small soon made mouse slipped like . Would use thought Alice speak mouse ? Everything out-of-the-way think likely talk rate harm trying . began Mouse know way pool ? tired swimming Mouse Alice thought must right way speaking mouse never done thing remembered seen brother Latin Grammar mouse mouse mouse mouse mouse Mouse looked rather inquisitively seemed wink one little eyes said nothing . Perhaps understand English thought Alice daresay French mouse come William Conqueror . knowledge history Alice clear notion long ago anything happened . began Où est chatte ? first sentence French lesson-book . Mouse gave sudden leap water seemed quiver fright . Oh beg pardon cried Alice hastily afraid hurt poor animal feelings . quite forgot like cats . like cats cried Mouse shrill passionate voice . Would like cats ? Well perhaps said Alice soothing tone angry . yet wish could show cat Dinah think take fancy cats could see . dear quiet thing Alice went half swam lazily pool sits purring nicely fire licking paws washing face nice soft thing nurse capital one catching mice oh beg pardon cried Alice time Mouse bristling felt certain must really offended . talk rather . indeed cried Mouse trembling end tail . would talk subject family always hated cats nasty low vulgar things let hear name indeed said Alice great hurry change subject conversation . fond dogs ? Mouse answer Alice went eagerly nice little dog near house like show little bright-eyed terrier know oh long curly brown hair fetch things throw sit beg dinner sorts things remember half belongs farmer know says useful worth hundred pounds says kills rats oh dear cried Alice sorrowful tone afraid offended Mouse swimming away hard could go making quite commotion pool went . called softly Mouse dear come back talk cats dogs either like Mouse heard turned round swam slowly back face quite pale passion Alice thought said low trembling voice Let us get shore tell history understand hate cats dogs . high time go pool getting quite crowded birds animals fallen Duck Dodo Lory Eaglet several curious creatures . Alice led way whole party swam shore . Caucus-Race Long Tale indeed queer-looking party assembled bank birds draggled feathers animals fur clinging close dripping wet cross uncomfortable . first question course get dry consultation minutes seemed quite natural Alice find talking familiarly known life . Indeed quite long argument Lory last turned sulky would say older must know better Alice would allow without knowing old Lory positively refused tell age said . last Mouse seemed person authority among called Sit listen soon make dry enough sat large ring Mouse middle . Alice kept eyes anxiously fixed felt sure would catch bad cold get dry soon . Ahem said Mouse important air ready ? driest thing know . Silence round please William Conqueror whose cause favoured pope soon submitted English wanted leaders late much accustomed usurpation conquest . Edwin Morcar earls Mercia Northumbria Ugh said Lory shiver . beg pardon said Mouse frowning politely speak ? said Lory hastily . thought said Mouse . proceed . Edwin Morcar earls Mercia Northumbria declared even Stigand patriotic archbishop Canterbury found advisable Found ? said Duck . Found Mouse replied rather crossly course know means . know means well enough find thing said Duck generally frog worm . question archbishop find ? Mouse notice question hurriedly went found advisable go Edgar Atheling meet William offer crown . William conduct first moderate . insolence Normans getting dear ? continued turning Alice spoke . wet ever said Alice melancholy tone seem dry . case said Dodo solemnly rising feet move meeting adjourn immediate adoption energetic remedies Speak English said Eaglet . know meaning half long words believe either Eaglet bent head hide smile birds tittered audibly . going say said Dodo offended tone best thing get us dry would Caucus-race . Caucus-race ? said Alice wanted much know Dodo paused thought somebody ought speak one else seemed inclined say anything . said Dodo best way explain . might like try thing winter day tell Dodo managed . First marked race-course sort circle exact shape matter said party placed along course . One two three away began running liked left liked easy know race . However running half hour quite dry Dodo suddenly called race crowded round panting asking ? question Dodo could answer without great deal thought sat long time one finger pressed upon forehead position usually see Shakespeare pictures rest waited silence . last Dodo said Everybody must prizes . give prizes ? quite chorus voices asked . course said Dodo pointing Alice one finger whole party crowded round calling confused way Prizes Prizes Alice idea despair put hand pocket pulled box comfits luckily salt water got handed round prizes . exactly one a-piece round . must prize know said Mouse . course Dodo replied gravely . else got pocket ? went turning Alice . thimble said Alice sadly . Hand said Dodo . crowded round Dodo solemnly presented thimble saying beg acceptance elegant thimble finished short speech cheered . Alice thought whole thing absurd looked grave dare laugh could think anything say simply bowed took thimble looking solemn could . next thing eat comfits caused noise confusion large birds complained could taste small ones choked patted back . However last sat ring begged Mouse tell something . promised tell history know said Alice hate C added whisper half afraid would offended . Mine long sad tale said Mouse turning Alice sighing . long tail certainly said Alice looking wonder Mouse tail call sad ? kept puzzling Mouse speaking idea tale something like Fury said mouse met house Let us go law prosecute . Come take denial must trial really morning nothing . Said mouse cur trial dear sir jury judge would wasting breath . judge jury Said cunning old Fury try whole cause condemn death . attending said Mouse Alice severely . thinking ? beg pardon said Alice humbly got fifth bend think ? cried Mouse sharply angrily . knot said Alice always ready make useful looking anxiously . Oh let help undo shall nothing sort said Mouse getting walking away . insult talking nonsense mean pleaded poor Alice . easily offended know Mouse growled reply . Please come back finish story Alice called others joined chorus Yes please Mouse shook head impatiently walked little quicker . pity stay sighed Lory soon quite sight old Crab took opportunity saying daughter Ah dear Let lesson never lose temper Hold tongue said young Crab little snappishly . enough try patience oyster wish Dinah know said Alice aloud addressing nobody particular . soon fetch back Dinah might venture ask question ? said Lory . Alice replied eagerly always ready talk pet Dinah cat . capital one catching mice think oh wish could see birds eat little bird soon look speech caused remarkable sensation among party . birds hurried one old Magpie began wrapping carefully remarking really must getting home night-air suit throat Canary called trembling voice children Come away dears high time bed various pretexts moved Alice soon left alone . wish mentioned Dinah said melancholy tone . Nobody seems like sure best cat world Oh dear Dinah wonder shall ever see poor Alice began cry felt lonely low-spirited . little however heard little pattering footsteps distance looked eagerly half hoping Mouse changed mind coming back finish story . Rabbit Sends Little Bill White Rabbit trotting slowly back looking anxiously went lost something heard muttering Duchess Duchess Oh dear paws Oh fur whiskers get executed sure ferrets ferrets dropped wonder ? Alice guessed moment looking fan pair white kid gloves good-naturedly began hunting nowhere seen everything seemed changed since swim pool great hall glass table little door vanished completely . soon Rabbit noticed Alice went hunting called angry tone Mary Ann ? Run home moment fetch pair gloves fan Quick Alice much frightened ran direction pointed without trying explain mistake made . took housemaid said ran . surprised finds better take fan gloves find . said came upon neat little house door bright brass plate name W. RABBIT engraved upon . went without knocking hurried upstairs great fear lest meet real Mary Ann turned house found fan gloves . queer seems Alice said going messages rabbit suppose Dinah sending messages next began fancying sort thing would happen Miss Alice Come directly get ready walk Coming minute nurse got see mouse get . think Alice went let Dinah stop house began ordering people like time found way tidy little room table window hoped fan two three pairs tiny white kid gloves took fan pair gloves going leave room eye fell upon little bottle stood near looking-glass . label time words DRINK nevertheless uncorked put lips . know something interesting sure happen said whenever eat drink anything see bottle . hope make grow large really quite tired tiny little thing indeed much sooner expected drunk half bottle found head pressing ceiling stoop save neck broken . hastily put bottle saying quite enough hope grow get door wish drunk quite much Alas late wish went growing growing soon kneel floor another minute even room tried effect lying one elbow door arm curled round head . Still went growing last resource put one arm window one foot chimney said whatever happens . become ? Luckily Alice little magic bottle full effect grew larger still uncomfortable seemed sort chance ever getting room wonder felt unhappy . much pleasanter home thought poor Alice one always growing larger smaller ordered mice rabbits . almost wish gone rabbit-hole yet yet rather curious know sort life wonder happened used read fairy-tales fancied kind thing never happened middle one ought book written ought grow write one grown added sorrowful tone least room grow . thought Alice shall never get older ? comfort one way never old woman always lessons learn Oh like Oh foolish Alice answered 

In [58]:
corpus = re.sub(r'\s+([\.!?\-”’])', r'\1', corpus) #to remove extra spaces before punctations
corpus

'Rabbit-Hole Alice beginning get tired sitting sister bank nothing twice peeped book sister reading pictures conversations use book thought Alice without pictures conversations? considering mind well could hot day made feel sleepy stupid whether pleasure making daisy-chain would worth trouble getting picking daisies suddenly White Rabbit pink eyes ran close. nothing remarkable Alice think much way hear Rabbit say Oh dear Oh dear shall late thought afterwards occurred ought wondered time seemed quite natural Rabbit actually took watch waistcoat-pocket looked hurried Alice started feet flashed across mind never seen rabbit either waistcoat-pocket watch take burning curiosity ran across field fortunately time see pop large rabbit-hole hedge. another moment went Alice never considering world get. rabbit-hole went straight like tunnel way dipped suddenly suddenly Alice moment think stopping found falling deep well. Either well deep fell slowly plenty time went look wonder going happen next. First tried look make coming dark see anything looked sides well noticed filled cupboards book-shelves saw maps pictures hung upon pegs. took jar one shelves passed labelled ORANGE MARMALADE great disappointment empty like drop jar fear killing somebody underneath managed put one cupboards fell past. Well thought Alice fall shall think nothing tumbling stairs brave think home say anything even fell top house likely true.. Would fall never come end? wonder many miles fallen time? said aloud. must getting somewhere near centre earth. Let see would four thousand miles think see Alice learnt several things sort lessons schoolroom though good opportunity showing knowledge one listen still good practice say yes right distance wonder Latitude Longitude got? Alice idea Latitude Longitude either thought nice grand words say. Presently began. wonder shall fall right earth funny seem come among people walk heads downward Antipathies think rather glad one listening time sound right word shall ask name country know. Please New Zealand Australia? tried curtsey spoke fancy curtseying falling air think could manage? ignorant little girl think asking never ask perhaps shall see written somewhere.. nothing else Alice soon began talking. Dinah miss much to-night think Dinah cat. hope remember saucer milk tea-time. Dinah dear wish mice air afraid might catch bat like mouse know. cats eat bats wonder? Alice began get rather sleepy went saying dreamy sort way cats eat bats? cats eat bats? sometimes bats eat cats? see answer either question much matter way put. felt dozing begun dream walking hand hand Dinah saying earnestly Dinah tell truth ever eat bat? suddenly thump thump came upon heap sticks dry leaves fall. Alice bit hurt jumped feet moment looked dark overhead another long passage White Rabbit still sight hurrying. moment lost away went Alice like wind time hear say turned corner Oh ears whiskers late getting close behind turned corner Rabbit longer seen found long low hall lit row lamps hanging roof. doors round hall locked Alice way one side trying every door walked sadly middle wondering ever get. Suddenly came upon little three-legged table made solid glass nothing except tiny golden key Alice first thought might belong one doors hall alas either locks large key small rate would open. However second time round came upon low curtain noticed behind little door fifteen inches high tried little golden key lock great delight fitted Alice opened door found led small passage much larger rat-hole knelt looked along passage loveliest garden ever saw. longed get dark hall wander among beds bright flowers cool fountains could even get head doorway even head would go thought poor Alice would little use without shoulders. Oh wish could shut like telescope think could knew begin. see many out-of-the-way things happened lately Alice begun think things indeed really impossible. seemed use waiting little door went back table half hoping might find another key rate book rules shutting people like telescopes time found little bottle certainly said Alice round neck bottle paper label words DRINK beautifully printed large letters. well say Drink wise little Alice going hurry. look first said see whether marked poison read several nice little histories children got burnt eaten wild beasts unpleasant things would remember simple rules friends taught red-hot poker burn hold long cut finger deeply knife usually bleeds never forgotten drink much bottle marked poison almost certain disagree sooner later. However bottle marked poison Alice ventured taste finding nice fact sort mixed flavour cherry-tart custard pine-apple roast turkey toffee hot buttered toast soon finished. curious feeling said Alice must shutting like telescope. indeed ten inches high face brightened thought right size going little door lovely garden. First however waited minutes see going shrink felt little nervous might end know said Alice going altogether like candle. wonder like? tried fancy flame candle like candle blown could remember ever seen thing. finding nothing happened decided going garden alas poor Alice got door found forgotten little golden key went back table found could possibly reach could see quite plainly glass tried best climb one legs table slippery tired trying poor little thing sat cried. Come use crying like said Alice rather sharply advise leave minute generally gave good advice though seldom followed sometimes scolded severely bring tears eyes remembered trying box ears cheated game croquet playing curious child fond pretending two people. use thought poor Alice pretend two people hardly enough left make one respectable person Soon eye fell little glass box lying table opened found small cake words EAT beautifully marked currants. Well eat said Alice makes grow larger reach key makes grow smaller creep door either way get garden care happens ate little bit said anxiously way? way? holding hand top head feel way growing quite surprised find remained size sure generally happens one eats cake Alice got much way expecting nothing out-of-the-way things happen seemed quite dull stupid life go common way. set work soon finished cake. Pool Tears Curiouser curiouser cried Alice much surprised moment quite forgot speak good English opening like largest telescope ever Good-bye feet looked feet seemed almost sight getting far. Oh poor little feet wonder put shoes stockings dears? sure able shall great deal far trouble must manage best way must kind thought Alice perhaps walk way want go Let see give new pair boots every Christmas. went planning would manage. must go carrier thought funny seem sending presents one feet odd directions look Alice Right Foot Esq. Hearthrug near Fender Alice love. Oh dear nonsense talking head struck roof hall fact nine feet high took little golden key hurried garden door. Poor Alice much could lying one side look garden one eye get hopeless ever sat began cry. ought ashamed said Alice great girl like might well say go crying way Stop moment tell went shedding gallons tears large pool round four inches deep reaching half hall. time heard little pattering feet distance hastily dried eyes see coming. White Rabbit returning splendidly dressed pair white kid gloves one hand large fan came trotting along great hurry muttering came Oh Duchess Duchess Oh savage kept waiting Alice felt desperate ready ask help one Rabbit came near began low timid voice please sir Rabbit started violently dropped white kid gloves fan skurried away darkness hard could go. Alice took fan gloves hall hot kept fanning time went talking Dear dear queer everything to-day yesterday things went usual. wonder changed night? Let think got morning? almost think remember feeling little different. next question world? Ah great puzzle began thinking children knew age see could changed. sure Ada said hair goes long ringlets mine go ringlets sure Mabel know sorts things oh knows little Besides oh dear puzzling try know things used know. Let see four times five twelve four times six thirteen four times seven oh dear shall never get twenty rate However Multiplication Table signify let try Geography. London capital Paris Paris capital Rome Rome wrong certain must changed Mabel try say doth little crossed hands lap saying lessons began repeat voice sounded hoarse strange words come used doth little crocodile Improve shining tail pour waters Nile every golden scale cheerfully seems grin neatly spread claws welcome little fishes gently smiling jaws sure right words said poor Alice eyes filled tears went must Mabel shall go live poky little house next toys play oh ever many lessons learn made mind Mabel stay use putting heads saying Come dear shall look say? Tell first like person come stay till somebody else oh dear cried Alice sudden burst tears wish would put heads tired alone said looked hands surprised see put one Rabbit little white kid gloves talking. done? thought. must growing small. got went table measure found nearly could guess two feet high going shrinking rapidly soon found cause fan holding dropped hastily time avoid shrinking away altogether. narrow escape said Alice good deal frightened sudden change glad find still existence garden ran speed back little door alas little door shut little golden key lying glass table things worse ever thought poor child never small never declare bad said words foot slipped another moment splash chin salt water. first idea somehow fallen sea case go back railway said. Alice seaside life come general conclusion wherever go English coast find number bathing machines sea children digging sand wooden spades row lodging houses behind railway station. However soon made pool tears wept nine feet high. wish cried much said Alice swam trying find way. shall punished suppose drowned tears queer thing sure However everything queer to-day. heard something splashing pool little way swam nearer make first thought must walrus hippopotamus remembered small soon made mouse slipped like. Would use thought Alice speak mouse? Everything out-of-the-way think likely talk rate harm trying. began Mouse know way pool? tired swimming Mouse Alice thought must right way speaking mouse never done thing remembered seen brother Latin Grammar mouse mouse mouse mouse mouse Mouse looked rather inquisitively seemed wink one little eyes said nothing. Perhaps understand English thought Alice daresay French mouse come William Conqueror. knowledge history Alice clear notion long ago anything happened. began Où est chatte? first sentence French lesson-book. Mouse gave sudden leap water seemed quiver fright. Oh beg pardon cried Alice hastily afraid hurt poor animal feelings. quite forgot like cats. like cats cried Mouse shrill passionate voice. Would like cats? Well perhaps said Alice soothing tone angry. yet wish could show cat Dinah think take fancy cats could see. dear quiet thing Alice went half swam lazily pool sits purring nicely fire licking paws washing face nice soft thing nurse capital one catching mice oh beg pardon cried Alice time Mouse bristling felt certain must really offended. talk rather. indeed cried Mouse trembling end tail. would talk subject family always hated cats nasty low vulgar things let hear name indeed said Alice great hurry change subject conversation. fond dogs? Mouse answer Alice went eagerly nice little dog near house like show little bright-eyed terrier know oh long curly brown hair fetch things throw sit beg dinner sorts things remember half belongs farmer know says useful worth hundred pounds says kills rats oh dear cried Alice sorrowful tone afraid offended Mouse swimming away hard could go making quite commotion pool went. called softly Mouse dear come back talk cats dogs either like Mouse heard turned round swam slowly back face quite pale passion Alice thought said low trembling voice Let us get shore tell history understand hate cats dogs. high time go pool getting quite crowded birds animals fallen Duck Dodo Lory Eaglet several curious creatures. Alice led way whole party swam shore. Caucus-Race Long Tale indeed queer-looking party assembled bank birds draggled feathers animals fur clinging close dripping wet cross uncomfortable. first question course get dry consultation minutes seemed quite natural Alice find talking familiarly known life. Indeed quite long argument Lory last turned sulky would say older must know better Alice would allow without knowing old Lory positively refused tell age said. last Mouse seemed person authority among called Sit listen soon make dry enough sat large ring Mouse middle. Alice kept eyes anxiously fixed felt sure would catch bad cold get dry soon. Ahem said Mouse important air ready? driest thing know. Silence round please William Conqueror whose cause favoured pope soon submitted English wanted leaders late much accustomed usurpation conquest. Edwin Morcar earls Mercia Northumbria Ugh said Lory shiver. beg pardon said Mouse frowning politely speak? said Lory hastily. thought said Mouse. proceed. Edwin Morcar earls Mercia Northumbria declared even Stigand patriotic archbishop Canterbury found advisable Found? said Duck. Found Mouse replied rather crossly course know means. know means well enough find thing said Duck generally frog worm. question archbishop find? Mouse notice question hurriedly went found advisable go Edgar Atheling meet William offer crown. William conduct first moderate. insolence Normans getting dear? continued turning Alice spoke. wet ever said Alice melancholy tone seem dry. case said Dodo solemnly rising feet move meeting adjourn immediate adoption energetic remedies Speak English said Eaglet. know meaning half long words believe either Eaglet bent head hide smile birds tittered audibly. going say said Dodo offended tone best thing get us dry would Caucus-race. Caucus-race? said Alice wanted much know Dodo paused thought somebody ought speak one else seemed inclined say anything. said Dodo best way explain. might like try thing winter day tell Dodo managed. First marked race-course sort circle exact shape matter said party placed along course. One two three away began running liked left liked easy know race. However running half hour quite dry Dodo suddenly called race crowded round panting asking? question Dodo could answer without great deal thought sat long time one finger pressed upon forehead position usually see Shakespeare pictures rest waited silence. last Dodo said Everybody must prizes. give prizes? quite chorus voices asked. course said Dodo pointing Alice one finger whole party crowded round calling confused way Prizes Prizes Alice idea despair put hand pocket pulled box comfits luckily salt water got handed round prizes. exactly one a-piece round. must prize know said Mouse. course Dodo replied gravely. else got pocket? went turning Alice. thimble said Alice sadly. Hand said Dodo. crowded round Dodo solemnly presented thimble saying beg acceptance elegant thimble finished short speech cheered. Alice thought whole thing absurd looked grave dare laugh could think anything say simply bowed took thimble looking solemn could. next thing eat comfits caused noise confusion large birds complained could taste small ones choked patted back. However last sat ring begged Mouse tell something. promised tell history know said Alice hate C added whisper half afraid would offended. Mine long sad tale said Mouse turning Alice sighing. long tail certainly said Alice looking wonder Mouse tail call sad? kept puzzling Mouse speaking idea tale something like Fury said mouse met house Let us go law prosecute. Come take denial must trial really morning nothing. Said mouse cur trial dear sir jury judge would wasting breath. judge jury Said cunning old Fury try whole cause condemn death. attending said Mouse Alice severely. thinking? beg pardon said Alice humbly got fifth bend think? cried Mouse sharply angrily. knot said Alice always ready make useful looking anxiously. Oh let help undo shall nothing sort said Mouse getting walking away. insult talking nonsense mean pleaded poor Alice. easily offended know Mouse growled reply. Please come back finish story Alice called others joined chorus Yes please Mouse shook head impatiently walked little quicker. pity stay sighed Lory soon quite sight old Crab took opportunity saying daughter Ah dear Let lesson never lose temper Hold tongue said young Crab little snappishly. enough try patience oyster wish Dinah know said Alice aloud addressing nobody particular. soon fetch back Dinah might venture ask question? said Lory. Alice replied eagerly always ready talk pet Dinah cat. capital one catching mice think oh wish could see birds eat little bird soon look speech caused remarkable sensation among party. birds hurried one old Magpie began wrapping carefully remarking really must getting home night-air suit throat Canary called trembling voice children Come away dears high time bed various pretexts moved Alice soon left alone. wish mentioned Dinah said melancholy tone. Nobody seems like sure best cat world Oh dear Dinah wonder shall ever see poor Alice began cry felt lonely low-spirited. little however heard little pattering footsteps distance looked eagerly half hoping Mouse changed mind coming back finish story. Rabbit Sends Little Bill White Rabbit trotting slowly back looking anxiously went lost something heard muttering Duchess Duchess Oh dear paws Oh fur whiskers get executed sure ferrets ferrets dropped wonder? Alice guessed moment looking fan pair white kid gloves good-naturedly began hunting nowhere seen everything seemed changed since swim pool great hall glass table little door vanished completely. soon Rabbit noticed Alice went hunting called angry tone Mary Ann? Run home moment fetch pair gloves fan Quick Alice much frightened ran direction pointed without trying explain mistake made. took housemaid said ran. surprised finds better take fan gloves find. said came upon neat little house door bright brass plate name W. RABBIT engraved upon. went without knocking hurried upstairs great fear lest meet real Mary Ann turned house found fan gloves. queer seems Alice said going messages rabbit suppose Dinah sending messages next began fancying sort thing would happen Miss Alice Come directly get ready walk Coming minute nurse got see mouse get. think Alice went let Dinah stop house began ordering people like time found way tidy little room table window hoped fan two three pairs tiny white kid gloves took fan pair gloves going leave room eye fell upon little bottle stood near looking-glass. label time words DRINK nevertheless uncorked put lips. know something interesting sure happen said whenever eat drink anything see bottle. hope make grow large really quite tired tiny little thing indeed much sooner expected drunk half bottle found head pressing ceiling stoop save neck broken. hastily put bottle saying quite enough hope grow get door wish drunk quite much Alas late wish went growing growing soon kneel floor another minute even room tried effect lying one elbow door arm curled round head. Still went growing last resource put one arm window one foot chimney said whatever happens. become? Luckily Alice little magic bottle full effect grew larger still uncomfortable seemed sort chance ever getting room wonder felt unhappy. much pleasanter home thought poor Alice one always growing larger smaller ordered mice rabbits. almost wish gone rabbit-hole yet yet rather curious know sort life wonder happened used read fairy-tales fancied kind thing never happened middle one ought book written ought grow write one grown added sorrowful tone least room grow. thought Alice shall never get older? comfort one way never old woman always lessons learn Oh like Oh foolish Alice answered. learn lessons? hardly room room lesson-books went taking first one side making quite conversation altogether minutes heard voice outside stopped listen. Mary Ann Mary Ann said voice. Fetch gloves moment came

In [59]:
len(corpus)

78938

In [60]:
segments = sent_tokenize(corpus.lower())
segments

['rabbit-hole alice beginning get tired sitting sister bank nothing twice peeped book sister reading pictures conversations use book thought alice without pictures conversations?',
 'considering mind well could hot day made feel sleepy stupid whether pleasure making daisy-chain would worth trouble getting picking daisies suddenly white rabbit pink eyes ran close.',
 'nothing remarkable alice think much way hear rabbit say oh dear oh dear shall late thought afterwards occurred ought wondered time seemed quite natural rabbit actually took watch waistcoat-pocket looked hurried alice started feet flashed across mind never seen rabbit either waistcoat-pocket watch take burning curiosity ran across field fortunately time see pop large rabbit-hole hedge.',
 'another moment went alice never considering world get.',
 'rabbit-hole went straight like tunnel way dipped suddenly suddenly alice moment think stopping found falling deep well.',
 'either well deep fell slowly plenty time went look wonder going happen next.',
 'first tried look make coming dark see anything looked sides well noticed filled cupboards book-shelves saw maps pictures hung upon pegs.',
 'took jar one shelves passed labelled orange marmalade great disappointment empty like drop jar fear killing somebody underneath managed put one cupboards fell past.',
 'well thought alice fall shall think nothing tumbling stairs brave think home say anything even fell top house likely true.. would fall never come end?',
 'wonder many miles fallen time?',
 'said aloud.',
 'must getting somewhere near centre earth.',
 'let see would four thousand miles think see alice learnt several things sort lessons schoolroom though good opportunity showing knowledge one listen still good practice say yes right distance wonder latitude longitude got?',
 'alice idea latitude longitude either thought nice grand words say.',
 'presently began.',
 'wonder shall fall right earth funny seem come among people walk heads downward antipathies think rather glad one listening time sound right word shall ask name country know.',
 'please new zealand australia?',
 'tried curtsey spoke fancy curtseying falling air think could manage?',
 'ignorant little girl think asking never ask perhaps shall see written somewhere.. nothing else alice soon began talking.',
 'dinah miss much to-night think dinah cat.',
 'hope remember saucer milk tea-time.',
 'dinah dear wish mice air afraid might catch bat like mouse know.',
 'cats eat bats wonder?',
 'alice began get rather sleepy went saying dreamy sort way cats eat bats?',
 'cats eat bats?',
 'sometimes bats eat cats?',
 'see answer either question much matter way put.',
 'felt dozing begun dream walking hand hand dinah saying earnestly dinah tell truth ever eat bat?',
 'suddenly thump thump came upon heap sticks dry leaves fall.',
 'alice bit hurt jumped feet moment looked dark overhead another long passage white rabbit still sight hurrying.',
 'moment lost away went alice like wind time hear say turned corner oh ears whiskers late getting close behind turned corner rabbit longer seen found long low hall lit row lamps hanging roof.',
 'doors round hall locked alice way one side trying every door walked sadly middle wondering ever get.',
 'suddenly came upon little three-legged table made solid glass nothing except tiny golden key alice first thought might belong one doors hall alas either locks large key small rate would open.',
 'however second time round came upon low curtain noticed behind little door fifteen inches high tried little golden key lock great delight fitted alice opened door found led small passage much larger rat-hole knelt looked along passage loveliest garden ever saw.',
 'longed get dark hall wander among beds bright flowers cool fountains could even get head doorway even head would go thought poor alice would little use without shoulders.',
 'oh wish could shut like telescope think could knew begin.',
 'see many out-of-the-way things happened lately alice begun think things indeed really impossible.',
 'seemed use waiting little door went back table half hoping might find another key rate book rules shutting people like telescopes time found little bottle certainly said alice round neck bottle paper label words drink beautifully printed large letters.',
 'well say drink wise little alice going hurry.',
 'look first said see whether marked poison read several nice little histories children got burnt eaten wild beasts unpleasant things would remember simple rules friends taught red-hot poker burn hold long cut finger deeply knife usually bleeds never forgotten drink much bottle marked poison almost certain disagree sooner later.',
 'however bottle marked poison alice ventured taste finding nice fact sort mixed flavour cherry-tart custard pine-apple roast turkey toffee hot buttered toast soon finished.',
 'curious feeling said alice must shutting like telescope.',
 'indeed ten inches high face brightened thought right size going little door lovely garden.',
 'first however waited minutes see going shrink felt little nervous might end know said alice going altogether like candle.',
 'wonder like?',
 'tried fancy flame candle like candle blown could remember ever seen thing.',
 'finding nothing happened decided going garden alas poor alice got door found forgotten little golden key went back table found could possibly reach could see quite plainly glass tried best climb one legs table slippery tired trying poor little thing sat cried.',
 'come use crying like said alice rather sharply advise leave minute generally gave good advice though seldom followed sometimes scolded severely bring tears eyes remembered trying box ears cheated game croquet playing curious child fond pretending two people.',
 'use thought poor alice pretend two people hardly enough left make one respectable person soon eye fell little glass box lying table opened found small cake words eat beautifully marked currants.',
 'well eat said alice makes grow larger reach key makes grow smaller creep door either way get garden care happens ate little bit said anxiously way?',
 'way?',
 'holding hand top head feel way growing quite surprised find remained size sure generally happens one eats cake alice got much way expecting nothing out-of-the-way things happen seemed quite dull stupid life go common way.',
 'set work soon finished cake.',
 'pool tears curiouser curiouser cried alice much surprised moment quite forgot speak good english opening like largest telescope ever good-bye feet looked feet seemed almost sight getting far.',
 'oh poor little feet wonder put shoes stockings dears?',
 'sure able shall great deal far trouble must manage best way must kind thought alice perhaps walk way want go let see give new pair boots every christmas.',
 'went planning would manage.',
 'must go carrier thought funny seem sending presents one feet odd directions look alice right foot esq.',
 'hearthrug near fender alice love.',
 'oh dear nonsense talking head struck roof hall fact nine feet high took little golden key hurried garden door.',
 'poor alice much could lying one side look garden one eye get hopeless ever sat began cry.',
 'ought ashamed said alice great girl like might well say go crying way stop moment tell went shedding gallons tears large pool round four inches deep reaching half hall.',
 'time heard little pattering feet distance hastily dried eyes see coming.',
 'white rabbit returning splendidly dressed pair white kid gloves one hand large fan came trotting along great hurry muttering came oh duchess duchess oh savage kept waiting alice felt desperate ready ask help one rabbit came near began low timid voice please sir rabbit started violently dropped white kid gloves fan skurried away darkness hard could go.',
 'alice took fan gloves hall hot kept fanning time went talking dear dear queer everything to-day yesterday things went usual.',
 'wonder changed night?',
 'let think got morning?',
 'almost think remember feeling little different.',
 'next question world?',
 'ah great puzzle began thinking children knew age see could changed.',
 'sure ada said hair goes long ringlets mine go ringlets sure mabel know sorts things oh knows little besides oh dear puzzling try know things used know.',
 'let see four times five twelve four times six thirteen four times seven oh dear shall never get twenty rate however multiplication table signify let try geography.',
 'london capital paris paris capital rome rome wrong certain must changed mabel try say doth little crossed hands lap saying lessons began repeat voice sounded hoarse strange words come used doth little crocodile improve shining tail pour waters nile every golden scale cheerfully seems grin neatly spread claws welcome little fishes gently smiling jaws sure right words said poor alice eyes filled tears went must mabel shall go live poky little house next toys play oh ever many lessons learn made mind mabel stay use putting heads saying come dear shall look say?',
 'tell first like person come stay till somebody else oh dear cried alice sudden burst tears wish would put heads tired alone said looked hands surprised see put one rabbit little white kid gloves talking.',
 'done?',
 'thought.',
 'must growing small.',
 'got went table measure found nearly could guess two feet high going shrinking rapidly soon found cause fan holding dropped hastily time avoid shrinking away altogether.',
 'narrow escape said alice good deal frightened sudden change glad find still existence garden ran speed back little door alas little door shut little golden key lying glass table things worse ever thought poor child never small never declare bad said words foot slipped another moment splash chin salt water.',
 'first idea somehow fallen sea case go back railway said.',
 'alice seaside life come general conclusion wherever go english coast find number bathing machines sea children digging sand wooden spades row lodging houses behind railway station.',
 'however soon made pool tears wept nine feet high.',
 'wish cried much said alice swam trying find way.',
 'shall punished suppose drowned tears queer thing sure however everything queer to-day.',
 'heard something splashing pool little way swam nearer make first thought must walrus hippopotamus remembered small soon made mouse slipped like.',
 'would use thought alice speak mouse?',
 'everything out-of-the-way think likely talk rate harm trying.',
 'began mouse know way pool?',
 'tired swimming mouse alice thought must right way speaking mouse never done thing remembered seen brother latin grammar mouse mouse mouse mouse mouse mouse looked rather inquisitively seemed wink one little eyes said nothing.',
 'perhaps understand english thought alice daresay french mouse come william conqueror.',
 'knowledge history alice clear notion long ago anything happened.',
 'began où est chatte?',
 'first sentence french lesson-book.',
 'mouse gave sudden leap water seemed quiver fright.',
 'oh beg pardon cried alice hastily afraid hurt poor animal feelings.',
 'quite forgot like cats.',
 'like cats cried mouse shrill passionate voice.',
 'would like cats?',
 'well perhaps said alice soothing tone angry.',
 'yet wish could show cat dinah think take fancy cats could see.',
 'dear quiet thing alice went half swam lazily pool sits purring nicely fire licking paws washing face nice soft thing nurse capital one catching mice oh beg pardon cried alice time mouse bristling felt certain must really offended.',
 'talk rather.',
 'indeed cried mouse trembling end tail.',
 'would talk subject family always hated cats nasty low vulgar things let hear name indeed said alice great hurry change subject conversation.',
 'fond dogs?',
 'mouse answer alice went eagerly nice little dog near house like show little bright-eyed terrier know oh long curly brown hair fetch things throw sit beg dinner sorts things remember half belongs farmer know says useful worth hundred pounds says kills rats oh dear cried alice sorrowful tone afraid offended mouse swimming away hard could go making quite commotion pool went.',
 'called softly mouse dear come back talk cats dogs either like mouse heard turned round swam slowly back face quite pale passion alice thought said low trembling voice let us get shore tell history understand hate cats dogs.',
 'high time go pool getting quite crowded birds animals fallen duck dodo lory eaglet several curious creatures.',
 'alice led way whole party swam shore.',
 'caucus-race long tale indeed queer-looking party assembled bank birds draggled feathers animals fur clinging close dripping wet cross uncomfortable.',
 'first question course get dry consultation minutes seemed quite natural alice find talking familiarly known life.',
 'indeed quite long argument lory last turned sulky would say older must know better alice would allow without knowing old lory positively refused tell age said.',
 'last mouse seemed person authority among called sit listen soon make dry enough sat large ring mouse middle.',
 'alice kept eyes anxiously fixed felt sure would catch bad cold get dry soon.',
 'ahem said mouse important air ready?',
 'driest thing know.',
 'silence round please william conqueror whose cause favoured pope soon submitted english wanted leaders late much accustomed usurpation conquest.',
 'edwin morcar earls mercia northumbria ugh said lory shiver.',
 'beg pardon said mouse frowning politely speak?',
 'said lory hastily.',
 'thought said mouse.',
 'proceed.',
 'edwin morcar earls mercia northumbria declared even stigand patriotic archbishop canterbury found advisable found?',
 'said duck.',
 'found mouse replied rather crossly course know means.',
 'know means well enough find thing said duck generally frog worm.',
 'question archbishop find?',
 'mouse notice question hurriedly went found advisable go edgar atheling meet william offer crown.',
 'william conduct first moderate.',
 'insolence normans getting dear?',
 'continued turning alice spoke.',
 'wet ever said alice melancholy tone seem dry.',
 'case said dodo solemnly rising feet move meeting adjourn immediate adoption energetic remedies speak english said eaglet.',
 'know meaning half long words believe either eaglet bent head hide smile birds tittered audibly.',
 'going say said dodo offended tone best thing get us dry would caucus-race.',
 'caucus-race?',
 'said alice wanted much know dodo paused thought somebody ought speak one else seemed inclined say anything.',
 'said dodo best way explain.',
 'might like try thing winter day tell dodo managed.',
 'first marked race-course sort circle exact shape matter said party placed along course.',
 'one two three away began running liked left liked easy know race.',
 'however running half hour quite dry dodo suddenly called race crowded round panting asking?',
 'question dodo could answer without great deal thought sat long time one finger pressed upon forehead position usually see shakespeare pictures rest waited silence.',
 'last dodo said everybody must prizes.',
 'give prizes?',
 'quite chorus voices asked.',
 'course said dodo pointing alice one finger whole party crowded round calling confused way prizes prizes alice idea despair put hand pocket pulled box comfits luckily salt water got handed round prizes.',
 'exactly one a-piece round.',
 'must prize know said mouse.',
 'course dodo replied gravely.',
 'else got pocket?',
 'went turning alice.',
 'thimble said alice sadly.',
 'hand said dodo.',
 'crowded round dodo solemnly presented thimble saying beg acceptance elegant thimble finished short speech cheered.',
 'alice thought whole thing absurd looked grave dare laugh could think anything say simply bowed took thimble looking solemn could.',
 'next thing eat comfits caused noise confusion large birds complained could taste small ones choked patted back.',
 'however last sat ring begged mouse tell something.',
 'promised tell history know said alice hate c added whisper half afraid would offended.',
 'mine long sad tale said mouse turning alice sighing.',
 'long tail certainly said alice looking wonder mouse tail call sad?',
 'kept puzzling mouse speaking idea tale something like fury said mouse met house let us go law prosecute.',
 'come take denial must trial really morning nothing.',
 'said mouse cur trial dear sir jury judge would wasting breath.',
 'judge jury said cunning old fury try whole cause condemn death.',
 'attending said mouse alice severely.',
 'thinking?',
 'beg pardon said alice humbly got fifth bend think?',
 'cried mouse sharply angrily.',
 'knot said alice always ready make useful looking anxiously.',
 'oh let help undo shall nothing sort said mouse getting walking away.',
 'insult talking nonsense mean pleaded poor alice.',
 'easily offended know mouse growled reply.',
 'please come back finish story alice called others joined chorus yes please mouse shook head impatiently walked little quicker.',
 'pity stay sighed lory soon quite sight old crab took opportunity saying daughter ah dear let lesson never lose temper hold tongue said young crab little snappishly.',
 'enough try patience oyster wish dinah know said alice aloud addressing nobody particular.',
 'soon fetch back dinah might venture ask question?',
 'said lory.',
 'alice replied eagerly always ready talk pet dinah cat.',
 'capital one catching mice think oh wish could see birds eat little bird soon look speech caused remarkable sensation among party.',
 'birds hurried one old magpie began wrapping carefully remarking really must getting home night-air suit throat canary called trembling voice children come away dears high time bed various pretexts moved alice soon left alone.',
 'wish mentioned dinah said melancholy tone.',
 'nobody seems like sure best cat world oh dear dinah wonder shall ever see poor alice began cry felt lonely low-spirited.',
 'little however heard little pattering footsteps distance looked eagerly half hoping mouse changed mind coming back finish story.',
 'rabbit sends little bill white rabbit trotting slowly back looking anxiously went lost something heard muttering duchess duchess oh dear paws oh fur whiskers get executed sure ferrets ferrets dropped wonder?',
 'alice guessed moment looking fan pair white kid gloves good-naturedly began hunting nowhere seen everything seemed changed since swim pool great hall glass table little door vanished completely.',
 'soon rabbit noticed alice went hunting called angry tone mary ann?',
 'run home moment fetch pair gloves fan quick alice much frightened ran direction pointed without trying explain mistake made.',
 'took housemaid said ran.',
 'surprised finds better take fan gloves find.',
 'said came upon neat little house door bright brass plate name w. rabbit engraved upon.',
 'went without knocking hurried upstairs great fear lest meet real mary ann turned house found fan gloves.',
 'queer seems alice said going messages rabbit suppose dinah sending messages next began fancying sort thing would happen miss alice come directly get ready walk coming minute nurse got see mouse get.',
 'think alice went let dinah stop house began ordering people like time found way tidy little room table window hoped fan two three pairs tiny white kid gloves took fan pair gloves going leave room eye fell upon little bottle stood near looking-glass.',
 'label time words drink nevertheless uncorked put lips.',
 'know something interesting sure happen said whenever eat drink anything see bottle.',
 'hope make grow large really quite tired tiny little thing indeed much sooner expected drunk half bottle found head pressing ceiling stoop save neck broken.',
 'hastily put bottle saying quite enough hope grow get door wish drunk quite much alas late wish went growing growing soon kneel floor another minute even room tried effect lying one elbow door arm curled round head.',
 'still went growing last resource put one arm window one foot chimney said whatever happens.',

In [61]:
len(segments)

1158

In [62]:
wordFreq = {}
words = re.findall(r'\b\w+\b|[\.\?\-]', corpus.lower())
for word in words:
    wordFreq[word] = wordFreq.get(word, 0) + 1

print("Word Frequencies:")
for word, freq in wordFreq.items():
    print(f"{word}: {freq}")

Word Frequencies:
rabbit: 51
-: 142
hole: 5
alice: 397
beginning: 14
get: 46
tired: 7
sitting: 10
sister: 9
bank: 3
nothing: 34
twice: 5
peeped: 3
book: 11
reading: 3
pictures: 4
conversations: 2
use: 18
thought: 74
without: 26
?: 203
considering: 3
mind: 11
well: 63
could: 77
hot: 7
day: 29
made: 30
feel: 8
sleepy: 5
stupid: 6
whether: 11
pleasure: 2
making: 8
daisy: 1
chain: 1
would: 83
worth: 4
trouble: 6
getting: 22
picking: 2
daisies: 1
suddenly: 13
white: 30
pink: 1
eyes: 29
ran: 16
close: 13
.: 979
remarkable: 2
think: 53
much: 51
way: 56
hear: 14
say: 51
oh: 45
dear: 29
shall: 25
late: 6
afterwards: 2
occurred: 2
ought: 14
wondered: 1
time: 71
seemed: 27
quite: 55
natural: 4
actually: 1
took: 24
watch: 8
waistcoat: 2
pocket: 7
looked: 45
hurried: 11
started: 2
feet: 19
flashed: 1
across: 5
never: 48
seen: 15
either: 10
take: 22
burning: 1
curiosity: 5
field: 1
fortunately: 1
see: 67
pop: 1
large: 33
hedge: 2
another: 22
moment: 31
went: 83
world: 7
straight: 2
like: 85
tunnel: 1
dipped: 2
stopping: 1
found: 32
falling: 2
deep: 7
fell: 6
slowly: 8
plenty: 2
look: 29
wonder: 18
going: 27
happen: 8
next: 30
first: 51
tried: 19
make: 27
coming: 9
dark: 3
anything: 20
sides: 4
noticed: 8
filled: 3
cupboards: 2
shelves: 2
saw: 14
maps: 1
hung: 1
upon: 26
pegs: 1
jar: 2
one: 104
passed: 5
labelled: 1
orange: 1
marmalade: 1
great: 39
disappointment: 1
empty: 1
drop: 1
fear: 4
killing: 1
somebody: 7
underneath: 2
managed: 4
put: 31
past: 3
fall: 7
tumbling: 2
stairs: 3
brave: 1
home: 5
even: 18
top: 8
house: 18
likely: 5
true: 4
come: 46
end: 18
many: 12
miles: 3
fallen: 4
said: 462
aloud: 5
must: 44
somewhere: 3
near: 15
centre: 1
earth: 4
let: 22
four: 8
thousand: 2
learnt: 2
several: 4
things: 31
sort: 20
lessons: 10
schoolroom: 1
though: 11
good: 27
opportunity: 8
showing: 2
knowledge: 3
listen: 7
still: 13
practice: 1
yes: 13
right: 32
distance: 8
latitude: 2
longitude: 2
got: 45
idea: 15
nice: 6
grand: 3
words: 21
presently: 2
began: 58
funny: 3
seem: 8
among: 12
people: 13
walk: 5
heads: 10
downward: 1
antipathies: 1
rather: 25
glad: 11
listening: 3
sound: 4
word: 10
ask: 11
name: 10
country: 1
know: 87
please: 19
new: 5
zealand: 1
australia: 1
curtsey: 1
spoke: 17
fancy: 7
curtseying: 1
air: 15
manage: 7
ignorant: 1
little: 128
girl: 4
asking: 5
perhaps: 17
written: 6
else: 12
soon: 25
talking: 17
dinah: 14
miss: 4
to: 4
night: 5
cat: 37
hope: 3
remember: 14
saucer: 1
milk: 2
tea: 19
wish: 21
mice: 4
afraid: 12
might: 28
catch: 4
bat: 3
mouse: 44
cats: 13
eat: 18
bats: 4
saying: 15
dreamy: 1
sometimes: 5
answer: 9
question: 17
matter: 9
felt: 23
dozing: 1
begun: 7
dream: 7
walking: 5
hand: 21
earnestly: 2
tell: 32
truth: 1
ever: 22
thump: 2
came: 40
heap: 1
sticks: 1
dry: 8
leaves: 6
bit: 16
hurt: 3
jumped: 6
overhead: 1
long: 32
passage: 4
sight: 10
hurrying: 1
lost: 3
away: 25
wind: 2
turned: 16
corner: 4
ears: 5
whiskers: 3
behind: 13
longer: 3
low: 15
hall: 9
lit: 1
row: 2
lamps: 1
hanging: 3
roof: 6
doors: 2
round: 41
locked: 1
side: 17
trying: 14
every: 12
door: 30
walked: 10
sadly: 5
middle: 7
wondering: 7
three: 28
legged: 2
table: 18
solid: 1
glass: 10
except: 4
tiny: 4
golden: 7
key: 9
belong: 1
alas: 4
locks: 2
small: 10
rate: 9
open: 7
however: 20
second: 4
curtain: 1
fifteen: 1
inches: 6
high: 16
lock: 1
delight: 3
fitted: 1
opened: 10
led: 4
larger: 7
rat: 1
knelt: 1
along: 6
loveliest: 1
garden: 16
longed: 2
wander: 1
beds: 2
bright: 8
flowers: 2
cool: 2
fountains: 2
head: 50
doorway: 1
go: 50
poor: 27
shoulders: 4
shut: 5
telescope: 3
knew: 15
begin: 13
out: 4
of: 3
the: 5
happened: 7
lately: 1
indeed: 16
really: 13
impossible: 3
waiting: 9
back: 39
half: 23
hoping: 3
find: 21
rules: 3
shutting: 2
telescopes: 1
bottle: 10
certainly: 14
neck: 7
paper: 4
label: 2
drink: 7
beautifully: 2
printed: 1
letters: 1
wise: 2
hurry: 11
marked: 6
poison: 3
read: 11
histories: 1
children: 10
burnt: 1
eaten: 1
wild: 2
beasts: 2
unpleasant: 2
simple: 5
friends: 2
taught: 4
red: 3
poker: 1
burn: 2
hold: 10
cut: 5
finger: 5
deeply: 4
knife: 3
usually: 2
bleeds: 1
forgotten: 6
almost: 6
certain: 3
disagree: 1
sooner: 2
later: 3
ventured: 4
taste: 2
finding: 3
fact: 8
mixed: 2
flavour: 1
cherry: 1
tart: 1
custard: 1
pine: 1
apple: 1
roast: 1
turkey: 1
toffee: 1
buttered: 1
toast: 1
finished: 12
curious: 19
feeling: 7
ten: 6
face: 15
brightened: 2
size: 13
lovely: 2
waited: 11
minutes: 11
shrink: 1
nervous: 5
altogether: 5
candle: 3
flame: 1
blown: 1
thing: 49
decided: 3
possibly: 3
reach: 4
plainly: 1
best: 12
climb: 1
legs: 3
slippery: 1
sat: 17
cried: 20
crying: 2
sharply: 4
advise: 1
leave: 9
minute: 21
generally: 7
gave: 15
advice: 2
seldom: 1
followed: 8
scolded: 1
severely: 4
bring: 3
tears: 11
remembered: 5
box: 10
cheated: 1
game: 13
croquet: 9
playing: 2
child: 11
fond: 4
pretending: 1
two: 40
pretend: 1
hardly: 12
enough: 18
left: 14
respectable: 1
person: 4
eye: 7
lying: 8
cake: 3
currants: 1
makes: 11
grow: 13
smaller: 3
creep: 1
care: 4
happens: 5
ate: 1
anxiously: 14
holding: 3
growing: 11
surprised: 7
remained: 3
sure: 24
eats: 1
expecting: 3
dull: 3
life: 12
common: 1
set: 14
work: 8
pool: 11
curiouser: 2
forgot: 2
speak: 15
english: 6
opening: 3
largest: 1
bye: 2
far: 13
shoes: 7
stockings: 1
dears: 3
able: 1
deal: 12
kind: 7
want: 9
give: 12
pair: 5
boots: 4
christmas: 1
planning: 1
carrier: 1
sending: 2
presents: 2
odd: 1
directions: 3
foot: 10
esq: 1
hearthrug: 1
fender: 1
love: 3
nonsense: 7
struck: 2
nine: 5
hopeless: 1
cry: 3
ashamed: 2
stop: 6
shedding: 1
gallons: 1
reaching: 1
heard: 30
pattering: 3
hastily: 16
dried: 1
returning: 1
splendidly: 1
dressed: 1
kid: 5
gloves: 11
fan: 10
trotting: 2
muttering: 3
duchess: 42
savage: 4
kept: 13
desperate: 1
ready: 8
help: 9
timid: 3
voice: 48
sir: 7
violently: 4
dropped: 5
skurried: 1
darkness: 1
hard: 8
fanning: 1
queer: 12
everything: 14
yesterday: 3
usual: 5
changed: 8
morning: 5
different: 9
ah: 5
puzzle: 1
thinking: 11
age: 4
ada: 1
hair: 7
goes: 7
ringlets: 2
mine: 10
mabel: 4
sorts: 3
knows: 2
besides: 4
puzzling: 4
try: 12
used: 13
times: 6
five: 8
twelve: 4
six: 2
thirteen: 1
seven: 6
twenty: 3
multiplication: 1
signify: 1
geography: 1
london: 1
capital: 4
paris: 2
rome: 2
wrong: 5
doth: 3
crossed: 3
hands: 12
lap: 2
repeat: 7
sounded: 5
hoarse: 3
strange: 5
crocodile: 1
improve: 1
shining: 1
tail: 9
pour: 1
waters: 1
nile: 1
scale: 1
cheerfully: 1
seems: 5
grin: 6
neatly: 2
spread: 3
claws: 2
welcome: 1
fishes: 1
gently: 3
smiling: 2
jaws: 2
live: 8
poky: 1
toys: 1
play: 8
learn: 7
stay: 5
putting: 3
till: 21
sudden: 5
burst: 1
alone: 4
done: 15
measure: 1
nearly: 11
guess: 3
shrinking: 4
rapidly: 2
cause: 3
avoid: 1
narrow: 2
escape: 4
frightened: 7
change: 14
existence: 1
speed: 1
worse: 3
declare: 2
bad: 2
slipped: 3
splash: 1
chin: 7
salt: 2
water: 5
somehow: 1
sea: 14
case: 5
railway: 2
seaside: 1
general: 3
conclusion: 2
wherever: 2
coast: 1
number: 5
bathing: 1
machines: 1
digging: 4
sand: 1
wooden: 1
spades: 1
lodging: 1
houses: 1
station: 1
wept: 1
swam: 5
punished: 1
suppose: 14
drowned: 1
something: 18
splashing: 2
nearer: 5
walrus: 1
hippopotamus: 1
talk: 14
harm: 1
swimming: 2
speaking: 5
brother: 1
latin: 1
grammar: 1
inquisitively: 1
wink: 2
understand: 6
daresay: 1
french: 4
william: 8
conqueror: 2
history: 7
clear: 2
notion: 3
ago: 2
où: 1
est: 1
chatte: 1
sentence: 6
lesson: 3
leap: 1
quiver: 1
fright: 2
beg: 8
pardon: 6
animal: 2
feelings: 2
shrill: 5
passionate: 1
soothing: 1
tone: 40
angry: 5
yet: 25
show: 3
quiet: 2
lazily: 1
sits: 1
purring: 2
nicely: 2
fire: 4
licking: 1
paws: 4
washing: 3
soft: 1
nurse: 3
catching: 2
bristling: 1
offended: 10
trembling: 6
subject: 6
family: 1
always: 13
hated: 1
nasty: 1
vulgar: 1
conversation: 9
dogs: 3
eagerly: 8
dog: 3
eyed: 1
terrier: 1
curly: 1
brown: 2
fetch: 7
throw: 3
sit: 8
dinner: 2
belongs: 2
farmer: 1
says: 4
useful: 2
hundred: 1
pounds: 1
kills: 1
rats: 1
sorrowful: 2
commotion: 1
called: 15
softly: 1
pale: 4
passion: 3
us: 14
shore: 4
hate: 2
crowded: 5
birds: 10
animals: 4
duck: 4
dodo: 13
lory: 7
eaglet: 3
creatures: 10
whole: 13
party: 10
caucus: 3
race: 6
tale: 4
looking: 32
assembled: 2
draggled: 1
feathers: 1
fur: 3
clinging: 1
dripping: 1
wet: 2
cross: 3
uncomfortable: 4
course: 26
consultation: 1
familiarly: 1
known: 1
argument: 4
last: 33
sulky: 3
older: 2
better: 14
allow: 3
knowing: 2
old: 19
positively: 1
refused: 1
authority: 2
ring: 2
fixed: 1
cold: 1
ahem: 1
important: 7
driest: 1
silence: 14
whose: 2
favoured: 1
pope: 1
submitted: 1
wanted: 4
leaders: 1
accustomed: 1
usurpation: 1
conquest: 1
edwin: 2
morcar: 2
earls: 2
mercia: 2
northumbria: 2
ugh: 2
shiver: 1
frowning: 4
politely: 6
proceed: 2
declared: 1
stigand: 1
patriotic: 1
archbishop: 2
canterbury: 1
advisable: 2
replied: 29
crossly: 1
means: 5
frog: 3
worm: 1
notice: 5
hurriedly: 2
edgar: 1
atheling: 1
meet: 2
offer: 2
crown: 3
conduct: 1
moderate: 1
insolence: 1
normans: 1
continued: 9
turning: 12
melancholy: 6
solemnly: 4
rising: 1
move: 3
meeting: 1
adjourn: 1
immediate: 1
adoption: 1
energetic: 1
remedies: 1
meaning: 8
believe: 9
bent: 1
hide: 1
smile: 2
tittered: 1
audibly: 1
paused: 1
inclined: 1
explain: 10
winter: 1
circle: 1
exact: 1
shape: 1
placed: 1
running: 8
liked: 6
easy: 2
hour: 2
panting: 2
pressed: 3
forehead: 2
position: 2
shakespeare: 1
rest: 10
everybody: 8
prizes: 5
chorus: 6
voices: 3
asked: 17
pointing: 4
calling: 1
confused: 4
despair: 1
pulled: 1
comfits: 2
luckily: 2
handed: 3
exactly: 8
a: 1
piece: 6
prize: 1
gravely: 3
thimble: 4
presented: 1
acceptance: 1
elegant: 1
short: 4
speech: 3
cheered: 3
absurd: 2
grave: 3
dare: 5
laugh: 1
simply: 3
bowed: 4
solemn: 3
caused: 2
noise: 3
confusion: 5
complained: 1
ones: 1
choked: 3
patted: 1
begged: 1
promised: 1
c: 1
added: 23
whisper: 3
sad: 3
sighing: 3
call: 9
fury: 3
met: 3
law: 2
prosecute: 1
denial: 1
trial: 10
cur: 1
jury: 22
judge: 4
wasting: 2
breath: 4
cunning: 1
condemn: 1
death: 1
attending: 3
humbly: 2
fifth: 1
bend: 2
angrily: 9
knot: 2
undo: 1
insult: 1
mean: 10
pleaded: 3
easily: 3
growled: 1
reply: 5
finish: 5
story: 8
others: 7
joined: 3
shook: 9
impatiently: 5
quicker: 1
pity: 3
sighed: 5
crab: 3
daughter: 1
lose: 1
temper: 5
tongue: 4
young: 5
snappishly: 1
patience: 1
oyster: 1
addressing: 1
nobody: 8
particular: 4
venture: 3
pet: 1
bird: 2
sensation: 2
magpie: 1
wrapping: 1
carefully: 3
remarking: 3
suit: 3
throat: 2
canary: 1
bed: 1
various: 1
pretexts: 1
moved: 5
mentioned: 3
lonely: 2
spirited: 1
footsteps: 2
sends: 1
bill: 17
executed: 6
ferrets: 2
guessed: 3
naturedly: 1
hunting: 3
nowhere: 2
since: 4
swim: 5
vanished: 4
completely: 1
mary: 4
ann: 4
run: 4
quick: 2
direction: 5
pointed: 1
mistake: 3
housemaid: 1
finds: 1
neat: 1
brass: 1
plate: 3
w: 1
engraved: 1
knocking: 3
upstairs: 1
lest: 1
real: 3
messages: 2
fancying: 1
directly: 2
ordering: 2
tidy: 1
room: 13
window: 8
hoped: 1
pairs: 1
stood: 7
nevertheless: 1
uncorked: 1
lips: 1
interesting: 5
whenever: 1
expected: 1
drunk: 2
pressing: 1
ceiling: 1
stoop: 2
save: 1
broken: 6
kneel: 1
floor: 3
effect: 3
elbow: 3
arm: 15
curled: 2
resource: 1
chimney: 6
whatever: 3
become: 5
magic: 1
full: 6
grew: 1
chance: 4
unhappy: 2
pleasanter: 1
ordered: 4
rabbits: 1
gone: 13
fairy: 1
tales: 1
fancied: 2
write: 6
grown: 7
least: 9
comfort: 1
woman: 2
foolish: 1
answered: 4
books: 2
taking: 5
outside: 4
stopped: 3
trembled: 2
forgetting: 3
reason: 9
inwards: 1
attempt: 1
proved: 2
failure: 1
snatch: 2
shriek: 5
crash: 3
concluded: 2
possible: 1
cucumber: 2
frame: 1
pat: 3
apples: 2
yer: 4
honour: 4
sounds: 4
pronounced: 1
arrum: 1
goose: 2
fills: 1
business: 7
whispers: 1
coward: 1
shrieks: 1
frames: 1
pulling: 1
hearing: 4
rumbling: 1
cartwheels: 1
together: 9
ladder: 1
lad: 1
em: 3
tie: 1
rope: 1
bear: 2
loose: 1
slate: 4
loud: 6
nay: 1
master: 4
shy: 1
place: 8
fireplace: 1
kick: 3
drew: 5
scratching: 1
scrambling: 1
sharp: 6
brandy: 1
choke: 1
fellow: 4
feeble: 2
squeaking: 2
thank: 4
ye: 1
flustered: 1
comes: 2
jack: 1
in: 2
sky: 5
rocket: 1
dead: 4
instantly: 5
sense: 3
moving: 3
barrowful: 2
doubt: 4
shower: 2
pebbles: 2
rattling: 2
hit: 2
shouted: 9
produced: 1
surprise: 5
cakes: 3
lay: 4
swallowed: 1
delighted: 2
crowd: 4
lizard: 6
held: 4
guinea: 6
pigs: 6
giving: 2
rush: 2
appeared: 8
safe: 2
thick: 1
wood: 8
wandered: 2
plan: 4
excellent: 2
arranged: 1
difficulty: 4
smallest: 2
peering: 1
trees: 7
bark: 2
enormous: 1
puppy: 7
feebly: 1
stretching: 2
paw: 3
touch: 1
coaxing: 2
whistle: 1
terribly: 1
hungry: 3
spite: 1
picked: 3
stick: 4
whereupon: 1
yelp: 1
rushed: 1
worry: 1
dodged: 1
thistle: 2
keep: 11
tumbled: 1
heels: 1
cart: 1
horse: 1
trampled: 1
series: 1
charges: 1
forwards: 1
barking: 1
hoarsely: 1
mouth: 10
faint: 1
leant: 1
buttercup: 1
fanned: 1
teaching: 1
tricks: 1
blades: 1
grass: 4
circumstances: 1
mushroom: 8
height: 5
stretched: 2
tiptoe: 2
edge: 3
immediately: 3
caterpillar: 28
arms: 6
folded: 3
quietly: 5
smoking: 2
hookah: 5
addressed: 2
languid: 1
encouraging: 2
shyly: 1
present: 3
sternly: 1
clearly: 1
sizes: 1
confusing: 3
turn: 11
chrysalis: 1
butterfly: 1
may: 13
contemptuously: 2
brought: 3
irritated: 1
remarks: 3
state: 1
promising: 1
swallowing: 1
anger: 2
wait: 1
puffed: 1
unfolded: 2
busy: 2
bee: 1
father: 6
man: 5
incessantly: 1
stand: 6
youth: 6
son: 1
feared: 1
injure: 1
brain: 1
perfectly: 4
none: 4
uncommonly: 1
fat: 1
somersault: 2
pray: 3
sage: 1
grey: 1
limbs: 1
supple: 1
ointment: 1
shilling: 1
sell: 2
couple: 1
weak: 2
tougher: 1
suet: 1
bones: 1
beak: 1
argued: 1
wife: 1
muscular: 1
strength: 1
jaw: 1
lasted: 2
steady: 1
balanced: 1
eel: 2
nose: 8
awfully: 1
clever: 2
questions: 4
airs: 1
stuff: 4
timidly: 9
altered: 1
decidedly: 4
changing: 2
often: 5
contradicted: 1
losing: 1
content: 1
wretched: 2
rearing: 1
upright: 1
piteous: 1
patiently: 2
chose: 2
yawned: 2
crawled: 1
merely: 2
taller: 2
shorter: 2
thoughtfully: 4
difficult: 2
broke: 2
nibbled: 2
violent: 2
blow: 2
closely: 1
swallow: 1
morsel: 1
lefthand: 2
free: 3
alarm: 2
immense: 1
length: 1
rise: 1
stalk: 1
green: 4
result: 1
follow: 2
shaking: 3
distant: 2
serpent: 9
succeeded: 3
curving: 1
graceful: 1
zigzag: 1
dive: 1
tops: 1
wandering: 2
hiss: 1
draw: 7
pigeon: 12
flown: 1
beating: 2
wings: 1
screamed: 4
indignantly: 4
repeated: 10
subdued: 1
sob: 1
roots: 2
banks: 1
hedges: 1
serpents: 3
pleasing: 1
puzzled: 9
hatching: 1
eggs: 5
sleep: 6
weeks: 1
sorry: 1
annoyed: 1
taken: 4
highest: 1
tree: 9
raising: 1
needs: 1
wriggling: 1
invent: 1
doubtfully: 2
changes: 2
deepest: 1
contempt: 1
girls: 3
denying: 1
telling: 2
tasted: 3
egg: 1
truthful: 1
silent: 7
adding: 1
matters: 2
raw: 1
settled: 3
nest: 1
crouched: 1
entangled: 2
branches: 2
untwist: 1
pieces: 3
nibbling: 3
bringing: 3
beautiful: 13
whoever: 1
lives: 4
frighten: 1
wits: 1
righthand: 1
pig: 11
pepper: 8
footman: 14
livery: 3
considered: 3
otherwise: 4
judging: 1
fish: 8
rapped: 1
loudly: 3
knuckles: 1
footmen: 1
powdered: 1
crept: 1
producing: 1
letter: 3
invitation: 2
queen: 75
order: 3
curls: 1
laughed: 2
ground: 8
staring: 3
stupidly: 1
knocked: 1
reasons: 1
secondly: 2
inside: 2
extraordinary: 2
within: 2
constant: 2
howling: 3
sneezing: 6
dish: 4
kettle: 1
instance: 3
knock: 1
uncivil: 1
remarked: 10
tomorrow: 1
skimming: 1
grazed: 1
maybe: 2
louder: 1
told: 6
dreadful: 2
muttered: 2
argue: 1
drive: 2
crazy: 1
repeating: 3
remark: 10
variations: 1
days: 4
whistling: 1
desperately: 1
idiotic: 1
kitchen: 4
smoke: 1
stool: 1
nursing: 3
baby: 14
cook: 13
leaning: 2
stirring: 2
cauldron: 2
soup: 18
sneezed: 1
occasionally: 1
alternately: 1
pause: 2
sneeze: 2
hearth: 1
grinning: 1
ear: 6
manners: 1
grins: 1
cheshire: 7
violence: 1
courage: 3
grinned: 3
pleased: 7
introduce: 2
fix: 1
throwing: 2
irons: 1
saucepans: 1
plates: 2
dishes: 2
already: 2
blows: 1
jumping: 4
agony: 1
terror: 1
precious: 1
unusually: 1
saucepan: 1
flew: 1
carried: 4
minded: 1
growl: 3
faster: 3
advantage: 3
takes: 2
hours: 4
axis: 1
axes: 1
chop: 1
glanced: 1
meant: 5
hint: 2
busily: 4
bother: 1
abide: 1
figures: 1
singing: 2
lullaby: 1
shake: 1
line: 2
roughly: 1
boy: 3
beat: 4
sneezes: 2
annoy: 1
teases: 1
wow: 6
sang: 2
verse: 4
song: 7
tossing: 3
howled: 1
thoroughly: 2
enjoy: 1
pleases: 1
flinging: 1
threw: 2
frying: 1
pan: 1
missed: 2
caught: 3
shaped: 3
creature: 4
star: 1
snorting: 1
steam: 1
engine: 1
doubling: 1
straightening: 1
proper: 3
twist: 2
tight: 1
prevent: 1
undoing: 1
kill: 1
murder: 1
grunted: 4
grunt: 1
expressing: 1
up: 2
snout: 1
also: 2
extremely: 2
sobbing: 3
seriously: 1
sobbed: 1
neither: 2
less: 4
carry: 1
relieved: 1
trot: 1
dreadfully: 6
ugly: 2
handsome: 1
startled: 2
seeing: 1
bough: 1
yards: 1
natured: 1
teeth: 1
treated: 1
respect: 1
puss: 1
wider: 1
depends: 1
explanation: 2
denied: 2
waving: 5
hatter: 56
march: 34
hare: 31
visit: 1
mad: 15
grant: 1
growls: 1
wags: 1
wag: 1
therefore: 1
growling: 1
invited: 2
happening: 1
by: 1
became: 2
appear: 2
hatters: 1
raving: 2
branch: 1
fig: 1
appearing: 1
vanishing: 1
giddy: 2
ending: 2
farther: 1
chimneys: 1
thatched: 1
raised: 2
towards: 1
instead: 3
chapter: 4
vii: 1
front: 2
dormouse: 40
fast: 4
asleep: 8
using: 2
cushion: 2
resting: 2
elbows: 1
chair: 1
wine: 2
civil: 3
laid: 2
wants: 2
cutting: 1
personal: 2
severity: 1
rude: 2
wide: 2
raven: 1
writing: 6
desk: 1
fun: 3
riddles: 2
breathe: 3
ravens: 1
desks: 1
break: 2
month: 2
uneasily: 2
fourth: 1
butter: 9
works: 1
meekly: 2
crumbs: 4
grumbled: 1
bread: 7
gloomily: 1
cup: 2
shoulder: 4
tells: 2
clock: 5
year: 2
readily: 1
stays: 1
poured: 1
riddle: 1
slightest: 1
wearily: 1
waste: 1
answers: 1
cautiously: 3
music: 3
accounts: 1
terms: 1
twinkling: 4
mournfully: 1
quarrelled: 1
spoon: 2
concert: 2
given: 1
hearts: 8
sing: 6
twinkle: 8
fly: 3
tray: 1
pinch: 2
bawled: 1
murdering: 1
exclaimed: 6
mournful: 1
sigh: 4
wash: 2
whiles: 1
interrupted: 9
yawning: 2
vote: 1
lady: 3
alarmed: 1
proposal: 1
wake: 2
pinched: 2
fellows: 1
sisters: 2
names: 2
elsie: 1
lacie: 1
tillie: 1
lived: 3
bottom: 4
interest: 1
eating: 1
drinking: 1
treacle: 7
ill: 2
ways: 1
living: 2
opinion: 1
triumphantly: 2
helped: 1
and: 6
sh: 2
sulkily: 2
interrupt: 1
consented: 1
learning: 2
promise: 1
clean: 1
unwillingly: 1
upset: 3
jug: 1
offend: 1
eh: 1
choosing: 1
interrupting: 2
rubbing: 2
manner: 2
begins: 4
closed: 2
doze: 1
woke: 1
traps: 1
moon: 1
memory: 1
muchness: 3
drawing: 1
rudeness: 1
disgust: 1
teapot: 1
stupidest: 1
leading: 1
today: 1
unlocking: 1
flower: 2
rose: 5
entrance: 1
roses: 3
gardeners: 8
painting: 2
paint: 1
jogged: 1
blame: 1
deserved: 1
beheaded: 3
spoken: 1
tulip: 1
onions: 1
flung: 1
brush: 1
unjust: 1
chanced: 1
watching: 3
checked: 3
afore: 1
flat: 2
faces: 5
eager: 3
soldiers: 10
carrying: 2
clubs: 1
oblong: 1
corners: 1
courtiers: 2
ornamented: 2
diamonds: 1
royal: 2
merrily: 1
couples: 1
guests: 3
mostly: 2
kings: 1
queens: 1
recognised: 1
noticing: 1
knave: 9
king: 63
crimson: 2
velvet: 1
procession: 5
doubtful: 2
lie: 2
rule: 5
processions: 1
opposite: 1
smiled: 2
idiot: 1
majesty: 12
pack: 5
cards: 3
pattern: 1
backs: 1
glaring: 1
beast: 1
consider: 4
bowing: 1
humble: 1
knee: 5
meanwhile: 1
examining: 1
remaining: 1
execute: 1
unfortunate: 3
protection: 1
pot: 1
marched: 1
evidently: 1
roared: 1
fine: 2
peeping: 1
hush: 3
whispered: 5
execution: 3
boxed: 1
scream: 2
laughter: 1
places: 2
thunder: 1
ridges: 1
furrows: 1
balls: 1
hedgehogs: 3
mallets: 1
flamingoes: 2
double: 1
arches: 4
chief: 1
managing: 1
flamingo: 5
body: 2
tucked: 3
comfortably: 1
straightened: 1
hedgehog: 7
expression: 1
bursting: 1
laughing: 2
provoking: 1
unrolled: 2
act: 1
crawling: 1
ridge: 1
furrow: 1
send: 1
doubled: 1
parts: 1
players: 4
played: 1
turns: 3
quarrelling: 2
fighting: 1
furious: 1
stamping: 2
shouting: 2
uneasy: 1
dispute: 2
beheading: 1
alive: 3
appearance: 1
nodded: 1
account: 1
someone: 1
fairly: 1
complaining: 1
quarrel: 1
oneself: 1
attends: 1
arch: 1
croqueted: 1
win: 1
finishing: 1
friend: 3
kiss: 1
likes: 1
impertinent: 1
removed: 2
passing: 1
settling: 1
difficulties: 1
executioner: 6
screaming: 1
search: 1
engaged: 1
fight: 2
croqueting: 1
helpless: 1

In [63]:
freq = pd.DataFrame(list(wordFreq.items()), columns=['Word', 'Frequency'])
freq

             Word  Frequency
0          rabbit         51
1               -        142
2            hole          5
3           alice        397
4       beginning         14
...           ...        ...
2422       gather          1
2423      sorrows          1
2424         joys          1
2425  remembering          1
2426        happy          1

[2427 rows x 2 columns]

In [64]:
bigram = []
for segment in segments:
  words = ['<s>'] + word_tokenize(segment) + ['</s>']
  bigram.append(list(ngrams(words,2)))

In [65]:
bigram

[[('<s>', 'rabbit-hole'),
  ('rabbit-hole', 'alice'),
  ('alice', 'beginning'),
  ('beginning', 'get'),
  ('get', 'tired'),
  ('tired', 'sitting'),
  ('sitting', 'sister'),
  ('sister', 'bank'),
  ('bank', 'nothing'),
  ('nothing', 'twice'),
  ('twice', 'peeped'),
  ('peeped', 'book'),
  ('book', 'sister'),
  ('sister', 'reading'),
  ('reading', 'pictures'),
  ('pictures', 'conversations'),
  ('conversations', 'use'),
  ('use', 'book'),
  ('book', 'thought'),
  ('thought', 'alice'),
  ('alice', 'without'),
  ('without', 'pictures'),
  ('pictures', 'conversations'),
  ('conversations', '?'),
  ('?', '</s>')],
 [('<s>', 'considering'),
  ('considering', 'mind'),
  ('mind', 'well'),
  ('well', 'could'),
  ('could', 'hot'),
  ('hot', 'day'),
  ('day', 'made'),
  ('made', 'feel'),
  ('feel', 'sleepy'),
  ('sleepy', 'stupid'),
  ('stupid', 'whether'),
  ('whether', 'pleasure'),
  ('pleasure', 'making'),
  ('making', 'daisy-chain'),
  ('daisy-chain', 'would'),
  ('would', 'worth'),
  ('worth', 'trouble'),
  ('trouble', 'getting'),
  ('getting', 'picking'),
  ('picking', 'daisies'),
  ('daisies', 'suddenly'),
  ('suddenly', 'white'),
  ('white', 'rabbit'),
  ('rabbit', 'pink'),
  ('pink', 'eyes'),
  ('eyes', 'ran'),
  ('ran', 'close'),
  ('close', '.'),
  ('.', '</s>')],
 [('<s>', 'nothing'),
  ('nothing', 'remarkable'),
  ('remarkable', 'alice'),
  ('alice', 'think'),
  ('think', 'much'),
  ('much', 'way'),
  ('way', 'hear'),
  ('hear', 'rabbit'),
  ('rabbit', 'say'),
  ('say', 'oh'),
  ('oh', 'dear'),
  ('dear', 'oh'),
  ('oh', 'dear'),
  ('dear', 'shall'),
  ('shall', 'late'),
  ('late', 'thought'),
  ('thought', 'afterwards'),
  ('afterwards', 'occurred'),
  ('occurred', 'ought'),
  ('ought', 'wondered'),
  ('wondered', 'time'),
  ('time', 'seemed'),
  ('seemed', 'quite'),
  ('quite', 'natural'),
  ('natural', 'rabbit'),
  ('rabbit', 'actually'),
  ('actually', 'took'),
  ('took', 'watch'),
  ('watch', 'waistcoat-pocket'),
  ('waistcoat-pocket', 'looked'),
  ('looked', 'hurried'),
  ('hurried', 'alice'),
  ('alice', 'started'),
  ('started', 'feet'),
  ('feet', 'flashed'),
  ('flashed', 'across'),
  ('across', 'mind'),
  ('mind', 'never'),
  ('never', 'seen'),
  ('seen', 'rabbit'),
  ('rabbit', 'either'),
  ('either', 'waistcoat-pocket'),
  ('waistcoat-pocket', 'watch'),
  ('watch', 'take'),
  ('take', 'burning'),
  ('burning', 'curiosity'),
  ('curiosity', 'ran'),
  ('ran', 'across'),
  ('across', 'field'),
  ('field', 'fortunately'),
  ('fortunately', 'time'),
  ('time', 'see'),
  ('see', 'pop'),
  ('pop', 'large'),
  ('large', 'rabbit-hole'),
  ('rabbit-hole', 'hedge'),
  ('hedge', '.'),
  ('.', '</s>')],
 [('<s>', 'another'),
  ('another', 'moment'),
  ('moment', 'went'),
  ('went', 'alice'),
  ('alice', 'never'),
  ('never', 'considering'),
  ('considering', 'world'),
  ('world', 'get'),
  ('get', '.'),
  ('.', '</s>')],
 [('<s>', 'rabbit-hole'),
  ('rabbit-hole', 'went'),
  ('went', 'straight'),
  ('straight', 'like'),
  ('like', 'tunnel'),
  ('tunnel', 'way'),
  ('way', 'dipped'),
  ('dipped', 'suddenly'),
  ('suddenly', 'suddenly'),
  ('suddenly', 'alice'),
  ('alice', 'moment'),
  ('moment', 'think'),
  ('think', 'stopping'),
  ('stopping', 'found'),
  ('found', 'falling'),
  ('falling', 'deep'),
  ('deep', 'well'),
  ('well', '.'),
  ('.', '</s>')],
 [('<s>', 'either'),
  ('either', 'well'),
  ('well', 'deep'),
  ('deep', 'fell'),
  ('fell', 'slowly'),
  ('slowly', 'plenty'),
  ('plenty', 'time'),
  ('time', 'went'),
  ('went', 'look'),
  ('look', 'wonder'),
  ('wonder', 'going'),
  ('going', 'happen'),
  ('happen', 'next'),
  ('next', '.'),
  ('.', '</s>')],
 [('<s>', 'first'),
  ('first', 'tried'),
  ('tried', 'look'),
  ('look', 'make'),
  ('make', 'coming'),
  ('coming', 'dark'),
  ('dark', 'see'),
  ('see', 'anything'),
  ('anything', 'looked'),
  ('looked', 'sides'),
  ('sides', 'well'),
  ('well', 'noticed'),
  ('noticed', 'filled'),
  ('filled', 'cupboards'),
  ('cupboards', 'book-shelves'),
  ('book-shelves', 'saw'),
  ('saw', 'maps'),
  ('maps', 'pictures'),
  ('pictures', 'hung'),
  ('hung', 'upon'),
  ('upon', 'pegs'),
  ('pegs', '.'),
  ('.', '</s>')],
 [('<s>', 'took'),
  ('took', 'jar'),
  ('jar', 'one'),
  ('one', 'shelves'),
  ('shelves', 'passed'),
  ('passed', 'labelled'),
  ('labelled', 'orange'),
  ('orange', 'marmalade'),
  ('marmalade', 'great'),
  ('great', 'disappointment'),
  ('disappointment', 'empty'),
  ('empty', 'like'),
  ('like', 'drop'),
  ('drop', 'jar'),
  ('jar', 'fear'),
  ('fear', 'killing'),
  ('killing', 'somebody'),
  ('somebody', 'underneath'),
  ('underneath', 'managed'),
  ('managed', 'put'),
  ('put', 'one'),
  ('one', 'cupboards'),
  ('cupboards', 'fell'),
  ('fell', 'past'),
  ('past', '.'),
  ('.', '</s>')],
 [('<s>', 'well'),
  ('well', 'thought'),
  ('thought', 'alice'),
  ('alice', 'fall'),
  ('fall', 'shall'),
  ('shall', 'think'),
  ('think', 'nothing'),
  ('nothing', 'tumbling'),
  ('tumbling', 'stairs'),
  ('stairs', 'brave'),
  ('brave', 'think'),
  ('think', 'home'),
  ('home', 'say'),
  ('say', 'anything'),
  ('anything', 'even'),
  ('even', 'fell'),
  ('fell', 'top'),
  ('top', 'house'),
  ('house', 'likely'),
  ('likely', 'true'),
  ('true', '..'),
  ('..', 'would'),
  ('would', 'fall'),
  ('fall', 'never'),
  ('never', 'come'),
  ('come', 'end'),
  ('end', '?'),
  ('?', '</s>')],
 [('<s>', 'wonder'),
  ('wonder', 'many'),
  ('many', 'miles'),
  ('miles', 'fallen'),
  ('fallen', 'time'),
  ('time', '?'),
  ('?', '</s>')],
 [('<s>', 'said'), ('said', 'aloud'), ('aloud', '.'), ('.', '</s>')],
 [('<s>', 'must'),
  ('must', 'getting'),
  ('getting', 'somewhere'),
  ('somewhere', 'near'),
  ('near', 'centre'),
  ('centre', 'earth'),
  ('earth', '.'),
  ('.', '</s>')],
 [('<s>', 'let'),
  ('let', 'see'),
  ('see', 'would'),
  ('would', 'four'),
  ('four', 'thousand'),
  ('thousand', 'miles'),
  ('miles', 'think'),
  ('think', 'see'),
  ('see', 'alice'),
  ('alice', 'learnt'),
  ('learnt', 'several'),
  ('several', 'things'),
  ('things', 'sort'),
  ('sort', 'lessons'),
  ('lessons', 'schoolroom'),
  ('schoolroom', 'though'),
  ('though', 'good'),
  ('good', 'opportunity'),
  ('opportunity', 'showing'),
  ('showing', 'knowledge'),
  ('knowledge', 'one'),
  ('one', 'listen'),
  ('listen', 'still'),
  ('still', 'good'),
  ('good', 'practice'),
  ('practice', 'say'),
  ('say', 'yes'),
  ('yes', 'right'),
  ('right', 'distance'),
  ('distance', 'wonder'),
  ('wonder', 'latitude'),
  ('latitude', 'longitude'),
  ('longitude', 'got'),
  ('got', '?'),
  ('?', '</s>')],
 [('<s>', 'alice'),
  ('alice', 'idea'),
  ('idea', 'latitude'),
  ('latitude', 'longitude'),
  ('longitude', 'either'),
  ('either', 'thought'),
  ('thought', 'nice'),
  ('nice', 'grand'),
  ('grand', 'words'),
  ('words', 'say'),
  ('say', '.'),
  ('.', '</s>')],
 [('<s>', 'presently'), ('presently', 'began'), ('began', '.'), ('.', '</s>')],
 [('<s>', 'wonder'),
  ('wonder', 'shall'),
  ('shall', 'fall'),
  ('fall', 'right'),
  ('right', 'earth'),
  ('earth', 'funny'),
  ('funny', 'seem'),
  ('seem', 'come'),
  ('come', 'among'),
  ('among', 'people'),
  ('people', 'walk'),
  ('walk', 'heads'),
  ('heads', 'downward'),
  ('downward', 'antipathies'),
  ('antipathies', 'think'),
  ('think', 'rather'),
  ('rather', 'glad'),
  ('glad', 'one'),
  ('one', 'listening'),
  ('listening', 'time'),
  ('time', 'sound'),
  ('sound', 'right'),
  ('right', 'word'),
  ('word', 'shall'),
  ('shall', 'ask'),
  ('ask', 'name'),
  ('name', 'country'),
  ('country', 'know'),
  ('know', '.'),
  ('.', '</s>')],
 [('<s>', 'please'),
  ('please', 'new'),
  ('new', 'zealand'),
  ('zealand', 'australia'),
  ('australia', '?'),
  ('?', '</s>')],
 [('<s>', 'tried'),
  ('tried', 'curtsey'),
  ('curtsey', 'spoke'),
  ('spoke', 'fancy'),
  ('fancy', 'curtseying'),
  ('curtseying', 'falling'),
  ('falling', 'air'),
  ('air', 'think'),
  ('think', 'could'),
  ('could', 'manage'),
  ('manage', '?'),
  ('?', '</s>')],
 [('<s>', 'ignorant'),
  ('ignorant', 'little'),
  ('little', 'girl'),
  ('girl', 'think'),
  ('think', 'asking'),
  ('asking', 'never'),
  ('never', 'ask'),
  ('ask', 'perhaps'),
  ('perhaps', 'shall'),
  ('shall', 'see'),
  ('see', 'written'),
  ('written', 'somewhere'),
  ('somewhere', '..'),
  ('..', 'nothing'),
  ('nothing', 'else'),
  ('else', 'alice'),
  ('alice', 'soon'),
  ('soon', 'began'),
  ('began', 'talking'),
  ('talking', '.'),
  ('.', '</s>')],
 [('<s>', 'dinah'),
  ('dinah', 'miss'),
  ('miss', 'much'),
  ('much', 'to-night'),
  ('to-night', 'think'),
  ('think', 'dinah'),
  ('dinah', 'cat'),
  ('cat', '.'),
  ('.', '</s>')],
 [('<s>', 'hope'),
  ('hope', 'remember'),
  ('remember', 'saucer'),
  ('saucer', 'milk'),
  ('milk', 'tea-time'),
  ('tea-time', '.'),
  ('.', '</s>')],
 [('<s>', 'dinah'),
  ('dinah', 'dear'),
  ('dear', 'wish'),
  ('wish', 'mice'),
  ('mice', 'air'),
  ('air', 'afraid'),
  ('afraid', 'might'),
  ('might', 'catch'),
  ('catch', 'bat'),
  ('bat', 'like'),
  ('like', 'mouse'),
  ('mouse', 'know'),
  ('know', '.'),
  ('.', '</s>')],
 [('<s>', 'cats'),
  ('cats', 'eat'),
  ('eat', 'bats'),
  ('bats', 'wonder'),
  ('wonder', '?'),
  ('?', '</s>')],
 [('<s>', 'alice'),
  ('alice', 'began'),
  ('began', 'get'),
  ('get', 'rather'),
  ('rather', 'sleepy'),
  ('sleepy', 'went'),
  ('went', 'saying'),
  ('saying', 'dreamy'),
  ('dreamy', 'sort'),
  ('sort', 'way'),
  ('way', 'cats'),
  ('cats', 'eat'),
  ('eat', 'bats'),
  ('bats', '?'),
  ('?', '</s>')],
 [('<s>', 'cats'),
  ('cats', 'eat'),
  ('eat', 'bats'),
  ('bats', '?'),
  ('?', '</s>')],
 [('<s>', 'sometimes'),
  ('sometimes', 'bats'),
  ('bats', 'eat'),
  ('eat', 'cats'),
  ('cats', '?'),
  ('?', '</s>')],
 [('<s>', 'see'),
  ('see', 'answer'),
  ('answer', 'either'),
  ('either', 'question'),
  ('question', 'much'),
  ('much', 'matter'),
  ('matter', 'way'),
  ('way', 'put'),
  ('put', '.'),
  ('.', '</s>')],
 [('<s>', 'felt'),
  ('felt', 'dozing'),
  ('dozing', 'begun'),
  ('begun', 'dream'),
  ('dream', 'walking'),
  ('walking', 'hand'),
  ('hand', 'hand'),
  ('hand', 'dinah'),
  ('dinah', 'saying'),
  ('saying', 'earnestly'),
  ('earnestly', 'dinah'),
  ('dinah', 'tell'),
  ('tell', 'truth'),
  ('truth', 'ever'),
  ('ever', 'eat'),
  ('eat', 'bat'),
  ('bat', '?'),
  ('?', '</s>')],
 [('<s>', 'suddenly'),
  ('suddenly', 'thump'),
  ('thump', 'thump'),
  ('thump', 'came'),
  ('came', 'upon'),
  ('upon', 'heap'),
  ('heap', 'sticks'),
  ('sticks', 'dry'),
  ('dry', 'leaves'),
  ('leaves', 'fall'),
  ('fall', '.'),
  ('.', '</s>')],
 [('<s>', 'alice'),
  ('alice', 'bit'),
  ('bit', 'hurt'),
  ('hurt', 'jumped'),
  ('jumped', 'feet'),
  ('feet', 'moment'),
  ('moment', 'looked'),
  ('looked', 'dark'),
  ('dark', 'overhead'),
  ('overhead', 'another'),
  ('another', 'long'),
  ('long', 'passage'),
  ('passage', 'white'),
  ('white', 'rabbit'),
  ('rabbit', 'still'),
  ('still', 'sight'),
  ('sight', 'hurrying'),
  ('hurrying', '.'),
  ('.', '</s>')],
 [('<s>', 'moment'),
  ('moment', 'lost'),
  ('lost', 'away'),
  ('away', 'went'),
  ('went', 'alice'),
  ('alice', 'like'),
  ('like', 'wind'),
  ('wind', 'time'),
  ('time', 'hear'),
  ('hear', 'say'),
  ('say', 'turned'),
  ('turned', 'corner'),
  ('corner', 'oh'),
  ('oh', 'ears'),
  ('ears', 'whiskers'),
  ('whiskers', 'late'),
  ('late', 'getting'),
  ('getting', 'close'),
  ('close', 'behind'),
  ('behind', 'turned'),
  ('turned', 'corner'),
  ('corner', 'rabbit'),
  ('rabbit', 'longer'),
  ('longer', 'seen'),
  ('seen', 'found'),
  ('found', 'long'),
  ('long', 'low'),
  ('low', 'hall'),
  ('hall', 'lit'),
  ('lit', 'row'),
  ('row', 'lamps'),
  ('lamps', 'hanging'),
  ('hanging', 'roof'),
  ('roof', '.'),
  ('.', '</s>')],
 [('<s>', 'doors'),
  ('doors', 'round'),
  ('round', 'hall'),
  ('hall', 'locked'),
  ('locked', 'alice'),
  ('alice', 'way'),
  ('way', 'one'),
  ('one', 'side'),
  ('side', 'trying'),
  ('trying', 'every'),
  ('every', 'door'),
  ('door', 'walked'),
  ('walked', 'sadly'),
  ('sadly', 'middle'),
  ('middle', 'wondering'),
  ('wondering', 'ever'),
  ('ever', 'get'),
  ('get', '.'),
  ('.', '</s>')],
 [('<s>', 'suddenly'),
  ('suddenly', 'came'),
  ('came', 'upon'),
  ('upon', 'little'),
  ('little', 'three-legged'),
  ('three-legged', 'table'),
  ('table', 'made'),
  ('made', 'solid'),
  ('solid', 'glass'),
  ('glass', 'nothing'),
  ('nothing', 'except'),
  ('except', 'tiny'),
  ('tiny', 'golden'),
  ('golden', 'key'),
  ('key', 'alice'),
  ('alice', 'first'),
  ('first', 'thought'),
  ('thought', 'might'),
  ('might', 'belong'),
  ('belong', 'one'),
  ('one', 'doors'),
  ('doors', 'hall'),
  ('hall', 'alas'),
  ('alas', 'either'),
  ('either', 'locks'),
  ('locks', 'large'),
  ('large', 'key'),
  ('key', 'small'),
  ('small', 'rate'),
  ('rate', 'would'),
  ('would', 'open'),
  ('open', '.'),
  ('.', '</s>')],
 [('<s>', 'however'),
  ('however', 'second'),
  ('second', 'time'),
  ('time', 'round'),
  ('round', 'came'),
  ('came', 'upon'),
  ('upon', 'low'),
  ('low', 'curtain'),
  ('curtain', 'noticed'),
  ('noticed', 'behind'),
  ('behind', 'little'),
  ('little', 'door'),
  ('door', 'fifteen'),
  ('fifteen', 'inches'),
  ('inches', 'high'),
  ('high', 'tried'),
  ('tried', 'little'),
  ('little', 'golden'),
  ('golden', 'key'),
  ('key', 'lock'),
  ('lock', 'great'),
  ('great', 'delight'),
  ('delight', 'fitted'),
  ('fitted', 'alice'),
  ('alice', 'opened'),
  ('opened', 'door'),
  ('door', 'found'),
  ('found', 'led'),
  ('led', 'small'),
  ('small', 'passage'),
  ('passage', 'much'),
  ('much', 'larger'),
  ('larger', 'rat-hole'),
  ('rat-hole', 'knelt'),
  ('knelt', 'looked'),
  ('looked', 'along'),
  ('along', 'passage'),
  ('passage', 'loveliest'),
  ('loveliest', 'garden'),
  ('garden', 'ever'),
  ('ever', 'saw'),
  ('saw', '.'),
  ('.', '</s>')],
 [('<s>', 'longed'),
  ('longed', 'get'),
  ('get', 'dark'),
  ('dark', 'hall'),
  ('hall', 'wander'),
  ('wander', 'among'),
  ('among', 'beds'),
  ('beds', 'bright'),
  ('bright', 'flowers'),
  ('flowers', 'cool'),
  ('cool', 'fountains'),
  ('fountains', 'could'),
  ('could', 'even'),
  ('even', 'get'),
  ('get', 'head'),
  ('head', 'doorway'),
  ('doorway', 'even'),
  ('even', 'head'),
  ('head', 'would'),
  ('would', 'go'),
  ('go', 'thought'),
  ('thought', 'poor'),
  ('poor', 'alice'),
  ('alice', 'would'),
  ('would', 'little'),
  ('little', 'use'),
  ('use', 'without'),
  ('without', 'shoulders'),
  ('shoulders', '.'),
  ('.', '</s>')],
 [('<s>', 'oh'),
  ('oh', 'wish'),
  ('wish', 'could'),
  ('could', 'shut'),
  ('shut', 'like'),
  ('like', 'telescope'),
  ('telescope', 'think'),
  ('think', 'could'),
  ('could', 'knew'),
  ('knew', 'begin'),
  ('begin', '.'),
  ('.', '</s>')],
 [('<s>', 'see'),
  ('see', 'many'),
  ('many', 'out-of-the-way'),
  ('out-of-the-way', 'things'),
  ('things', 'happened'),
  ('happened', 'lately'),
  ('lately', 'alice'),
  ('alice', 'begun'),
  ('begun', 'think'),
  ('think', 'things'),
  ('things', 'indeed'),
  ('indeed', 'really'),
  ('really', 'impossible'),
  ('impossible', '.'),
  ('.', '</s>')],
 [('<s>', 'seemed'),
  ('seemed', 'use'),
  ('use', 'waiting'),
  ('waiting', 'little'),
  ('little', 'door'),
  ('door', 'went'),
  ('went', 'back'),
  ('back', 'table'),
  ('table', 'half'),
  ('half', 'hoping'),
  ('hoping', 'might'),
  ('might', 'find'),
  ('find', 'another'),
  ('another', 'key'),
  ('key', 'rate'),
  ('rate', 'book'),
  ('book', 'rules'),
  ('rules', 'shutting'),
  ('shutting', 'people'),
  ('people', 'like'),
  ('like', 'telescopes'),
  ('telescopes', 'time'),
  ('time', 'found'),
  ('found', 'little'),
  ('little', 'bottle'),
  ('bottle', 'certainly'),
  ('certainly', 'said'),
  ('said', 'alice'),
  ('alice', 'round'),
  ('round', 'neck'),
  ('neck', 'bottle'),
  ('bottle', 'paper'),
  ('paper', 'label'),
  ('label', 'words'),
  ('words', 'drink'),
  ('drink', 'beautifully'),
  ('beautifully', 'printed'),
  ('printed', 'large'),
  ('large', 'letters'),
  ('letters', '.'),
  ('.', '</s>')],
 [('<s>', 'well'),
  ('well', 'say'),
  ('say', 'drink'),
  ('drink', 'wise'),
  ('wise', 'little'),
  ('little', 'alice'),
  ('alice', 'going'),
  ('going', 'hurry'),
  ('hurry', '.'),
  ('.', '</s>')],
 [('<s>', 'look'),
  ('look', 'first'),
  ('first', 'said'),
  ('said', 'see'),
  ('see', 'whether'),
  ('whether', 'marked'),
  ('marked', 'poison'),
  ('poison', 'read'),
  ('read', 'several'),
  ('several', 'nice'),
  ('nice', 'little'),
  ('little', 'histories'),
  ('histories', 'children'),
  ('children', 'got'),
  ('got', 'burnt'),
  ('burnt', 'eaten'),
  ('eaten', 'wild'),
  ('wild', 'beasts'),
  ('beasts', 'unpleasant'),
  ('unpleasant', 'things'),
  ('things', 'would'),
  ('would', 'remember'),
  ('remember', 'simple'),
  ('simple', 'rules'),
  ('rules', 'friends'),
  ('friends', 'taught'),
  ('taught', 'red-hot'),
  ('red-hot', 'poker'),
  ('poker', 'burn'),
  ('burn', 'hold'),
  ('hold', 'long'),
  ('long', 'cut'),
  ('cut', 'finger'),
  ('finger', 'deeply'),
  ('deeply', 'knife'),
  ('knife', 'usually'),
  ('usually', 'bleeds'),
  ('bleeds', 'never'),
  ('never', 'forgotten'),
  ('forgotten', 'drink'),
  ('drink', 'much'),
  ('much', 'bottle'),
  ('bottle', 'marked'),
  ('marked', 'poison'),
  ('poison', 'almost'),
  ('almost', 'certain'),
  ('certain', 'disagree'),
  ('disagree', 'sooner'),
  ('sooner', 'later'),
  ('later', '.'),
  ('.', '</s>')],
 [('<s>', 'however'),
  ('however', 'bottle'),
  ('bottle', 'marked'),
  ('marked', 'poison'),
  ('poison', 'alice'),
  ('alice', 'ventured'),
  ('ventured', 'taste'),
  ('taste', 'finding'),
  ('finding', 'nice'),
  ('nice', 'fact'),
  ('fact', 'sort'),
  ('sort', 'mixed'),
  ('mixed', 'flavour'),
  ('flavour', 'cherry-tart'),
  ('cherry-tart', 'custard'),
  ('custard', 'pine-apple'),
  ('pine-apple', 'roast'),
  ('roast', 'turkey'),
  ('turkey', 'toffee'),
  ('toffee', 'hot'),
  ('hot', 'buttered'),
  ('buttered', 'toast'),
  ('toast', 'soon'),
  ('soon', 'finished'),
  ('finished', '.'),
  ('.', '</s>')],
 [('<s>', 'curious'),
  ('curious', 'feeling'),
  ('feeling', 'said'),
  ('said', 'alice'),
  ('alice', 'must'),
  ('must', 'shutting'),
  ('shutting', 'like'),
  ('like', 'telescope'),
  ('telescope', '.'),
  ('.', '</s>')],
 [('<s>', 'indeed'),
  ('indeed', 'ten'),
  ('ten', 'inches'),
  ('inches', 'high'),
  ('high', 'face'),
  ('face', 'brightened'),
  ('brightened', 'thought'),
  ('thought', 'right'),
  ('right', 'size'),
  ('size', 'going'),
  ('going', 'little'),
  ('little', 'door'),
  ('door', 'lovely'),
  ('lovely', 'garden'),
  ('garden', '.'),
  ('.', '</s>')],
 [('<s>', 'first'),
  ('first', 'however'),
  ('however', 'waited'),
  ('waited', 'minutes'),
  ('minutes', 'see'),
  ('see', 'going'),
  ('going', 'shrink'),
  ('shrink', 'felt'),
  ('felt', 'little'),
  ('little', 'nervous'),
  ('nervous', 'might'),
  ('might', 'end'),
  ('end', 'know'),
  ('know', 'said'),
  ('said', 'alice'),
  ('alice', 'going'),
  ('going', 'altogether'),
  ('altogether', 'like'),
  ('like', 'candle'),
  ('candle', '.'),
  ('.', '</s>')],
 [('<s>', 'wonder'), ('wonder', 'like'), ('like', '?'), ('?', '</s>')],
 [('<s>', 'tried'),
  ('tried', 'fancy'),
  ('fancy', 'flame'),
  ('flame', 'candle'),
  ('candle', 'like'),
  ('like', 'candle'),
  ('candle', 'blown'),
  ('blown', 'could'),
  ('could', 'remember'),
  ('remember', 'ever'),
  ('ever', 'seen'),
  ('seen', 'thing'),
  ('thing', '.'),
  ('.', '</s>')],
 [('<s>', 'finding'),
  ('finding', 'nothing'),
  ('nothing', 'happened'),
  ('happened', 'decided'),
  ('decided', 'going'),
  ('going', 'garden'),
  ('garden', 'alas'),
  ('alas', 'poor'),
  ('poor', 'alice'),
  ('alice', 'got'),
  ('got', 'door'),
  ('door', 'found'),
  ('found', 'forgotten'),
  ('forgotten', 'little'),
  ('little', 'golden'),
  ('golden', 'key'),
  ('key', 'went'),
  ('went', 'back'),
  ('back', 'table'),
  ('table', 'found'),
  ('found', 'could'),
  ('could', 'possibly'),
  ('possibly', 'reach'),
  ('reach', 'could'),
  ('could', 'see'),
  ('see', 'quite'),

In [66]:
biModel = {}

for bi in bigram:
  for b in bi:
    context = (b[0])
    next = b[1]
    if context not in biModel:
      biModel[context] = {}

    if next not in biModel[context]:
        biModel[context][next] = 1
    else:
        biModel[context][next] += 1

In [67]:
biModel

{'<s>': {'rabbit-hole': 2,
  'considering': 1,
  'nothing': 8,
  'another': 4,
  'either': 1,
  'first': 13,
  'took': 3,
  'well': 23,
  'wonder': 5,
  'said': 84,
  'must': 13,
  'let': 6,
  'alice': 73,
  'presently': 2,
  'please': 6,
  'tried': 3,
  'ignorant': 1,
  'dinah': 2,
  'hope': 2,
  'cats': 2,
  'sometimes': 1,
  'see': 8,
  'felt': 2,
  'suddenly': 2,
  'moment': 4,
  'doors': 1,
  'however': 10,
  'longed': 1,
  'oh': 19,
  'seemed': 3,
  'look': 3,
  'curious': 4,
  'indeed': 3,
  'finding': 1,
  'come': 16,
  'use': 2,
  'way': 2,
  'holding': 1,
  'set': 2,
  'pool': 1,
  'sure': 3,
  'went': 6,
  'hearthrug': 1,
  'poor': 7,
  'ought': 3,
  'time': 8,
  'white': 3,
  'almost': 2,
  'next': 6,
  'ah': 3,
  'london': 1,
  'tell': 9,
  'done': 3,
  'thought': 8,
  'got': 6,
  'narrow': 1,
  'wish': 4,
  'shall': 8,
  'heard': 3,
  'would': 12,
  'everything': 3,
  'began': 5,
  'tired': 1,
  'perhaps': 4,
  'knowledge': 1,
  'mouse': 3,
  'quite': 7,
  'like': 6,
  'yet': 4,
  'dear': 1,
  'talk': 2,
  'fond': 2,
  'called': 2,
  'high': 1,
  'caucus-race': 2,
  'last': 5,
  'ahem': 1,
  'driest': 1,
  'silence': 1,
  'edwin': 2,
  'beg': 3,
  'proceed': 1,
  'found': 2,
  'know': 17,
  'question': 2,
  'william': 1,
  'insolence': 1,
  'continued': 2,
  'wet': 1,
  'case': 2,
  'going': 2,
  'might': 4,
  'one': 6,
  'give': 6,
  'course': 11,
  'exactly': 3,
  'else': 1,
  'thimble': 1,
  'hand': 1,
  'crowded': 1,
  'promised': 1,
  'mine': 2,
  'long': 4,
  'kept': 2,
  'judge': 3,
  'attending': 1,
  'thinking': 3,
  'cried': 1,
  'knot': 1,
  'insult': 1,
  'easily': 1,
  'pity': 1,
  'enough': 3,
  'soon': 7,
  'capital': 1,
  'birds': 1,
  'nobody': 3,
  'little': 3,
  'rabbit': 2,
  'run': 1,
  'surprised': 1,
  'queer': 1,
  'think': 7,
  'label': 1,
  'hastily': 1,
  'still': 1,
  'become': 1,
  'luckily': 1,
  'much': 4,
  'comfort': 1,
  'learn': 2,
  'hardly': 3,
  'mary': 1,
  'fetch': 2,
  'get': 6,
  'voice': 1,
  'arm': 1,
  'fills': 1,
  'number': 1,
  'bring': 1,
  'mind': 2,
  'bill': 1,
  'nay': 1,
  'shy': 1,
  'happened': 1,
  'minute': 2,
  'barrowful': 1,
  'put': 1,
  'eat': 1,
  'swallowed': 1,
  'made': 2,
  'sounded': 1,
  'enormous': 1,
  'suppose': 4,
  'great': 2,
  'large': 3,
  'stretched': 1,
  'advice': 1,
  'encouraging': 1,
  'mean': 6,
  'explain': 3,
  'afraid': 4,
  'bit': 1,
  'brought': 1,
  'something': 1,
  'keep': 3,
  'minutes': 1,
  'repeat': 1,
  'youth': 3,
  'old': 4,
  'answered': 1,
  'kick': 1,
  'wrong': 2,
  'caterpillar': 1,
  'size': 1,
  'asked': 7,
  'content': 1,
  'good': 1,
  'used': 1,
  'side': 1,
  'mushroom': 1,
  'chin': 1,
  'green': 1,
  'shoulders': 1,
  'moving': 1,
  'succeeded': 1,
  'serpent': 2,
  'trouble': 1,
  'taken': 1,
  'likely': 1,
  'seen': 2,
  'believe': 4,
  'new': 1,
  'matters': 2,
  'remembered': 1,
  'whoever': 1,
  'pig': 2,
  'opened': 2,
  'fish-footman': 1,
  'invitation': 2,
  'frog-footman': 1,
  'bowed': 1,
  'sort': 3,
  'certainly': 5,
  'instance': 2,
  'looking': 3,
  'rate': 2,
  'repeated': 1,
  'doubt': 1,
  'really': 4,
  'anything': 2,
  'door': 1,
  'even': 3,
  'things': 1,
  'cheshire': 2,
  'trying': 1,
  'duchess': 3,
  'everybody': 2,
  'chorus': 1,
  'cook': 2,
  'wow': 1,
  'take': 5,
  'grunt': 1,
  'baby': 1,
  'could': 3,
  'tears': 1,
  'grunted': 1,
  'grown': 1,
  'cat': 4,
  'looked': 4,
  'depends': 1,
  'matter': 1,
  'direction': 1,
  'visit': 1,
  'want': 2,
  'mad': 3,
  'begin': 3,
  'grant': 1,
  'growl': 1,
  'therefore': 1,
  'call': 4,
  'play': 2,
  'by-the-bye': 1,
  'nearly': 2,
  'turned': 1,
  'say': 3,
  'right': 6,
  'uncomfortable': 1,
  'table': 1,
  'plenty': 1,
  'wine': 1,
  'civil': 2,
  'hair': 1,
  'hatter': 9,
  'glad': 3,
  'thing': 3,
  'day': 1,
  'two': 2,
  'told': 1,
  'best': 2,
  'yes': 9,
  'march': 1,
  'funny': 1,
  'tells': 1,
  'muttered': 1,
  'watch': 1,
  'dormouse': 6,
  'guessed': 1,
  'slightest': 1,
  'knew': 1,
  'dare': 3,
  'stand': 2,
  'replied': 1,
  'quarrelled': 1,
  'goes': 1,
  'twinkle': 1,
  'ever': 1,
  'bright': 1,
  'reason': 3,
  'happens': 1,
  'getting': 2,
  'vote': 1,
  'wake': 2,
  'asleep': 1,
  'quick': 1,
  'upon': 1,
  'lived': 1,
  'making': 1,
  'live': 1,
  'three': 2,
  'treacle': 2,
  'moved': 1,
  'draw': 2,
  'answer': 1,
  'learning': 1,
  'piece': 1,
  'stupidest': 1,
  'manage': 2,
  'queen': 7,
  'seven': 2,
  'none': 1,
  'five': 1,
  'sound': 1,
  'came': 3,
  'followed': 1,
  'stood': 1,
  'procession': 1,
  'idiot': 1,
  'name': 1,
  'business': 1,
  'king': 6,
  'leave': 1,
  'make': 2,
  'turning': 1,
  'may': 3,
  'heads': 3,
  'beheaded': 1,
  'shouted': 1,
  'soldiers': 1,
  'fine': 2,
  'walking': 1,
  'hush': 1,
  'boxed': 1,
  'chief': 1,
  'players': 1,
  'dreadfully': 1,
  'talking': 1,
  'friend': 1,
  'rather': 3,
  'impertinent': 1,
  'read': 1,
  'head': 2,
  'already': 1,
  'hedgehog': 1,
  'tucked': 1,
  'executioner': 2,
  'prison': 1,
  'mock': 4,
  'soup': 2,
  'tut': 1,
  'squeezed': 1,
  'game': 1,
  'tis': 1,
  'true': 1,
  'moral': 2,
  'mustard': 1,
  'pray': 1,
  'cheap': 1,
  'guests': 1,
  'never': 8,
  'lazy': 1,
  'gryphon': 5,
  'fun': 2,
  'fancy': 1,
  'pitied': 1,
  'sorrow': 1,
  'young': 1,
  'sat': 2,
  'waited': 1,
  'words': 2,
  'master': 1,
  'hold': 1,
  'extras': 1,
  'washing': 1,
  'end': 2,
  'wanted': 1,
  'afford': 1,
  'inquired': 1,
  'reeling': 1,
  'many': 1,
  'ten': 1,
  'eleventh': 1,
  'chapter': 1,
  'bone': 1,
  'seals': 1,
  'advance': 1,
  'far': 2,
  'turn': 1,
  'change': 1,
  'back': 1,
  'without': 1,
  'forgotten': 1,
  'porpoise': 1,
  'join': 4,
  'scaly': 1,
  'england': 1,
  'thank': 1,
  'tails': 2,
  'fall': 1,
  'boots': 3,
  'shoes': 1,
  'soles': 1,
  'whiting': 1,
  'adventures': 1,
  'listeners': 1,
  'creatures': 1,
  'duck': 1,
  'later': 1,
  'different': 1,
  'go': 4,
  'toes': 1,
  'pie': 1,
  'pennyworth': 1,
  'beau': 1,
  'trial': 2,
  'stole': 1,
  'middle': 1,
  'jury-box': 1,
  'twelve': 1,
  'putting': 1,
  'stupid': 1,
  'nice': 1,
  'quickly': 1,
  'herald': 1,
  'fourteenth': 1,
  'fifteenth': 1,
  'sixteenth': 1,
  'write': 1,
  'stolen': 1,
  'seem': 1,
  'help': 1,
  'deny': 1,
  'denies': 1,
  'remember': 1,
  'miserable': 1,
  'often': 1,
  'guinea-pig': 1,
  'carried': 1,
  'pepper': 1,
  'collar': 1,
  'behead': 1,
  'added': 2,
  'imagine': 1,
  'persisted': 1,
  'important': 2,
  'beginning': 1,
  'unimportant': 1,
  'jury': 4,
  'persons': 1,
  'mile': 1,
  'oldest': 1,
  'consider': 1,
  'evidence': 1,
  'directed': 2,
  'unfolded': 1,
  'prisoner': 1,
  'sign': 1,
  'general': 1,
  'proves': 2,
  'verses': 1,
  'sent': 1,
  'gave': 1,
  'chance': 1,
  'notion': 1,
  'meaning': 1,
  'knave': 1,
  'fit': 1,
  'unfortunate': 1,
  'dead': 1,
  'pun': 1,
  'sentence': 1,
  'stuff': 1,
  'idea': 1,
  'cares': 1,
  'sister': 1,
  'lastly': 1},
 'rabbit-hole': {'alice': 1, 'hedge': 1, 'went': 1, 'yet': 1},
 'alice': {'beginning': 4,
  'without': 1,
  'think': 3,
  'started': 1,
  'never': 3,
  'moment': 2,
  'fall': 1,
  'learnt': 1,
  'idea': 2,
  'soon': 3,
  'began': 7,
  'bit': 1,
  'like': 4,
  'way': 1,
  'first': 1,
  'opened': 1,
  'would': 2,
  'begun': 1,
  'round': 1,
  'going': 2,
  'ventured': 4,
  'must': 1,
  'got': 3,
  'rather': 5,
  'pretend': 1,
  'makes': 1,
  'much': 7,
  'perhaps': 2,
  'right': 1,
  'love': 1,
  'great': 3,
  'felt': 7,
  'took': 1,
  'eyes': 1,
  'sudden': 1,
  'good': 3,
  'seaside': 1,
  'swam': 1,
  'speak': 1,
  'thought': 13,
  'daresay': 1,
  'clear': 1,
  'hastily': 4,
  'soothing': 1,
  'went': 9,
  'time': 2,
  'sorrowful': 1,
  'led': 1,
  'find': 1,
  'kept': 1,
  'spoke': 2,
  'melancholy': 1,
  'wanted': 1,
  'one': 2,
  '.': 57,
  'sadly': 1,
  'hate': 1,
  'sighing': 1,
  'looking': 3,
  'severely': 1,
  'humbly': 1,
  'always': 2,
  'called': 2,
  'aloud': 1,
  'replied': 9,
  'guessed': 2,
  'said': 12,
  'come': 1,
  'little': 4,
  'shall': 1,
  'answered': 1,
  'knew': 1,
  'elbow': 1,
  'heard': 3,
  'waiting': 1,
  'could': 11,
  'well': 1,
  'long': 1,
  'noticed': 2,
  'wandered': 1,
  'coaxing': 1,
  'dodged': 1,
  'thinking': 1,
  'leant': 1,
  'looked': 8,
  'see': 1,
  'turn': 1,
  'know': 1,
  'turned': 1,
  'swallowing': 1,
  'remember': 1,
  'folded': 1,
  'timidly': 2,
  'three': 1,
  'piteous': 1,
  'waited': 3,
  'remained': 1,
  'tone': 2,
  'indignantly': 3,
  'puzzled': 1,
  'truthful': 1,
  'quite': 7,
  'crouched': 1,
  'laughed': 1,
  'get': 1,
  'louder': 1,
  'desperately': 1,
  'jumping': 1,
  'glanced': 1,
  'flinging': 1,
  'caught': 1,
  'sure': 1,
  'proper': 1,
  'seriously': 1,
  'added': 1,
  'remarked': 2,
  'invited': 1,
  'quietly': 1,
  'wish': 2,
  'grin': 1,
  'asleep': 1,
  'coming': 1,
  'angrily': 1,
  'laid': 1,
  'taken': 1,
  'considered': 1,
  'sighed': 1,
  'cautiously': 2,
  'thoughtfully': 1,
  'asked': 3,
  'head': 1,
  'gently': 1,
  'tried': 2,
  'earnestly': 1,
  'let': 1,
  'silent': 1,
  'picked': 1,
  'stood': 1,
  'recognised': 1,
  'stopped': 1,
  'please': 1,
  'politely': 1,
  'surprised': 1,
  'loudly': 2,
  'protection': 1,
  'put': 2,
  'question': 1,
  'joined': 1,
  'duchess': 1,
  'gave': 1,
  'found': 1,
  'extremely': 1,
  'allow': 1,
  'excellent': 1,
  'arches': 1,
  'appeared': 1,
  'walked': 1,
  'glad': 2,
  'side': 1,
  'shoulder': 2,
  'whispered': 2,
  'attended': 1,
  'sharply': 1,
  'alice': 1,
  'custody': 1,
  'seen': 1,
  'alone': 1,
  'nearly': 1,
  'proud': 1,
  'learned': 1,
  'living': 1,
  'doubtfully': 1,
  'feel': 1,
  'hurry': 1,
  'every': 1,
  'feeling': 1,
  'often': 1,
  'interesting': 1,
  'thoroughly': 1,
  'whose': 1,
  'might': 1,
  'dare': 1,
  'hand': 1,
  'panted': 1,
  'twelve': 1,
  'meekly': 1,
  'boldly': 1,
  'watched': 1,
  'chapter': 1,
  'evidence': 1,
  'besides': 1,
  'grown': 2,
  'dear': 1,
  'told': 1,
  'wonderful': 1,
  'tiny': 1},
 'beginning': {'get': 1,
  'conversation': 1,
  'end': 2,
  'see': 1,
  'think': 1,
  '?': 1,
  'angrily': 1,
  'feel': 1,
  'morning': 1,
  'heard': 1,
  'grow': 1,
  'write': 1,
  'king': 1},
 'get': {'tired': 1,
  '.': 3,
  'rather': 1,
  'dark': 1,
  'head': 2,
  'garden': 1,
  'hopeless': 1,
  'twenty': 1,
  'shore': 1,
  'dry': 2,
  'us': 1,
  'executed': 1,
  'ready': 2,
  'door': 3,
  'older': 1,
  'window': 1,
  'hold': 2,
  'used': 2,
  'beautiful': 1,
  '?': 4,
  'opportunity': 1,
  'home': 1,
  'said': 2,
  'somewhere': 1,
  'thing': 1,
  'like': 1,
  'places': 1,
  'away': 1,
  '..': 1,
  'trial': 1,
  'leave': 1,
  'better': 1,
  'eyes': 1},
 'tired': {'sitting': 1,
  'trying': 1,
  'alone': 1,
  'swimming': 1,
  'tiny': 1,
  'breath': 1,
  '.': 1},
 'sitting': {'sister': 1,
  'top': 1,
  'ground': 1,
  'three-legged': 1,
  'hearth': 1,
  'bough': 1,
  'branch': 1,
  'fast': 1,
  'sad': 1,
  'next': 1},
 'sister': {'bank': 1,
  'reading': 1,
  'gently': 1,
  'long': 1,
  'well': 1,
  'kissed': 1,
  'sat': 1,
  'dream': 1,
  'would': 1},
 'bank': {'nothing': 1, 'birds': 1, 'head': 1},
 'nothing': {'twice': 1,
  'remarkable': 1,
  'tumbling': 1,
  'else': 3,
  'except': 1,
  'happened': 2,
  'out-of-the-way': 1,
  '.': 6,
  'sort': 2,
  'never': 1,
  'tops': 1,
  'seems': 1,
  'tea': 1,
  'better': 1,
  'yet': 1,
  'looked': 1,
  'could': 1,
  'sat': 1,
  'fast': 1,
  'said': 1,
  'whatever': 2,
  'written': 1,
  'clearer': 1,
  'pack': 1},
 'twice': {'peeped': 1, 'shook': 1, 'half': 1, 'lobster': 1, 'set': 1},
 'peeped': {'book': 1, 'edge': 1, 'fish-footman': 1},
 'book': {'sister': 1,
  'thought': 1,
  'rules': 1,
  'written': 1,
  'remember': 1,
  'rule': 1,
  'said': 1},
 'reading': {'pictures': 1, 'list': 1, 'finished': 1},
 'pictures': {'conversations': 2, 'hung': 1, 'rest': 1},
 'conversations': {'use': 1, '?': 1},
 'use': {'book': 1,
  'without': 1,
  'waiting': 1,
  'crying': 1,
  'thought': 2,
  'putting': 1,
  'ointment': 1,
  'saying': 1,
  'denying': 1,
  'knocking': 1,
  'talking': 1,
  'procession': 1,
  'speaking': 1,
  'going': 1,
  'repeating': 1,
  'left': 1,
  'trial': 1},
 'thought': {'alice': 26,
  'afterwards': 1,
  'nice': 1,
  'might': 4,
  'poor': 4,
  'right': 1,
  'funny': 1,
  '.': 4,
  'must': 3,
  'said': 3,
  'somebody': 1,
  'sat': 1,
  'whole': 1,
  'wonder': 1,
  'sure': 1,
  'wish': 1,
  'use': 1,
  'decidedly': 1,
  'would': 4,
  'looked': 1,
  'still': 1,
  'could': 1,
  'curious': 1,
  'people': 1,
  'never': 1,
  'till': 1,
  'perhaps': 1,
  'see': 1,
  'little': 1,
  'kind': 1,
  'hand': 1,
  'rightly': 1,
  'first': 1},
 'without': {'pictures': 1,
  'shoulders': 1,
  'knowing': 1,
  'great': 1,
  'trying': 1,
  'knocking': 1,
  'hearing': 1,
  'speaking': 1,
  'attending': 2,
  'moment': 1,
  'grin': 1,
  'cat': 1,
  'invited': 1,
  'opening': 1,
  'considering': 1,
  'interrupting': 1,
  'noticing': 1,
  'waiting': 2,
  'seen': 1,
  'even': 2,
  'maybe': 1,
  'lobsters': 1,
  'porpoise': 1},
 '?': {'</s>': 203},
 'considering': {'mind': 1, 'world': 1, 'time': 1},
 'mind': {'well': 1,
  'never': 1,
  'mabel': 1,
  'coming': 1,
  'loose': 1,
  'turned': 1,
  'said': 2,
  'cried': 1,
  'poor': 1,
  '.': 1},
 'well': {'could': 6,
  '.': 3,
  'deep': 1,
  'noticed': 1,
  'thought': 1,
  'say': 5,
  'eat': 1,
  'perhaps': 3,
  'enough': 3,
  'got': 1,
  'hardly': 2,
  'look': 1,
  'wait': 1,
  'tried': 1,
  'like': 1,
  '?': 3,
  'said': 2,
  'introduce': 1,
  'pigs': 1,
  'cat': 1,
  'often': 1,
  'hatter': 1,
  'live': 1,
  'alice': 1,
  'go': 3,
  'unjust': 1,
  'must': 2,
  'without': 1,
  'means': 1,
  'gryphon': 1,
  'mystery': 1,
  'show': 1,
  'school': 1,
  'never': 1,
  'whole': 1,
  'looking': 1,
  'rate': 1,
  'might': 1},
 'could': {'hot': 1,
  'manage': 1,
  'even': 2,
  'shut': 1,
  'knew': 1,
  'remember': 4,
  'possibly': 2,
  'see': 7,
  'lying': 1,
  'go': 2,
  'changed': 1,
  'guess': 1,
  'show': 1,
  'answer': 1,
  'think': 4,
  '.': 4,
  'taste': 1,
  'hear': 4,
  'sure': 1,
  'waited': 1,
  'set': 1,
  'soon': 1,
  'neck': 1,
  'let': 1,
  'sneezing': 1,
  'grin': 1,
  'abide': 1,
  'hardly': 1,
  'hold': 1,
  'doubt': 1,
  'mistake': 1,
  'denied': 1,
  'keep': 1,
  'draw': 1,
  'bear': 1,
  'tell': 2,
  'help': 2,
  'get': 2,
  'beheaded': 1,
  'say': 1,
  'speak': 1,
  'would': 3,
  'could': 1,
  'join': 1,
  'told': 1,
  'turn': 1,
  'stand': 1,
  'make': 1,
  'accident': 1,
  'swim': 2},
 'hot': {'day': 1, 'buttered': 1, 'kept': 1, 'tea': 1, 'tureen': 1},
 'day': {'made': 1,
  'tell': 1,
  'confusing': 1,
  'know': 1,
  'stuff': 1,
  'wink': 1,
  '.': 4,
  'maybe': 1,
  'night': 1,
  'two': 1,
  'month': 2,
  'said': 2,
  'majesty': 1,
  'went': 1,
  'day-school': 1,
  'lessons': 1,
  'day': 1,
  'must': 1,
  'little': 1,
  'knave': 1},
 'made': {'feel': 1,
  'solid': 1,
  'mind': 1,
  'pool': 1,
  'mouse': 1,
  '.': 1,
  'snatch': 1,
  'another': 2,
  'words': 1,
  'rush': 1,
  'look': 1,
  'believe': 1,
  'awfully': 1,
  'draw': 1,
  'proper': 1,
  'dreadfully': 1,
  'grin': 1,
  'whole': 1,
  'savage': 1,
  'said': 1,
  'next': 1,
  '?': 2,
  'alice': 1,
  'tarts': 1,
  'memorandum': 1,
  'beginning': 1,
  'entirely': 1,
  'mark': 1},
 'feel': {'sleepy': 1,
  'way': 1,
  'little': 2,
  'queer': 1,
  'uneasy': 1,
  'encouraged': 1,
  'simple': 1},
 'sleepy': {'stupid': 1, 'went': 1, 'voice': 2, 'drew': 1},
 'stupid': {'whether': 1, 'life': 1, '?': 1, 'things': 2, 'ask': 1},
 'whether': {'pleasure': 1,
  'marked': 1,
  'little': 1,
  'good': 1,
  'blows': 1,
  'would': 1,
  'ought': 1,
  'gardeners': 1,
  'could': 1,
  'turn': 1,
  'nervous': 1},
 'pleasure': {'making': 1, 'simple': 1},
 'making': {'daisy-chain': 1,
  'quite': 2,
  'escape': 1,
  'short': 1,
  'noise': 1,
  'personal': 1,
  'faces': 1},
 'daisy-chain': {'would': 1},
 'would': {'worth': 1,
  'fall': 1,
  'four': 1,
  'open': 1,
  'go': 5,
  'little': 1,
  'remember': 1,
  'manage': 1,
  'put': 1,
  'use': 2,
  'like': 6,
  'talk': 1,
  'say': 1,
  'allow': 1,
  'catch': 1,
  'caucus-race': 1,
  'offended': 1,
  'wasting': 1,
  'happen': 3,
  'likely': 1,
  'feel': 2,
  'hardly': 1,
  'bend': 1,
  'called': 1,
  'tell': 3,
  'well': 1,
  'advantage': 1,
  'make': 1,
  'quite': 3,
  'made': 1,
  'said': 1,
  'grand': 1,
  'call': 1,
  'twist': 1,
  'become': 2,
  'cat': 1,
  'seem': 1,
  'appeared': 1,
  'cost': 1,
  'break': 1,
  'join': 2,
  'could': 4,
  'wash': 1,
  'ever': 1,
  'come': 1,
  'kind': 1,
  'stoop': 1,
  'give': 1,
  'done': 1,
  'get': 1,
  'deny': 1,
  'die': 1,
  'always': 1,
  'change': 3,
  'rustling': 1,
  'take': 1,
  'after-time': 1,
  'keep': 1,
  'gather': 1},
 'worth': {'trouble': 1, 'hundred': 1, 'hearing': 1, 'finishing': 1},
 'trouble': {'getting': 1,
  'must': 1,
  'enough': 1,
  'say': 1,
  'said': 1,
  'know': 1},
 'getting': {'picking': 1,
  'somewhere': 1,
  'close': 1,
  'far': 1,
  'quite': 1,
  'dear': 1,
  'walking': 2,
  'home': 1,
  'room': 1,
  'hands': 1,
  'entangled': 1,
  'extremely': 1,
  'used': 1,
  'tired': 1,
  'sleepy': 1,
  'body': 1,
  '?': 1,
  'saying': 1,
  'thin': 1,
  'dormouse': 1,
  'late': 1},
 'picking': {'daisies': 1, 'quickly': 1},
 'daisies': {'suddenly': 1},
 'suddenly': {'white': 1,
  'suddenly': 1,
  'alice': 1,
  'thump': 1,
  'came': 1,
  'called': 1,
  'spread': 1,
  'upon': 1,
  'footman': 1,
  'appeared': 1,
  'make': 1,
  'others': 1,
  'dropping': 1},
 'white': {'rabbit': 22, 'kid': 5, 'yet': 1, 'three': 1, 'one': 1},
 'rabbit': {'pink': 1,
  'say': 2,
  'actually': 1,
  'either': 1,
  'still': 1,
  'longer': 1,
  'returning': 1,
  'came': 2,
  'started': 1,
  'little': 1,
  'sends': 1,
  'trotting': 1,
  'noticed': 1,
  'engraved': 1,
  'suppose': 1,
  'coming': 1,
  'reason': 1,
  'window': 1,
  'pat': 1,
  'angrily': 1,
  'voice': 2,
  'talking': 1,
  'peeping': 1,
  'low': 1,
  'asked': 1,
  'began': 1,
  'whispered': 1,
  '.': 1,
  'trumpet': 1,
  'cried': 1,
  'blew': 2,
  'hastily': 1,
  'said': 1,
  'fumbled': 1,
  'read': 2,
  'interrupted': 1,
  'jumping': 1,
  'seems': 1,
  'fact': 1,
  'queerest': 1,
  'put': 1,
  'hurried': 1},
 'pink': {'eyes': 1},
 'eyes': {'ran': 1,
  'remembered': 1,
  'see': 2,
  'filled': 1,
  'said': 1,
  'anxiously': 1,
  'feebly': 1,
  'half': 2,
  'immediately': 1,
  'like': 1,
  'nearly': 2,
  'getting': 2,
  'wide': 1,
  'course': 1,
  '.': 3,
  'time': 1,
  'appeared': 1,
  'watched': 1,
  'full': 1,
  'mouths': 1,
  'looking': 1,
  'still': 1,
  'bright': 1},
 'ran': {'close': 1,
  'across': 1,
  'speed': 1,
  'direction': 1,
  '.': 1,
  'house': 1,
  'hard': 1,
  'round': 1,
  'till': 1,
  'alice': 1,
  'away': 1,
  'wildly': 1,
  'gryphon': 1,
  'faster': 1,
  'thinking': 1,
  'well': 1},
 'close': {'.': 1,
  'behind': 3,
  'dripping': 1,
  'saying': 1,
  'nearly': 1,
  'little': 1,
  'ear': 2,
  'first': 1,
  'waving': 1,
  'one': 1},
 '.': {'</s>': 954, '?': 13},
 'remarkable': {'alice': 1, 'sensation': 1},
 'think': {'much': 1,
  'stopping': 1,
  'nothing': 3,
  'home': 1,
  'see': 1,
  'rather': 1,
  'could': 3,
  'asking': 1,
  'dinah': 1,
  'things': 1,
  'got': 1,
  'remember': 1,
  'likely': 1,
  'take': 1,
  'anything': 1,
  '?': 2,
  'oh': 1,
  'alice': 1,
  'kick': 1,
  'best': 1,
  'must': 1,
  'feel': 1,
  'ought': 1,
  'good': 2,
  'changed': 1,
  'age': 1,
  'listen': 1,
  'work': 1,
  'twelve': 1,
  'creature': 1,
  '.': 1,
  'proved': 1,
  'find': 1,
  'might': 1,
  'said': 4,
  'talk': 1,
  'may': 1,
  'pity': 1,
  'enough': 1,
  'play': 1,
  'glad': 1,
  'understand': 1,
  'better': 1,
  'would': 1},
 'much': {'way': 2,
  'to-night': 1,
  'matter': 1,
  'larger': 1,
  'bottle': 1,
  'surprised': 2,
  'could': 2,
  'said': 5,
  'accustomed': 1,
  'know': 1,
  'frightened': 2,
  'sooner': 1,
  'alas': 1,
  'pleasanter': 1,
  'right': 2,
  'contradicted': 1,
  'serpents': 1,
  'run': 1,
  'pepper': 1,
  'air': 1,
  'already': 1,
  'like': 2,
  'care': 1,
  'interesting': 1,
  'farther': 1,
  '.': 1,
  'went': 1,
  'muchness': 1,
  'confused': 1,
  'would': 1,
  'first': 1,
  'thought': 1,
  'pleased': 1,
  'thing': 1,

In [68]:
data = [{'Input': context, 'output': next, 'freq': freq}
        for context, nextFreq in biModel.items()
        for next, freq in nextFreq.items()]

freqbi = pd.DataFrame(data)
freqbi

             Input       output  freq
0              <s>  rabbit-hole     2
1              <s>  considering     1
2              <s>      nothing     8
3              <s>      another     4
4              <s>       either     1
...            ...          ...   ...
10286      sorrows         find     1
10287         joys  remembering     1
10288  remembering   child-life     1
10289   child-life        happy     1
10290        happy       summer     1

[10291 rows x 3 columns]

In [69]:
trigram = []
for segment in segments:
  words = ['<s>'] + word_tokenize(segment) + ['</s>']
  trigram.append(list(trigrams(words)))

In [70]:
trigram

[[('<s>', 'rabbit-hole', 'alice'),
  ('rabbit-hole', 'alice', 'beginning'),
  ('alice', 'beginning', 'get'),
  ('beginning', 'get', 'tired'),
  ('get', 'tired', 'sitting'),
  ('tired', 'sitting', 'sister'),
  ('sitting', 'sister', 'bank'),
  ('sister', 'bank', 'nothing'),
  ('bank', 'nothing', 'twice'),
  ('nothing', 'twice', 'peeped'),
  ('twice', 'peeped', 'book'),
  ('peeped', 'book', 'sister'),
  ('book', 'sister', 'reading'),
  ('sister', 'reading', 'pictures'),
  ('reading', 'pictures', 'conversations'),
  ('pictures', 'conversations', 'use'),
  ('conversations', 'use', 'book'),
  ('use', 'book', 'thought'),
  ('book', 'thought', 'alice'),
  ('thought', 'alice', 'without'),
  ('alice', 'without', 'pictures'),
  ('without', 'pictures', 'conversations'),
  ('pictures', 'conversations', '?'),
  ('conversations', '?', '</s>')],
 [('<s>', 'considering', 'mind'),
  ('considering', 'mind', 'well'),
  ('mind', 'well', 'could'),
  ('well', 'could', 'hot'),
  ('could', 'hot', 'day'),
  ('hot', 'day', 'made'),
  ('day', 'made', 'feel'),
  ('made', 'feel', 'sleepy'),
  ('feel', 'sleepy', 'stupid'),
  ('sleepy', 'stupid', 'whether'),
  ('stupid', 'whether', 'pleasure'),
  ('whether', 'pleasure', 'making'),
  ('pleasure', 'making', 'daisy-chain'),
  ('making', 'daisy-chain', 'would'),
  ('daisy-chain', 'would', 'worth'),
  ('would', 'worth', 'trouble'),
  ('worth', 'trouble', 'getting'),
  ('trouble', 'getting', 'picking'),
  ('getting', 'picking', 'daisies'),
  ('picking', 'daisies', 'suddenly'),
  ('daisies', 'suddenly', 'white'),
  ('suddenly', 'white', 'rabbit'),
  ('white', 'rabbit', 'pink'),
  ('rabbit', 'pink', 'eyes'),
  ('pink', 'eyes', 'ran'),
  ('eyes', 'ran', 'close'),
  ('ran', 'close', '.'),
  ('close', '.', '</s>')],
 [('<s>', 'nothing', 'remarkable'),
  ('nothing', 'remarkable', 'alice'),
  ('remarkable', 'alice', 'think'),
  ('alice', 'think', 'much'),
  ('think', 'much', 'way'),
  ('much', 'way', 'hear'),
  ('way', 'hear', 'rabbit'),
  ('hear', 'rabbit', 'say'),
  ('rabbit', 'say', 'oh'),
  ('say', 'oh', 'dear'),
  ('oh', 'dear', 'oh'),
  ('dear', 'oh', 'dear'),
  ('oh', 'dear', 'shall'),
  ('dear', 'shall', 'late'),
  ('shall', 'late', 'thought'),
  ('late', 'thought', 'afterwards'),
  ('thought', 'afterwards', 'occurred'),
  ('afterwards', 'occurred', 'ought'),
  ('occurred', 'ought', 'wondered'),
  ('ought', 'wondered', 'time'),
  ('wondered', 'time', 'seemed'),
  ('time', 'seemed', 'quite'),
  ('seemed', 'quite', 'natural'),
  ('quite', 'natural', 'rabbit'),
  ('natural', 'rabbit', 'actually'),
  ('rabbit', 'actually', 'took'),
  ('actually', 'took', 'watch'),
  ('took', 'watch', 'waistcoat-pocket'),
  ('watch', 'waistcoat-pocket', 'looked'),
  ('waistcoat-pocket', 'looked', 'hurried'),
  ('looked', 'hurried', 'alice'),
  ('hurried', 'alice', 'started'),
  ('alice', 'started', 'feet'),
  ('started', 'feet', 'flashed'),
  ('feet', 'flashed', 'across'),
  ('flashed', 'across', 'mind'),
  ('across', 'mind', 'never'),
  ('mind', 'never', 'seen'),
  ('never', 'seen', 'rabbit'),
  ('seen', 'rabbit', 'either'),
  ('rabbit', 'either', 'waistcoat-pocket'),
  ('either', 'waistcoat-pocket', 'watch'),
  ('waistcoat-pocket', 'watch', 'take'),
  ('watch', 'take', 'burning'),
  ('take', 'burning', 'curiosity'),
  ('burning', 'curiosity', 'ran'),
  ('curiosity', 'ran', 'across'),
  ('ran', 'across', 'field'),
  ('across', 'field', 'fortunately'),
  ('field', 'fortunately', 'time'),
  ('fortunately', 'time', 'see'),
  ('time', 'see', 'pop'),
  ('see', 'pop', 'large'),
  ('pop', 'large', 'rabbit-hole'),
  ('large', 'rabbit-hole', 'hedge'),
  ('rabbit-hole', 'hedge', '.'),
  ('hedge', '.', '</s>')],
 [('<s>', 'another', 'moment'),
  ('another', 'moment', 'went'),
  ('moment', 'went', 'alice'),
  ('went', 'alice', 'never'),
  ('alice', 'never', 'considering'),
  ('never', 'considering', 'world'),
  ('considering', 'world', 'get'),
  ('world', 'get', '.'),
  ('get', '.', '</s>')],
 [('<s>', 'rabbit-hole', 'went'),
  ('rabbit-hole', 'went', 'straight'),
  ('went', 'straight', 'like'),
  ('straight', 'like', 'tunnel'),
  ('like', 'tunnel', 'way'),
  ('tunnel', 'way', 'dipped'),
  ('way', 'dipped', 'suddenly'),
  ('dipped', 'suddenly', 'suddenly'),
  ('suddenly', 'suddenly', 'alice'),
  ('suddenly', 'alice', 'moment'),
  ('alice', 'moment', 'think'),
  ('moment', 'think', 'stopping'),
  ('think', 'stopping', 'found'),
  ('stopping', 'found', 'falling'),
  ('found', 'falling', 'deep'),
  ('falling', 'deep', 'well'),
  ('deep', 'well', '.'),
  ('well', '.', '</s>')],
 [('<s>', 'either', 'well'),
  ('either', 'well', 'deep'),
  ('well', 'deep', 'fell'),
  ('deep', 'fell', 'slowly'),
  ('fell', 'slowly', 'plenty'),
  ('slowly', 'plenty', 'time'),
  ('plenty', 'time', 'went'),
  ('time', 'went', 'look'),
  ('went', 'look', 'wonder'),
  ('look', 'wonder', 'going'),
  ('wonder', 'going', 'happen'),
  ('going', 'happen', 'next'),
  ('happen', 'next', '.'),
  ('next', '.', '</s>')],
 [('<s>', 'first', 'tried'),
  ('first', 'tried', 'look'),
  ('tried', 'look', 'make'),
  ('look', 'make', 'coming'),
  ('make', 'coming', 'dark'),
  ('coming', 'dark', 'see'),
  ('dark', 'see', 'anything'),
  ('see', 'anything', 'looked'),
  ('anything', 'looked', 'sides'),
  ('looked', 'sides', 'well'),
  ('sides', 'well', 'noticed'),
  ('well', 'noticed', 'filled'),
  ('noticed', 'filled', 'cupboards'),
  ('filled', 'cupboards', 'book-shelves'),
  ('cupboards', 'book-shelves', 'saw'),
  ('book-shelves', 'saw', 'maps'),
  ('saw', 'maps', 'pictures'),
  ('maps', 'pictures', 'hung'),
  ('pictures', 'hung', 'upon'),
  ('hung', 'upon', 'pegs'),
  ('upon', 'pegs', '.'),
  ('pegs', '.', '</s>')],
 [('<s>', 'took', 'jar'),
  ('took', 'jar', 'one'),
  ('jar', 'one', 'shelves'),
  ('one', 'shelves', 'passed'),
  ('shelves', 'passed', 'labelled'),
  ('passed', 'labelled', 'orange'),
  ('labelled', 'orange', 'marmalade'),
  ('orange', 'marmalade', 'great'),
  ('marmalade', 'great', 'disappointment'),
  ('great', 'disappointment', 'empty'),
  ('disappointment', 'empty', 'like'),
  ('empty', 'like', 'drop'),
  ('like', 'drop', 'jar'),
  ('drop', 'jar', 'fear'),
  ('jar', 'fear', 'killing'),
  ('fear', 'killing', 'somebody'),
  ('killing', 'somebody', 'underneath'),
  ('somebody', 'underneath', 'managed'),
  ('underneath', 'managed', 'put'),
  ('managed', 'put', 'one'),
  ('put', 'one', 'cupboards'),
  ('one', 'cupboards', 'fell'),
  ('cupboards', 'fell', 'past'),
  ('fell', 'past', '.'),
  ('past', '.', '</s>')],
 [('<s>', 'well', 'thought'),
  ('well', 'thought', 'alice'),
  ('thought', 'alice', 'fall'),
  ('alice', 'fall', 'shall'),
  ('fall', 'shall', 'think'),
  ('shall', 'think', 'nothing'),
  ('think', 'nothing', 'tumbling'),
  ('nothing', 'tumbling', 'stairs'),
  ('tumbling', 'stairs', 'brave'),
  ('stairs', 'brave', 'think'),
  ('brave', 'think', 'home'),
  ('think', 'home', 'say'),
  ('home', 'say', 'anything'),
  ('say', 'anything', 'even'),
  ('anything', 'even', 'fell'),
  ('even', 'fell', 'top'),
  ('fell', 'top', 'house'),
  ('top', 'house', 'likely'),
  ('house', 'likely', 'true'),
  ('likely', 'true', '..'),
  ('true', '..', 'would'),
  ('..', 'would', 'fall'),
  ('would', 'fall', 'never'),
  ('fall', 'never', 'come'),
  ('never', 'come', 'end'),
  ('come', 'end', '?'),
  ('end', '?', '</s>')],
 [('<s>', 'wonder', 'many'),
  ('wonder', 'many', 'miles'),
  ('many', 'miles', 'fallen'),
  ('miles', 'fallen', 'time'),
  ('fallen', 'time', '?'),
  ('time', '?', '</s>')],
 [('<s>', 'said', 'aloud'), ('said', 'aloud', '.'), ('aloud', '.', '</s>')],
 [('<s>', 'must', 'getting'),
  ('must', 'getting', 'somewhere'),
  ('getting', 'somewhere', 'near'),
  ('somewhere', 'near', 'centre'),
  ('near', 'centre', 'earth'),
  ('centre', 'earth', '.'),
  ('earth', '.', '</s>')],
 [('<s>', 'let', 'see'),
  ('let', 'see', 'would'),
  ('see', 'would', 'four'),
  ('would', 'four', 'thousand'),
  ('four', 'thousand', 'miles'),
  ('thousand', 'miles', 'think'),
  ('miles', 'think', 'see'),
  ('think', 'see', 'alice'),
  ('see', 'alice', 'learnt'),
  ('alice', 'learnt', 'several'),
  ('learnt', 'several', 'things'),
  ('several', 'things', 'sort'),
  ('things', 'sort', 'lessons'),
  ('sort', 'lessons', 'schoolroom'),
  ('lessons', 'schoolroom', 'though'),
  ('schoolroom', 'though', 'good'),
  ('though', 'good', 'opportunity'),
  ('good', 'opportunity', 'showing'),
  ('opportunity', 'showing', 'knowledge'),
  ('showing', 'knowledge', 'one'),
  ('knowledge', 'one', 'listen'),
  ('one', 'listen', 'still'),
  ('listen', 'still', 'good'),
  ('still', 'good', 'practice'),
  ('good', 'practice', 'say'),
  ('practice', 'say', 'yes'),
  ('say', 'yes', 'right'),
  ('yes', 'right', 'distance'),
  ('right', 'distance', 'wonder'),
  ('distance', 'wonder', 'latitude'),
  ('wonder', 'latitude', 'longitude'),
  ('latitude', 'longitude', 'got'),
  ('longitude', 'got', '?'),
  ('got', '?', '</s>')],
 [('<s>', 'alice', 'idea'),
  ('alice', 'idea', 'latitude'),
  ('idea', 'latitude', 'longitude'),
  ('latitude', 'longitude', 'either'),
  ('longitude', 'either', 'thought'),
  ('either', 'thought', 'nice'),
  ('thought', 'nice', 'grand'),
  ('nice', 'grand', 'words'),
  ('grand', 'words', 'say'),
  ('words', 'say', '.'),
  ('say', '.', '</s>')],
 [('<s>', 'presently', 'began'),
  ('presently', 'began', '.'),
  ('began', '.', '</s>')],
 [('<s>', 'wonder', 'shall'),
  ('wonder', 'shall', 'fall'),
  ('shall', 'fall', 'right'),
  ('fall', 'right', 'earth'),
  ('right', 'earth', 'funny'),
  ('earth', 'funny', 'seem'),
  ('funny', 'seem', 'come'),
  ('seem', 'come', 'among'),
  ('come', 'among', 'people'),
  ('among', 'people', 'walk'),
  ('people', 'walk', 'heads'),
  ('walk', 'heads', 'downward'),
  ('heads', 'downward', 'antipathies'),
  ('downward', 'antipathies', 'think'),
  ('antipathies', 'think', 'rather'),
  ('think', 'rather', 'glad'),
  ('rather', 'glad', 'one'),
  ('glad', 'one', 'listening'),
  ('one', 'listening', 'time'),
  ('listening', 'time', 'sound'),
  ('time', 'sound', 'right'),
  ('sound', 'right', 'word'),
  ('right', 'word', 'shall'),
  ('word', 'shall', 'ask'),
  ('shall', 'ask', 'name'),
  ('ask', 'name', 'country'),
  ('name', 'country', 'know'),
  ('country', 'know', '.'),
  ('know', '.', '</s>')],
 [('<s>', 'please', 'new'),
  ('please', 'new', 'zealand'),
  ('new', 'zealand', 'australia'),
  ('zealand', 'australia', '?'),
  ('australia', '?', '</s>')],
 [('<s>', 'tried', 'curtsey'),
  ('tried', 'curtsey', 'spoke'),
  ('curtsey', 'spoke', 'fancy'),
  ('spoke', 'fancy', 'curtseying'),
  ('fancy', 'curtseying', 'falling'),
  ('curtseying', 'falling', 'air'),
  ('falling', 'air', 'think'),
  ('air', 'think', 'could'),
  ('think', 'could', 'manage'),
  ('could', 'manage', '?'),
  ('manage', '?', '</s>')],
 [('<s>', 'ignorant', 'little'),
  ('ignorant', 'little', 'girl'),
  ('little', 'girl', 'think'),
  ('girl', 'think', 'asking'),
  ('think', 'asking', 'never'),
  ('asking', 'never', 'ask'),
  ('never', 'ask', 'perhaps'),
  ('ask', 'perhaps', 'shall'),
  ('perhaps', 'shall', 'see'),
  ('shall', 'see', 'written'),
  ('see', 'written', 'somewhere'),
  ('written', 'somewhere', '..'),
  ('somewhere', '..', 'nothing'),
  ('..', 'nothing', 'else'),
  ('nothing', 'else', 'alice'),
  ('else', 'alice', 'soon'),
  ('alice', 'soon', 'began'),
  ('soon', 'began', 'talking'),
  ('began', 'talking', '.'),
  ('talking', '.', '</s>')],
 [('<s>', 'dinah', 'miss'),
  ('dinah', 'miss', 'much'),
  ('miss', 'much', 'to-night'),
  ('much', 'to-night', 'think'),
  ('to-night', 'think', 'dinah'),
  ('think', 'dinah', 'cat'),
  ('dinah', 'cat', '.'),
  ('cat', '.', '</s>')],
 [('<s>', 'hope', 'remember'),
  ('hope', 'remember', 'saucer'),
  ('remember', 'saucer', 'milk'),
  ('saucer', 'milk', 'tea-time'),
  ('milk', 'tea-time', '.'),
  ('tea-time', '.', '</s>')],
 [('<s>', 'dinah', 'dear'),
  ('dinah', 'dear', 'wish'),
  ('dear', 'wish', 'mice'),
  ('wish', 'mice', 'air'),
  ('mice', 'air', 'afraid'),
  ('air', 'afraid', 'might'),
  ('afraid', 'might', 'catch'),
  ('might', 'catch', 'bat'),
  ('catch', 'bat', 'like'),
  ('bat', 'like', 'mouse'),
  ('like', 'mouse', 'know'),
  ('mouse', 'know', '.'),
  ('know', '.', '</s>')],
 [('<s>', 'cats', 'eat'),
  ('cats', 'eat', 'bats'),
  ('eat', 'bats', 'wonder'),
  ('bats', 'wonder', '?'),
  ('wonder', '?', '</s>')],
 [('<s>', 'alice', 'began'),
  ('alice', 'began', 'get'),
  ('began', 'get', 'rather'),
  ('get', 'rather', 'sleepy'),
  ('rather', 'sleepy', 'went'),
  ('sleepy', 'went', 'saying'),
  ('went', 'saying', 'dreamy'),
  ('saying', 'dreamy', 'sort'),
  ('dreamy', 'sort', 'way'),
  ('sort', 'way', 'cats'),
  ('way', 'cats', 'eat'),
  ('cats', 'eat', 'bats'),
  ('eat', 'bats', '?'),
  ('bats', '?', '</s>')],
 [('<s>', 'cats', 'eat'),
  ('cats', 'eat', 'bats'),
  ('eat', 'bats', '?'),
  ('bats', '?', '</s>')],
 [('<s>', 'sometimes', 'bats'),
  ('sometimes', 'bats', 'eat'),
  ('bats', 'eat', 'cats'),
  ('eat', 'cats', '?'),
  ('cats', '?', '</s>')],
 [('<s>', 'see', 'answer'),
  ('see', 'answer', 'either'),
  ('answer', 'either', 'question'),
  ('either', 'question', 'much'),
  ('question', 'much', 'matter'),
  ('much', 'matter', 'way'),
  ('matter', 'way', 'put'),
  ('way', 'put', '.'),
  ('put', '.', '</s>')],
 [('<s>', 'felt', 'dozing'),
  ('felt', 'dozing', 'begun'),
  ('dozing', 'begun', 'dream'),
  ('begun', 'dream', 'walking'),
  ('dream', 'walking', 'hand'),
  ('walking', 'hand', 'hand'),
  ('hand', 'hand', 'dinah'),
  ('hand', 'dinah', 'saying'),
  ('dinah', 'saying', 'earnestly'),
  ('saying', 'earnestly', 'dinah'),
  ('earnestly', 'dinah', 'tell'),
  ('dinah', 'tell', 'truth'),
  ('tell', 'truth', 'ever'),
  ('truth', 'ever', 'eat'),
  ('ever', 'eat', 'bat'),
  ('eat', 'bat', '?'),
  ('bat', '?', '</s>')],
 [('<s>', 'suddenly', 'thump'),
  ('suddenly', 'thump', 'thump'),
  ('thump', 'thump', 'came'),
  ('thump', 'came', 'upon'),
  ('came', 'upon', 'heap'),
  ('upon', 'heap', 'sticks'),
  ('heap', 'sticks', 'dry'),
  ('sticks', 'dry', 'leaves'),
  ('dry', 'leaves', 'fall'),
  ('leaves', 'fall', '.'),
  ('fall', '.', '</s>')],
 [('<s>', 'alice', 'bit'),
  ('alice', 'bit', 'hurt'),
  ('bit', 'hurt', 'jumped'),
  ('hurt', 'jumped', 'feet'),
  ('jumped', 'feet', 'moment'),
  ('feet', 'moment', 'looked'),
  ('moment', 'looked', 'dark'),
  ('looked', 'dark', 'overhead'),
  ('dark', 'overhead', 'another'),
  ('overhead', 'another', 'long'),
  ('another', 'long', 'passage'),
  ('long', 'passage', 'white'),
  ('passage', 'white', 'rabbit'),
  ('white', 'rabbit', 'still'),
  ('rabbit', 'still', 'sight'),
  ('still', 'sight', 'hurrying'),
  ('sight', 'hurrying', '.'),
  ('hurrying', '.', '</s>')],
 [('<s>', 'moment', 'lost'),
  ('moment', 'lost', 'away'),
  ('lost', 'away', 'went'),
  ('away', 'went', 'alice'),
  ('went', 'alice', 'like'),
  ('alice', 'like', 'wind'),
  ('like', 'wind', 'time'),
  ('wind', 'time', 'hear'),
  ('time', 'hear', 'say'),
  ('hear', 'say', 'turned'),
  ('say', 'turned', 'corner'),
  ('turned', 'corner', 'oh'),
  ('corner', 'oh', 'ears'),
  ('oh', 'ears', 'whiskers'),
  ('ears', 'whiskers', 'late'),
  ('whiskers', 'late', 'getting'),
  ('late', 'getting', 'close'),
  ('getting', 'close', 'behind'),
  ('close', 'behind', 'turned'),
  ('behind', 'turned', 'corner'),
  ('turned', 'corner', 'rabbit'),
  ('corner', 'rabbit', 'longer'),
  ('rabbit', 'longer', 'seen'),
  ('longer', 'seen', 'found'),
  ('seen', 'found', 'long'),
  ('found', 'long', 'low'),
  ('long', 'low', 'hall'),
  ('low', 'hall', 'lit'),
  ('hall', 'lit', 'row'),
  ('lit', 'row', 'lamps'),
  ('row', 'lamps', 'hanging'),
  ('lamps', 'hanging', 'roof'),
  ('hanging', 'roof', '.'),
  ('roof', '.', '</s>')],
 [('<s>', 'doors', 'round'),
  ('doors', 'round', 'hall'),
  ('round', 'hall', 'locked'),
  ('hall', 'locked', 'alice'),
  ('locked', 'alice', 'way'),
  ('alice', 'way', 'one'),
  ('way', 'one', 'side'),
  ('one', 'side', 'trying'),
  ('side', 'trying', 'every'),
  ('trying', 'every', 'door'),
  ('every', 'door', 'walked'),
  ('door', 'walked', 'sadly'),
  ('walked', 'sadly', 'middle'),
  ('sadly', 'middle', 'wondering'),
  ('middle', 'wondering', 'ever'),
  ('wondering', 'ever', 'get'),
  ('ever', 'get', '.'),
  ('get', '.', '</s>')],
 [('<s>', 'suddenly', 'came'),
  ('suddenly', 'came', 'upon'),
  ('came', 'upon', 'little'),
  ('upon', 'little', 'three-legged'),
  ('little', 'three-legged', 'table'),
  ('three-legged', 'table', 'made'),
  ('table', 'made', 'solid'),
  ('made', 'solid', 'glass'),
  ('solid', 'glass', 'nothing'),
  ('glass', 'nothing', 'except'),
  ('nothing', 'except', 'tiny'),
  ('except', 'tiny', 'golden'),
  ('tiny', 'golden', 'key'),
  ('golden', 'key', 'alice'),
  ('key', 'alice', 'first'),
  ('alice', 'first', 'thought'),
  ('first', 'thought', 'might'),
  ('thought', 'might', 'belong'),
  ('might', 'belong', 'one'),
  ('belong', 'one', 'doors'),
  ('one', 'doors', 'hall'),
  ('doors', 'hall', 'alas'),
  ('hall', 'alas', 'either'),
  ('alas', 'either', 'locks'),
  ('either', 'locks', 'large'),
  ('locks', 'large', 'key'),
  ('large', 'key', 'small'),
  ('key', 'small', 'rate'),
  ('small', 'rate', 'would'),
  ('rate', 'would', 'open'),
  ('would', 'open', '.'),
  ('open', '.', '</s>')],
 [('<s>', 'however', 'second'),
  ('however', 'second', 'time'),
  ('second', 'time', 'round'),
  ('time', 'round', 'came'),
  ('round', 'came', 'upon'),
  ('came', 'upon', 'low'),
  ('upon', 'low', 'curtain'),
  ('low', 'curtain', 'noticed'),
  ('curtain', 'noticed', 'behind'),
  ('noticed', 'behind', 'little'),
  ('behind', 'little', 'door'),
  ('little', 'door', 'fifteen'),
  ('door', 'fifteen', 'inches'),
  ('fifteen', 'inches', 'high'),
  ('inches', 'high', 'tried'),
  ('high', 'tried', 'little'),
  ('tried', 'little', 'golden'),
  ('little', 'golden', 'key'),
  ('golden', 'key', 'lock'),
  ('key', 'lock', 'great'),
  ('lock', 'great', 'delight'),
  ('great', 'delight', 'fitted'),
  ('delight', 'fitted', 'alice'),
  ('fitted', 'alice', 'opened'),
  ('alice', 'opened', 'door'),
  ('opened', 'door', 'found'),
  ('door', 'found', 'led'),
  ('found', 'led', 'small'),
  ('led', 'small', 'passage'),
  ('small', 'passage', 'much'),
  ('passage', 'much', 'larger'),
  ('much', 'larger', 'rat-hole'),
  ('larger', 'rat-hole', 'knelt'),
  ('rat-hole', 'knelt', 'looked'),
  ('knelt', 'looked', 'along'),
  ('looked', 'along', 'passage'),
  ('along', 'passage', 'loveliest'),
  ('passage', 'loveliest', 'garden'),
  ('loveliest', 'garden', 'ever'),
  ('garden', 'ever', 'saw'),
  ('ever', 'saw', '.'),
  ('saw', '.', '</s>')],
 [('<s>', 'longed', 'get'),
  ('longed', 'get', 'dark'),
  ('get', 'dark', 'hall'),
  ('dark', 'hall', 'wander'),
  ('hall', 'wander', 'among'),
  ('wander', 'among', 'beds'),
  ('among', 'beds', 'bright'),
  ('beds', 'bright', 'flowers'),
  ('bright', 'flowers', 'cool'),
  ('flowers', 'cool', 'fountains'),
  ('cool', 'fountains', 'could'),
  ('fountains', 'could', 'even'),
  ('could', 'even', 'get'),
  ('even', 'get', 'head'),
  ('get', 'head', 'doorway'),
  ('head', 'doorway', 'even'),
  ('doorway', 'even', 'head'),
  ('even', 'head', 'would'),
  ('head', 'would', 'go'),
  ('would', 'go', 'thought'),
  ('go', 'thought', 'poor'),
  ('thought', 'poor', 'alice'),
  ('poor', 'alice', 'would'),
  ('alice', 'would', 'little'),
  ('would', 'little', 'use'),
  ('little', 'use', 'without'),
  ('use', 'without', 'shoulders'),
  ('without', 'shoulders', '.'),
  ('shoulders', '.', '</s>')],
 [('<s>', 'oh', 'wish'),
  ('oh', 'wish', 'could'),
  ('wish', 'could', 'shut'),
  ('could', 'shut', 'like'),
  ('shut', 'like', 'telescope'),
  ('like', 'telescope', 'think'),
  ('telescope', 'think', 'could'),
  ('think', 'could', 'knew'),
  ('could', 'knew', 'begin'),
  ('knew', 'begin', '.'),
  ('begin', '.', '</s>')],
 [('<s>', 'see', 'many'),
  ('see', 'many', 'out-of-the-way'),
  ('many', 'out-of-the-way', 'things'),
  ('out-of-the-way', 'things', 'happened'),
  ('things', 'happened', 'lately'),
  ('happened', 'lately', 'alice'),
  ('lately', 'alice', 'begun'),

In [71]:
triModel = {}

for tri in trigram:
  for t in tri:
    context = (t[0], t[1])
    next = t[2]
    if context not in triModel:
      triModel[context] = {}

    if next not in triModel[context]:
        triModel[context][next] = 1
    else:
        triModel[context][next] += 1

In [72]:
triModel

{('<s>', 'rabbit-hole'): {'alice': 1, 'went': 1},
 ('rabbit-hole', 'alice'): {'beginning': 1},
 ('alice', 'beginning'): {'get': 1, 'see': 1, 'think': 1, 'angrily': 1},
 ('beginning', 'get'): {'tired': 1},
 ('get', 'tired'): {'sitting': 1},
 ('tired', 'sitting'): {'sister': 1},
 ('sitting', 'sister'): {'bank': 1},
 ('sister', 'bank'): {'nothing': 1},
 ('bank', 'nothing'): {'twice': 1},
 ('nothing', 'twice'): {'peeped': 1},
 ('twice', 'peeped'): {'book': 1},
 ('peeped', 'book'): {'sister': 1},
 ('book', 'sister'): {'reading': 1},
 ('sister', 'reading'): {'pictures': 1},
 ('reading', 'pictures'): {'conversations': 1},
 ('pictures', 'conversations'): {'use': 1, '?': 1},
 ('conversations', 'use'): {'book': 1},
 ('use', 'book'): {'thought': 1},
 ('book', 'thought'): {'alice': 1},
 ('thought', 'alice'): {'without': 1,
  'fall': 1,
  'perhaps': 1,
  'speak': 1,
  'daresay': 1,
  'shall': 1,
  'waiting': 1,
  '.': 8,
  'well': 1,
  'long': 1,
  'never': 1,
  'sure': 1,
  'went': 2,
  'grin': 1,
  'asleep': 1,
  'arches': 1,
  'might': 1,
  'twelve': 1},
 ('alice', 'without'): {'pictures': 1},
 ('without', 'pictures'): {'conversations': 1},
 ('conversations', '?'): {'</s>': 1},
 ('<s>', 'considering'): {'mind': 1},
 ('considering', 'mind'): {'well': 1},
 ('mind', 'well'): {'could': 1},
 ('well', 'could'): {'hot': 1,
  '.': 2,
  'neck': 1,
  'sneezing': 1,
  'remember': 1},
 ('could', 'hot'): {'day': 1},
 ('hot', 'day'): {'made': 1},
 ('day', 'made'): {'feel': 1},
 ('made', 'feel'): {'sleepy': 1},
 ('feel', 'sleepy'): {'stupid': 1},
 ('sleepy', 'stupid'): {'whether': 1},
 ('stupid', 'whether'): {'pleasure': 1},
 ('whether', 'pleasure'): {'making': 1},
 ('pleasure', 'making'): {'daisy-chain': 1},
 ('making', 'daisy-chain'): {'would': 1},
 ('daisy-chain', 'would'): {'worth': 1},
 ('would', 'worth'): {'trouble': 1},
 ('worth', 'trouble'): {'getting': 1},
 ('trouble', 'getting'): {'picking': 1},
 ('getting', 'picking'): {'daisies': 1},
 ('picking', 'daisies'): {'suddenly': 1},
 ('daisies', 'suddenly'): {'white': 1},
 ('suddenly', 'white'): {'rabbit': 1},
 ('white', 'rabbit'): {'pink': 1,
  'still': 1,
  'returning': 1,
  'trotting': 1,
  'talking': 1,
  'peeping': 1,
  '.': 1,
  'trumpet': 1,
  'cried': 1,
  'blew': 2,
  'said': 1,
  'fumbled': 1,
  'read': 2,
  'interrupted': 1,
  'jumping': 1,
  'seems': 1,
  'fact': 1,
  'queerest': 1,
  'put': 1,
  'hurried': 1},
 ('rabbit', 'pink'): {'eyes': 1},
 ('pink', 'eyes'): {'ran': 1},
 ('eyes', 'ran'): {'close': 1},
 ('ran', 'close'): {'.': 1},
 ('close', '.'): {'</s>': 1},
 ('<s>', 'nothing'): {'remarkable': 1,
  'yet': 1,
  'could': 1,
  'said': 1,
  'whatever': 2,
  'clearer': 1,
  'pack': 1},
 ('nothing', 'remarkable'): {'alice': 1},
 ('remarkable', 'alice'): {'think': 1},
 ('alice', 'think'): {'much': 1, 'proved': 1, 'pity': 1},
 ('think', 'much'): {'way': 1},
 ('much', 'way'): {'hear': 1, 'expecting': 1},
 ('way', 'hear'): {'rabbit': 1},
 ('hear', 'rabbit'): {'say': 1},
 ('rabbit', 'say'): {'oh': 1, 'barrowful': 1},
 ('say', 'oh'): {'dear': 1},
 ('oh', 'dear'): {'oh': 1,
  'shall': 2,
  'nonsense': 1,
  'puzzling': 1,
  'cried': 2,
  'dinah': 1,
  'paws': 1,
  'nearly': 1},
 ('dear', 'oh'): {'dear': 1},
 ('dear', 'shall'): {'late': 1, 'never': 1, 'look': 1},
 ('shall', 'late'): {'thought': 1},
 ('late', 'thought'): {'afterwards': 1},
 ('thought', 'afterwards'): {'occurred': 1},
 ('afterwards', 'occurred'): {'ought': 1},
 ('occurred', 'ought'): {'wondered': 1},
 ('ought', 'wondered'): {'time': 1},
 ('wondered', 'time'): {'seemed': 1},
 ('time', 'seemed'): {'quite': 1},
 ('seemed', 'quite'): {'natural': 2, 'dull': 1},
 ('quite', 'natural'): {'rabbit': 1, 'alice': 1},
 ('natural', 'rabbit'): {'actually': 1},
 ('rabbit', 'actually'): {'took': 1},
 ('actually', 'took'): {'watch': 1},
 ('took', 'watch'): {'waistcoat-pocket': 1, 'looked': 1},
 ('watch', 'waistcoat-pocket'): {'looked': 1},
 ('waistcoat-pocket', 'looked'): {'hurried': 1},
 ('looked', 'hurried'): {'alice': 1},
 ('hurried', 'alice'): {'started': 1},
 ('alice', 'started'): {'feet': 1},
 ('started', 'feet'): {'flashed': 1},
 ('feet', 'flashed'): {'across': 1},
 ('flashed', 'across'): {'mind': 1},
 ('across', 'mind'): {'never': 1},
 ('mind', 'never'): {'seen': 1},
 ('never', 'seen'): {'rabbit': 1, 'curious': 1},
 ('seen', 'rabbit'): {'either': 1},
 ('rabbit', 'either'): {'waistcoat-pocket': 1},
 ('either', 'waistcoat-pocket'): {'watch': 1},
 ('waistcoat-pocket', 'watch'): {'take': 1},
 ('watch', 'take'): {'burning': 1},
 ('take', 'burning'): {'curiosity': 1},
 ('burning', 'curiosity'): {'ran': 1},
 ('curiosity', 'ran'): {'across': 1},
 ('ran', 'across'): {'field': 1},
 ('across', 'field'): {'fortunately': 1},
 ('field', 'fortunately'): {'time': 1},
 ('fortunately', 'time'): {'see': 1},
 ('time', 'see'): {'pop': 1},
 ('see', 'pop'): {'large': 1},
 ('pop', 'large'): {'rabbit-hole': 1},
 ('large', 'rabbit-hole'): {'hedge': 1},
 ('rabbit-hole', 'hedge'): {'.': 1},
 ('hedge', '.'): {'</s>': 1},
 ('<s>', 'another'): {'moment': 1, 'puzzling': 1, 'minute': 1, 'shore': 1},
 ('another', 'moment'): {'went': 1,
  'splash': 1,
  'sight': 1,
  'found': 1,
  'addressed': 1},
 ('moment', 'went'): {'alice': 1},
 ('went', 'alice'): {'never': 1, 'like': 1},
 ('alice', 'never'): {'considering': 1, 'come': 1, 'court': 1},
 ('never', 'considering'): {'world': 1},
 ('considering', 'world'): {'get': 1},
 ('world', 'get'): {'.': 1},
 ('get', '.'): {'</s>': 3},
 ('rabbit-hole', 'went'): {'straight': 1},
 ('went', 'straight'): {'like': 1},
 ('straight', 'like'): {'tunnel': 1},
 ('like', 'tunnel'): {'way': 1},
 ('tunnel', 'way'): {'dipped': 1},
 ('way', 'dipped'): {'suddenly': 1},
 ('dipped', 'suddenly'): {'suddenly': 1},
 ('suddenly', 'suddenly'): {'alice': 1},
 ('suddenly', 'alice'): {'moment': 1},
 ('alice', 'moment'): {'think': 1, 'appeared': 1},
 ('moment', 'think'): {'stopping': 1},
 ('think', 'stopping'): {'found': 1},
 ('stopping', 'found'): {'falling': 1},
 ('found', 'falling'): {'deep': 1},
 ('falling', 'deep'): {'well': 1},
 ('deep', 'well'): {'.': 1},
 ('well', '.'): {'</s>': 3},
 ('<s>', 'either'): {'well': 1},
 ('either', 'well'): {'deep': 1},
 ('well', 'deep'): {'fell': 1},
 ('deep', 'fell'): {'slowly': 1},
 ('fell', 'slowly'): {'plenty': 1},
 ('slowly', 'plenty'): {'time': 1},
 ('plenty', 'time'): {'went': 1},
 ('time', 'went'): {'look': 1, 'talking': 1},
 ('went', 'look'): {'wonder': 1},
 ('look', 'wonder'): {'going': 1},
 ('wonder', 'going'): {'happen': 1},
 ('going', 'happen'): {'next': 1},
 ('happen', 'next'): {'.': 3},
 ('next', '.'): {'</s>': 5},
 ('<s>', 'first'): {'tried': 1,
  'however': 1,
  'idea': 1,
  'sentence': 1,
  'question': 2,
  'marked': 1,
  'thing': 2,
  'side': 1,
  'perhaps': 1,
  'came': 1,
  'position': 1},
 ('first', 'tried'): {'look': 1},
 ('tried', 'look'): {'make': 1},
 ('look', 'make'): {'coming': 1},
 ('make', 'coming'): {'dark': 1},
 ('coming', 'dark'): {'see': 1},
 ('dark', 'see'): {'anything': 1},
 ('see', 'anything'): {'looked': 2},
 ('anything', 'looked'): {'sides': 1, 'like': 1},
 ('looked', 'sides'): {'well': 1, 'behind': 1},
 ('sides', 'well'): {'noticed': 1},
 ('well', 'noticed'): {'filled': 1},
 ('noticed', 'filled'): {'cupboards': 1},
 ('filled', 'cupboards'): {'book-shelves': 1},
 ('cupboards', 'book-shelves'): {'saw': 1},
 ('book-shelves', 'saw'): {'maps': 1},
 ('saw', 'maps'): {'pictures': 1},
 ('maps', 'pictures'): {'hung': 1},
 ('pictures', 'hung'): {'upon': 1},
 ('hung', 'upon'): {'pegs': 1},
 ('upon', 'pegs'): {'.': 1},
 ('pegs', '.'): {'</s>': 1},
 ('<s>', 'took'): {'jar': 1, 'housemaid': 1, 'regular': 1},
 ('took', 'jar'): {'one': 1},
 ('jar', 'one'): {'shelves': 1},
 ('one', 'shelves'): {'passed': 1},
 ('shelves', 'passed'): {'labelled': 1},
 ('passed', 'labelled'): {'orange': 1},
 ('labelled', 'orange'): {'marmalade': 1},
 ('orange', 'marmalade'): {'great': 1},
 ('marmalade', 'great'): {'disappointment': 1},
 ('great', 'disappointment'): {'empty': 1},
 ('disappointment', 'empty'): {'like': 1},
 ('empty', 'like'): {'drop': 1},
 ('like', 'drop'): {'jar': 1},
 ('drop', 'jar'): {'fear': 1},
 ('jar', 'fear'): {'killing': 1},
 ('fear', 'killing'): {'somebody': 1},
 ('killing', 'somebody'): {'underneath': 1},
 ('somebody', 'underneath'): {'managed': 1},
 ('underneath', 'managed'): {'put': 1},
 ('managed', 'put'): {'one': 1},
 ('put', 'one'): {'cupboards': 1, 'rabbit': 1, 'arm': 1},
 ('one', 'cupboards'): {'fell': 1},
 ('cupboards', 'fell'): {'past': 1},
 ('fell', 'past'): {'.': 1},
 ('past', '.'): {'</s>': 1},
 ('<s>', 'well'): {'thought': 1,
  'say': 1,
  'eat': 1,
  'perhaps': 3,
  'got': 1,
  'tried': 1,
  'like': 1,
  '?': 1,
  'said': 1,
  'cat': 1,
  'often': 1,
  'hardly': 1,
  'alice': 1,
  'must': 2,
  'gryphon': 1,
  'mystery': 1,
  'show': 1,
  'never': 1,
  'rate': 1,
  'go': 1},
 ('well', 'thought'): {'alice': 1},
 ('alice', 'fall'): {'shall': 1},
 ('fall', 'shall'): {'think': 1},
 ('shall', 'think'): {'nothing': 1},
 ('think', 'nothing'): {'tumbling': 1, 'better': 1, 'else': 1},
 ('nothing', 'tumbling'): {'stairs': 1},
 ('tumbling', 'stairs'): {'brave': 1},
 ('stairs', 'brave'): {'think': 1},
 ('brave', 'think'): {'home': 1},
 ('think', 'home'): {'say': 1},
 ('home', 'say'): {'anything': 1},
 ('say', 'anything'): {'even': 1, '.': 1},
 ('anything', 'even'): {'fell': 1},
 ('even', 'fell'): {'top': 1},
 ('fell', 'top'): {'house': 1},
 ('top', 'house'): {'likely': 1},
 ('house', 'likely'): {'true': 1},
 ('likely', 'true'): {'..': 1},
 ('true', '..'): {'would': 1},
 ('..', 'would'): {'fall': 1},
 ('would', 'fall'): {'never': 1},
 ('fall', 'never'): {'come': 1},
 ('never', 'come'): {'end': 1, 'upon': 1},
 ('come', 'end'): {'?': 1, 'stop': 1},
 ('end', '?'): {'</s>': 1},
 ('<s>', 'wonder'): {'many': 1,
  'shall': 1,
  'like': 1,
  'changed': 1,
  'next': 1},
 ('wonder', 'many'): {'miles': 1},
 ('many', 'miles'): {'fallen': 1},
 ('miles', 'fallen'): {'time': 1},
 ('fallen', 'time'): {'?': 1},
 ('time', '?'): {'</s>': 1},
 ('<s>', 'said'): {'aloud': 1,
  'lory': 2,
  'duck': 1,
  'alice': 23,
  'dodo': 1,
  'mouse': 1,
  'came': 2,
  'caterpillar': 8,
  'nibbled': 1,
  'pigeon': 1,
  'footman': 1,
  'duchess': 1,
  'last': 2,
  'cat': 4,
  'looked': 1,
  'pig': 1,
  'march': 4,
  'turning': 1,
  'one': 2,
  'knave': 1,
  'queen': 4,
  '?': 1,
  'king': 4,
  'gryphon': 4,
  'mock': 5,
  'whiting': 1,
  'dormouse': 1,
  'hatter': 1,
  'cook': 1,
  'white': 1,
  'could': 1,
  '.': 1},
 ('said', 'aloud'): {'.': 1},
 ('aloud', '.'): {'</s>': 3},
 ('<s>', 'must'): {'getting': 1,
  'go': 3,
  'growing': 1,
  'prize': 1,
  'burn': 1,
  'said': 2,
  'pretty': 1,
  'remember': 1,
  'imitated': 1,
  'meant': 1},
 ('must', 'getting'): {'somewhere': 1, 'home': 1},
 ('getting', 'somewhere'): {'near': 1},
 ('somewhere', 'near'): {'centre': 1},
 ('near', 'centre'): {'earth': 1},
 ('centre', 'earth'): {'.': 1},
 ('earth', '.'): {'</s>': 2},
 ('<s>', 'let'): {'see': 2, 'think': 1, 'alone': 1, 'go': 1, 'know': 1},
 ('let', 'see'): {'would': 1, 'give': 1, 'four': 1, 'managed': 1},
 ('see', 'would'): {'four': 1, 'happen': 1, 'deny': 1},
 ('would', 'four'): {'thousand': 1},
 ('four', 'thousand'): {'miles': 1},
 ('thousand', 'miles'): {'think': 1},
 ('miles', 'think'): {'see': 1},
 ('think', 'see'): {'alice': 1},
 ('see', 'alice'): {'learnt': 1},
 ('alice', 'learnt'): {'several': 1},
 ('learnt', 'several'): {'things': 1},
 ('several', 'things'): {'sort': 1},
 ('things', 'sort'): {'lessons': 1},
 ('sort', 'lessons'): {'schoolroom': 1},
 ('lessons', 'schoolroom'): {'though': 1},
 ('schoolroom', 'though'): {'good': 1},
 ('though', 'good'): {'opportunity': 1},
 ('good', 'opportunity'): {'showing': 1, 'making': 1, 'repeating': 1},
 ('opportunity', 'showing'): {'knowledge': 1, 'little': 1},
 ('showing', 'knowledge'): {'one': 1},
 ('knowledge', 'one'): {'listen': 1},
 ('one', 'listen'): {'still': 1},
 ('listen', 'still'): {'good': 1},
 ('still', 'good'): {'practice': 1},
 ('good', 'practice'): {'say': 1},
 ('practice', 'say'): {'yes': 1},
 ('say', 'yes'): {'right': 1},
 ('yes', 'right'): {'distance': 1},
 ('right', 'distance'): {'wonder': 1},
 ('distance', 'wonder'): {'latitude': 1},
 ('wonder', 'latitude'): {'longitude': 1},
 ('latitude', 'longitude'): {'got': 1, 'either': 1},
 ('longitude', 'got'): {'?': 1},
 ('got', '?'): {'</s>': 2},
 ('<s>', 'alice'): {'idea': 1,
  'began': 3,
  'bit': 1,
  'took': 1,
  'seaside': 1,
  'led': 1,
  'kept': 1,
  'thought': 6,
  'replied': 2,
  'guessed': 1,
  'knew': 1,
  'heard': 1,
  'noticed': 1,
  'looked': 5,
  'felt': 3,
  'folded': 1,
  'said': 3,
  'remained': 1,
  'crouched': 1,
  'laughed': 1,
  'went': 2,
  'like': 1,
  'caught': 1,
  'beginning': 1,
  'think': 1,
  'much': 2,
  'waited': 2,
  'hastily': 1,
  'considered': 1,
  'looking': 1,
  'sighed': 1,
  'asked': 3,
  'ventured': 1,
  'quite': 2,
  'wish': 1,
  'silent': 1,
  'rather': 1,
  'gave': 1,
  'could': 3,
  'glad': 1,
  'nearly': 1,
  'feel': 1,
  'thoroughly': 1,
  'dare': 1,
  'panted': 1,
  'never': 1,
  'whispered': 1,
  'evidence': 1,
  'got': 1},
 ('alice', 'idea'): {'latitude': 1, 'despair': 1},
 ('idea', 'latitude'): {'longitude': 1},
 ('longitude', 'either'): {'thought': 1},
 ('either', 'thought'): {'nice': 1},
 ('thought', 'nice'): {'grand': 1},
 ('nice', 'grand'): {'words': 1},
 ('grand', 'words'): {'say': 1},
 ('words', 'say'): {'.': 1},
 ('say', '.'): {'</s>': 4, '?': 1},
 ('<s>', 'presently'): {'began': 1, 'rabbit': 1},
 ('presently', 'began'): {'.': 1},
 ('began', '.'): {'</s>': 4},
 ('wonder', 'shall'): {'fall': 1, 'ever': 1},
 ('shall', 'fall'): {'right': 1},
 ('fall', 'right'): {'earth': 1},
 ('right', 'earth'): {'funny': 1},
 ('earth', 'funny'): {'seem': 1},
 ('funny', 'seem'): {'come': 1, 'sending': 1},
 ('seem', 'come'): {'among': 1},
 ('come', 'among'): {'people': 1},
 ('among', 'people'): {'walk': 1},
 ('people', 'walk'): {'heads': 1},
 ('walk', 'heads'): {'downward': 1},
 ('heads', 'downward'): {'antipathies': 1},
 ('downward', 'antipathies'): {'think': 1},
 ('antipathies', 'think'): {'rather': 1},
 ('think', 'rather'): {'glad': 1},
 ('rather', 'glad'): {'one': 1},
 ('glad', 'one'): {'listening': 1},
 ('one', 'listening'): {'time': 1},
 ('listening', 'time'): {'sound': 1},
 ('time', 'sound'): {'right': 1},
 ('sound', 'right'): {'word': 1},
 ('right', 'word'): {'shall': 1},
 ('word', 'shall'): {'ask': 1},
 ('shall', 'ask'): {'name': 1},
 ('ask', 'name'): {'country': 1},
 ('name', 'country'): {'know': 1},
 ('country', 'know'): {'.': 1},
 ('know', '.'): {'</s>': 17},
 ('<s>', 'please'): {'new': 1,
  'come': 1,
  'said': 1,
  'would': 1,
  'go': 1,
  'majesty': 1},
 ('please', 'new'): {'zealand': 1},
 ('new', 'zealand'): {'australia': 1},
 ('zealand', 'australia'): {'?': 1},
 ('australia', '?'): {'</s>': 1},
 ('<s>', 'tried'): {'curtsey': 1, 'fancy': 1, 'roots': 1},
 ('tried', 'curtsey'): {'spoke': 1},
 ('curtsey', 'spoke'): {'fancy': 1},
 ('spoke', 'fancy'): {'curtseying': 1},
 ('fancy', 'curtseying'): {'falling': 1},
 ('curtseying', 'falling'): {'air': 1},
 ('falling', 'air'): {'think': 1},
 ('air', 'think'): {'could': 1},
 ('think', 'could'): {'manage': 1, 'knew': 1, 'draw': 1},
 ('could', 'manage'): {'?': 1},
 ('manage', '?'): {'</s>': 3},
 ('<s>', 'ignorant'): {'little': 1},
 ('ignorant', 'little'): {'girl': 1},
 ('little', 'girl'): {'think': 1, 'said': 1, 'serpent': 1},
 ('girl', 'think'): {'asking': 1},
 ('think', 'asking'): {'never': 1},
 ('asking', 'never'): {'ask': 1},
 ('never', 'ask'): {'perhaps': 1},
 ('ask', 'perhaps'): {'shall': 1},
 ('perhaps', 'shall'): {'see': 1},
 ('shall', 'see'): {'written': 1},
 ('see', 'written'): {'somewhere': 1},
 ('written', 'somewhere'): {'..': 1},
 ('somewhere', '..'): {'nothing': 1},
 ('..', 'nothing'): {'else': 1},
 ('nothing', 'else'): {'alice': 1, 'perhaps': 1, 'say': 1},
 ('else', 'alice'): {'soon': 1},
 ('alice', 'soon'): {'began': 1, 'left': 1, 'came': 1},
 ('soon', 'began'): {'talking': 1},
 ('began', 'talking'): {'.': 1, 'usual': 1},
 ('talking', '.'): {'</s>': 3},
 ('<s>', 'dinah'): {'miss': 1, 'dear': 1},
 ('dinah', 'miss'): {'much': 1},
 ('miss', 'much'): {'to-night': 1},
 ('much', 'to-night'): {'think': 1},
 ('to-night', 'think'): {'dinah': 1},
 ('think', 'dinah'): {'cat': 1},
 ('dinah', 'cat'): {'.': 2},
 ('cat', '.'): {'</s>': 7},
 ('<s>', 'hope'): {'remember': 1, 'make': 1},
 ('hope', 'remember'): {'saucer': 1},
 ('remember', 'saucer'): {'milk': 1},
 ('saucer', 'milk'): {'tea-time': 1},
 ('milk', 'tea-time'): {'.': 1},
 ('tea-time', '.'): {'</s>': 1},
 ('dinah', 'dear'): {'wish': 1},
 ('dear', 'wish'): {'mice': 1, 'would': 1},
 ('wish', 'mice'): {'air': 1},
 ('mice', 'air'): {'afraid': 1},
 ('air', 'afraid'): {'might': 1},
 ('afraid', 'might'): {'catch': 1},
 ('might', 'catch'): {'bat': 1},
 ('catch', 'bat'): {'like': 1},
 ('bat', 'like'): {'mouse': 1},
 ('like', 'mouse'): {'know': 1, 'heard': 1},
 ('mouse', 'know'): {'.': 1, 'way': 1},
 ('<s>', 'cats'): {'eat': 2},
 ('cats', 'eat'): {'bats': 3},
 ('eat', 'bats'): {'wonder': 1, '?': 2},
 ('bats', 'wonder'): {'?': 1},
 ('wonder', '?'): {'</s>': 3},
 ('alice', 'began'): {'get': 1,
  'cry': 1,
  'feel': 1,
  'rather': 1,
  'say': 1,
  'telling': 1,
  'loud': 1},
 ('began', 'get'): {'rather': 1},
 ('get', 'rather'): {'sleepy': 1},
 ('rather', 'sleepy'): {'went': 1},
 ('sleepy', 'went'): {'saying': 1},
 ('went', 'saying'): {'dreamy': 1},
 ('saying', 'dreamy'): {'sort': 1},
 ('dreamy', 'sort'): {'way': 1},
 ('sort', 'way'): {'cats': 1, 'fly': 1},
 ('way', 'cats'): {'eat': 1},
 ('bats', '?'): {'</s>': 2},
 ('<s>', 'sometimes'): {'bats': 1},
 ('sometimes', 'bats'): {'eat': 1},
 ('bats', 'eat'): {'cats': 1},
 ('eat', 'cats'): {'?': 1},
 ('cats', '?'): {'</s>': 2},
 ('<s>', 'see'): {'answer': 1,
  'many': 1,
  'said': 2,
  'trying': 1,
  'wine': 1,
  'miss': 1,
  'eagerly': 1},
 ('see', 'answer'): {'either': 1},
 ('answer', 'either'): {'question': 1},
 ('either', 'question'): {'much': 1},
 ('question', 'much'): {'matter': 1},
 ('much', 'matter'): {'way': 1},
 ('matter', 'way'): {'put': 1, 'go': 1},
 ('way', 'put'): {'.': 1},
 ('put', '.'): {'</s>': 1},
 ('<s>', 'felt'): {'dozing': 1, 'curious': 1},
 ('felt', 'dozing'): {'begun': 1},
 ('dozing', 'begun'): {'dream': 1},
 ('begun', 'dream'): {'walking': 1},
 ('dream', 'walking'): {'hand': 1},
 ('walking', 'hand'): {'hand': 1},
 ('hand', 'hand'): {'dinah': 1, 'couples': 1},
 ('hand', 'dinah'): {'saying': 1},
 ('dinah', 'saying'): {'earnestly': 1},
 ('saying', 'earnestly'): {'dinah': 1},
 ('earnestly', 'dinah'): {'tell': 1},
 ('dinah', 'tell'): {'truth': 1},
 ('tell', 'truth'): {'ever': 1},
 ('truth', 'ever'): {'eat': 1},
 ('ever', 'eat'): {'bat': 1},
 ('eat', 'bat'): {'?': 1},
 ('bat', '?'): {'</s>': 1},
 ('<s>', 'suddenly'): {'thump': 1, 'came': 1},
 ('suddenly', 'thump'): {'thump': 1},
 ('thump', 'thump'): {'came': 1},
 ('thump', 'came'): {'upon': 1},
 ('came', 'upon'): {'heap': 1, 'little': 1, 'low': 1, 'neat': 1, 'gryphon': 1},
 ('upon', 'heap'): {'sticks': 1},
 ('heap', 'sticks'): {'dry': 1},
 ('sticks', 'dry'): {'leaves': 1},
 ('dry', 'leaves'): {'fall': 1},
 ('leaves', 'fall'): {'.': 1},
 ('fall', '.'): {'</s>': 1},
 ('alice', 'bit'): {'hurt': 1},
 ('bit', 'hurt'): {'jumped': 1},
 ('hurt', 'jumped'): {'feet': 1},
 ('jumped', 'feet'): {'moment': 1},
 ('feet', 'moment'): {'looked': 1},
 ('moment', 'looked'): {'dark': 1},
 ('looked', 'dark'): {'overhead': 1},
 ('dark', 'overhead'): {'another': 1},
 ('overhead', 'another'): {'long': 1},
 ('another', 'long'): {'passage': 1},
 ('long', 'passage'): {'white': 1},
 ('passage', 'white'): {'rabbit': 1},
 ('rabbit', 'still'): {'sight': 1},
 ('still', 'sight'): {'hurrying': 1},
 ('sight', 'hurrying'): {'.': 1},
 ('hurrying', '.'): {'</s>': 1},
 ('<s>', 'moment'): {'lost': 1, 'alice': 2, 'king': 1},
 ('moment', 'lost'): {'away': 1},
 ('lost', 'away'): {'went': 1},
 ('away', 'went'): {'alice': 1},
 ('alice', 'like'): {'wind': 1, 'told': 1, 'tone': 1, 'look': 1},
 ('like', 'wind'): {'time': 1},
 ('wind', 'time'): {'hear': 1},
 ('time', 'hear'): {'say': 1},
 ('hear', 'say'): {'turned': 1},

In [73]:
data = [{'Input': context, 'output': next, 'freq': freq}
        for context, nextFreq in triModel.items()
        for next, freq in nextFreq.items()]

freqTri = pd.DataFrame(data)
freqTri

                           Input      output  freq
0             (<s>, rabbit-hole)       alice     1
1             (<s>, rabbit-hole)        went     1
2           (rabbit-hole, alice)   beginning     1
3             (alice, beginning)         get     1
4             (alice, beginning)         see     1
...                          ...         ...   ...
12205        (joys, remembering)  child-life     1
12206  (remembering, child-life)       happy     1
12207        (child-life, happy)      summer     1
12208            (happy, summer)        days     1
12209             (summer, days)           .     1

[12210 rows x 3 columns]

In [74]:
laplace = {}
vocabSize = len(freq['Word'])

for index, row in freqTri.iterrows():
    trigram = row['Input']
    numerator = row['freq'] + 1

    biCount = freqbi[(freqbi['Input'] == trigram[0]) & (freqbi['output'] == trigram[1])]['freq'].values[0]

    denominator = biCount + vocabSize
    probability = numerator / denominator

    if trigram not in laplace:
        laplace[trigram] = {}
    laplace[trigram][row['output']] = probability

laplace

{('<s>', 'rabbit-hole'): {'alice': 0.0008233841086867024,
  'went': 0.0008233841086867024},
 ('rabbit-hole', 'alice'): {'beginning': 0.0008237232289950577},
 ('alice', 'beginning'): {'get': 0.0008227067050596463,
  'see': 0.0008227067050596463,
  'think': 0.0008227067050596463,
  'angrily': 0.0008227067050596463},
 ('beginning', 'get'): {'tired': 0.0008237232289950577},
 ('get', 'tired'): {'sitting': 0.0008237232289950577},
 ('tired', 'sitting'): {'sister': 0.0008237232289950577},
 ('sitting', 'sister'): {'bank': 0.0008237232289950577},
 ('sister', 'bank'): {'nothing': 0.0008237232289950577},
 ('bank', 'nothing'): {'twice': 0.0008237232289950577},
 ('nothing', 'twice'): {'peeped': 0.0008237232289950577},
 ('twice', 'peeped'): {'book': 0.0008237232289950577},
 ('peeped', 'book'): {'sister': 0.0008237232289950577},
 ('book', 'sister'): {'reading': 0.0008237232289950577},
 ('sister', 'reading'): {'pictures': 0.0008237232289950577},
 ('reading', 'pictures'): {'conversations': 0.0008237232289950577},
 ('pictures', 'conversations'): {'use': 0.0008233841086867024,
  '?': 0.0008233841086867024},
 ('conversations', 'use'): {'book': 0.0008237232289950577},
 ('use', 'book'): {'thought': 0.0008237232289950577},
 ('book', 'thought'): {'alice': 0.0008237232289950577},
 ('thought', 'alice'): {'without': 0.0008153281695882593,
  'fall': 0.0008153281695882593,
  'perhaps': 0.0008153281695882593,
  'speak': 0.0008153281695882593,
  'daresay': 0.0008153281695882593,
  'shall': 0.0008153281695882593,
  'waiting': 0.0008153281695882593,
  '.': 0.0036689767631471666,
  'well': 0.0008153281695882593,
  'long': 0.0008153281695882593,
  'never': 0.0008153281695882593,
  'sure': 0.0008153281695882593,
  'went': 0.0012229922543823889,
  'grin': 0.0008153281695882593,
  'asleep': 0.0008153281695882593,
  'arches': 0.0008153281695882593,
  'might': 0.0008153281695882593,
  'twelve': 0.0008153281695882593},
 ('alice', 'without'): {'pictures': 0.0008237232289950577},
 ('without', 'pictures'): {'conversations': 0.0008237232289950577},
 ('conversations', '?'): {'</s>': 0.0008237232289950577},
 ('<s>', 'considering'): {'mind': 0.0008237232289950577},
 ('considering', 'mind'): {'well': 0.0008237232289950577},
 ('mind', 'well'): {'could': 0.0008237232289950577},
 ('well', 'could'): {'hot': 0.0008220304151253596,
  '.': 0.0012330456226880395,
  'neck': 0.0008220304151253596,
  'sneezing': 0.0008220304151253596,
  'remember': 0.0008220304151253596},
 ('could', 'hot'): {'day': 0.0008237232289950577},
 ('hot', 'day'): {'made': 0.0008237232289950577},
 ('day', 'made'): {'feel': 0.0008237232289950577},
 ('made', 'feel'): {'sleepy': 0.0008237232289950577},
 ('feel', 'sleepy'): {'stupid': 0.0008237232289950577},
 ('sleepy', 'stupid'): {'whether': 0.0008237232289950577},
 ('stupid', 'whether'): {'pleasure': 0.0008237232289950577},
 ('whether', 'pleasure'): {'making': 0.0008237232289950577},
 ('pleasure', 'making'): {'daisy-chain': 0.0008237232289950577},
 ('making', 'daisy-chain'): {'would': 0.0008237232289950577},
 ('daisy-chain', 'would'): {'worth': 0.0008237232289950577},
 ('would', 'worth'): {'trouble': 0.0008237232289950577},
 ('worth', 'trouble'): {'getting': 0.0008237232289950577},
 ('trouble', 'getting'): {'picking': 0.0008237232289950577},
 ('getting', 'picking'): {'daisies': 0.0008237232289950577},
 ('picking', 'daisies'): {'suddenly': 0.0008237232289950577},
 ('daisies', 'suddenly'): {'white': 0.0008237232289950577},
 ('suddenly', 'white'): {'rabbit': 0.0008237232289950577},
 ('white', 'rabbit'): {'pink': 0.0008166598611678236,
  'still': 0.0008166598611678236,
  'returning': 0.0008166598611678236,
  'trotting': 0.0008166598611678236,
  'talking': 0.0008166598611678236,
  'peeping': 0.0008166598611678236,
  '.': 0.0008166598611678236,
  'trumpet': 0.0008166598611678236,
  'cried': 0.0008166598611678236,
  'blew': 0.0012249897917517355,
  'said': 0.0008166598611678236,
  'fumbled': 0.0008166598611678236,
  'read': 0.0012249897917517355,
  'interrupted': 0.0008166598611678236,
  'jumping': 0.0008166598611678236,
  'seems': 0.0008166598611678236,
  'fact': 0.0008166598611678236,
  'queerest': 0.0008166598611678236,
  'put': 0.0008166598611678236,
  'hurried': 0.0008166598611678236},
 ('rabbit', 'pink'): {'eyes': 0.0008237232289950577},
 ('pink', 'eyes'): {'ran': 0.0008237232289950577},
 ('eyes', 'ran'): {'close': 0.0008237232289950577},
 ('ran', 'close'): {'.': 0.0008237232289950577},
 ('close', '.'): {'</s>': 0.0008237232289950577},
 ('<s>', 'nothing'): {'remarkable': 0.0008213552361396304,
  'yet': 0.0008213552361396304,
  'could': 0.0008213552361396304,
  'said': 0.0008213552361396304,
  'whatever': 0.0012320328542094457,
  'clearer': 0.0008213552361396304,
  'pack': 0.0008213552361396304},
 ('nothing', 'remarkable'): {'alice': 0.0008237232289950577},
 ('remarkable', 'alice'): {'think': 0.0008237232289950577},
 ('alice', 'think'): {'much': 0.0008230452674897119,
  'proved': 0.0008230452674897119,
  'pity': 0.0008230452674897119},
 ('think', 'much'): {'way': 0.0008237232289950577},
 ('much', 'way'): {'hear': 0.0008233841086867024,
  'expecting': 0.0008233841086867024},
 ('way', 'hear'): {'rabbit': 0.0008237232289950577},
 ('hear', 'rabbit'): {'say': 0.0008237232289950577},
 ('rabbit', 'say'): {'oh': 0.0008233841086867024,
  'barrowful': 0.0008233841086867024},
 ('say', 'oh'): {'dear': 0.0008237232289950577},
 ('oh', 'dear'): {'oh': 0.0008206811653672548,
  'shall': 0.0012310217480508822,
  'nonsense': 0.0008206811653672548,
  'puzzling': 0.0008206811653672548,
  'cried': 0.0012310217480508822,
  'dinah': 0.0008206811653672548,
  'paws': 0.0008206811653672548,
  'nearly': 0.0008206811653672548},
 ('dear', 'oh'): {'dear': 0.0008237232289950577},
 ('dear', 'shall'): {'late': 0.0008230452674897119,
  'never': 0.0008230452674897119,
  'look': 0.0008230452674897119},
 ('shall', 'late'): {'thought': 0.0008237232289950577},
 ('late', 'thought'): {'afterwards': 0.0008237232289950577},
 ('thought', 'afterwards'): {'occurred': 0.0008237232289950577},
 ('afterwards', 'occurred'): {'ought': 0.0008237232289950577},
 ('occurred', 'ought'): {'wondered': 0.0008237232289950577},
 ('ought', 'wondered'): {'time': 0.0008237232289950577},
 ('wondered', 'time'): {'seemed': 0.0008237232289950577},
 ('time', 'seemed'): {'quite': 0.0008237232289950577},
 ('seemed', 'quite'): {'natural': 0.0012345679012345679,
  'dull': 0.0008230452674897119},
 ('quite', 'natural'): {'rabbit': 0.0008233841086867024,
  'alice': 0.0008233841086867024},
 ('natural', 'rabbit'): {'actually': 0.0008237232289950577},
 ('rabbit', 'actually'): {'took': 0.0008237232289950577},
 ('actually', 'took'): {'watch': 0.0008237232289950577},
 ('took', 'watch'): {'waistcoat-pocket': 0.0008233841086867024,
  'looked': 0.0008233841086867024},
 ('watch', 'waistcoat-pocket'): {'looked': 0.0008237232289950577},
 ('waistcoat-pocket', 'looked'): {'hurried': 0.0008237232289950577},
 ('looked', 'hurried'): {'alice': 0.0008237232289950577},
 ('hurried', 'alice'): {'started': 0.0008237232289950577},
 ('alice', 'started'): {'feet': 0.0008237232289950577},
 ('started', 'feet'): {'flashed': 0.0008237232289950577},
 ('feet', 'flashed'): {'across': 0.0008237232289950577},
 ('flashed', 'across'): {'mind': 0.0008237232289950577},
 ('across', 'mind'): {'never': 0.0008237232289950577},
 ('mind', 'never'): {'seen': 0.0008237232289950577},
 ('never', 'seen'): {'rabbit': 0.0008233841086867024,
  'curious': 0.0008233841086867024},
 ('seen', 'rabbit'): {'either': 0.0008237232289950577},
 ('rabbit', 'either'): {'waistcoat-pocket': 0.0008237232289950577},
 ('either', 'waistcoat-pocket'): {'watch': 0.0008237232289950577},
 ('waistcoat-pocket', 'watch'): {'take': 0.0008237232289950577},
 ('watch', 'take'): {'burning': 0.0008237232289950577},
 ('take', 'burning'): {'curiosity': 0.0008237232289950577},
 ('burning', 'curiosity'): {'ran': 0.0008237232289950577},
 ('curiosity', 'ran'): {'across': 0.0008237232289950577},
 ('ran', 'across'): {'field': 0.0008237232289950577},
 ('across', 'field'): {'fortunately': 0.0008237232289950577},
 ('field', 'fortunately'): {'time': 0.0008237232289950577},
 ('fortunately', 'time'): {'see': 0.0008237232289950577},
 ('time', 'see'): {'pop': 0.0008237232289950577},
 ('see', 'pop'): {'large': 0.0008237232289950577},
 ('pop', 'large'): {'rabbit-hole': 0.0008237232289950577},
 ('large', 'rabbit-hole'): {'hedge': 0.0008237232289950577},
 ('rabbit-hole', 'hedge'): {'.': 0.0008237232289950577},
 ('hedge', '.'): {'</s>': 0.0008237232289950577},
 ('<s>', 'another'): {'moment': 0.0008227067050596463,
  'puzzling': 0.0008227067050596463,
  'minute': 0.0008227067050596463,
  'shore': 0.0008227067050596463},
 ('another', 'moment'): {'went': 0.0008223684210526315,
  'splash': 0.0008223684210526315,
  'sight': 0.0008223684210526315,
  'found': 0.0008223684210526315,
  'addressed': 0.0008223684210526315},
 ('moment', 'went'): {'alice': 0.0008237232289950577},
 ('went', 'alice'): {'never': 0.0008233841086867024,
  'like': 0.0008233841086867024},
 ('alice', 'never'): {'considering': 0.0008230452674897119,
  'come': 0.0008230452674897119,
  'court': 0.0008230452674897119},
 ('never', 'considering'): {'world': 0.0008237232289950577},
 ('considering', 'world'): {'get': 0.0008237232289950577},
 ('world', 'get'): {'.': 0.0008237232289950577},
 ('get', '.'): {'</s>': 0.0016460905349794238},
 ('rabbit-hole', 'went'): {'straight': 0.0008237232289950577},
 ('went', 'straight'): {'like': 0.0008237232289950577},
 ('straight', 'like'): {'tunnel': 0.0008237232289950577},
 ('like', 'tunnel'): {'way': 0.0008237232289950577},
 ('tunnel', 'way'): {'dipped': 0.0008237232289950577},
 ('way', 'dipped'): {'suddenly': 0.0008237232289950577},
 ('dipped', 'suddenly'): {'suddenly': 0.0008237232289950577},
 ('suddenly', 'suddenly'): {'alice': 0.0008237232289950577},
 ('suddenly', 'alice'): {'moment': 0.0008237232289950577},
 ('alice', 'moment'): {'think': 0.0008233841086867024,
  'appeared': 0.0008233841086867024},
 ('moment', 'think'): {'stopping': 0.0008237232289950577},
 ('think', 'stopping'): {'found': 0.0008237232289950577},
 ('stopping', 'found'): {'falling': 0.0008237232289950577},
 ('found', 'falling'): {'deep': 0.0008237232289950577},
 ('falling', 'deep'): {'well': 0.0008237232289950577},
 ('deep', 'well'): {'.': 0.0008237232289950577},
 ('well', '.'): {'</s>': 0.0016460905349794238},
 ('<s>', 'either'): {'well': 0.0008237232289950577},
 ('either', 'well'): {'deep': 0.0008237232289950577},
 ('well', 'deep'): {'fell': 0.0008237232289950577},
 ('deep', 'fell'): {'slowly': 0.0008237232289950577},
 ('fell', 'slowly'): {'plenty': 0.0008237232289950577},
 ('slowly', 'plenty'): {'time': 0.0008237232289950577},
 ('plenty', 'time'): {'went': 0.0008237232289950577},
 ('time', 'went'): {'look': 0.0008233841086867024,
  'talking': 0.0008233841086867024},
 ('went', 'look'): {'wonder': 0.0008237232289950577},
 ('look', 'wonder'): {'going': 0.0008237232289950577},
 ('wonder', 'going'): {'happen': 0.0008237232289950577},
 ('going', 'happen'): {'next': 0.0008237232289950577},
 ('happen', 'next'): {'.': 0.0016460905349794238},
 ('next', '.'): {'</s>': 0.0024671052631578946},
 ('<s>', 'first'): {'tried': 0.000819672131147541,
  'however': 0.000819672131147541,
  'idea': 0.000819672131147541,
  'sentence': 0.000819672131147541,
  'question': 0.0012295081967213116,
  'marked': 0.000819672131147541,
  'thing': 0.0012295081967213116,
  'side': 0.000819672131147541,
  'perhaps': 0.000819672131147541,
  'came': 0.000819672131147541,
  'position': 0.000819672131147541},
 ('first', 'tried'): {'look': 0.0008237232289950577},
 ('tried', 'look'): {'make': 0.0008237232289950577},
 ('look', 'make'): {'coming': 0.0008237232289950577},
 ('make', 'coming'): {'dark': 0.0008237232289950577},
 ('coming', 'dark'): {'see': 0.0008237232289950577},
 ('dark', 'see'): {'anything': 0.0008237232289950577},
 ('see', 'anything'): {'looked': 0.0012350761630300535},
 ('anything', 'looked'): {'sides': 0.0008233841086867024,
  'like': 0.0008233841086867024},
 ('looked', 'sides'): {'well': 0.0008233841086867024,
  'behind': 0.0008233841086867024},
 ('sides', 'well'): {'noticed': 0.0008237232289950577},
 ('well', 'noticed'): {'filled': 0.0008237232289950577},
 ('noticed', 'filled'): {'cupboards': 0.0008237232289950577},
 ('filled', 'cupboards'): {'book-shelves': 0.0008237232289950577},
 ('cupboards', 'book-shelves'): {'saw': 0.0008237232289950577},
 ('book-shelves', 'saw'): {'maps': 0.0008237232289950577},
 ('saw', 'maps'): {'pictures': 0.0008237232289950577},
 ('maps', 'pictures'): {'hung': 0.0008237232289950577},
 ('pictures', 'hung'): {'upon': 0.0008237232289950577},
 ('hung', 'upon'): {'pegs': 0.0008237232289950577},
 ('upon', 'pegs'): {'.': 0.0008237232289950577},
 ('pegs', '.'): {'</s>': 0.0008237232289950577},
 ('<s>', 'took'): {'jar': 0.0008230452674897119,
  'housemaid': 0.0008230452674897119,
  'regular': 0.0008230452674897119},
 ('took', 'jar'): {'one': 0.0008237232289950577},
 ('jar', 'one'): {'shelves': 0.0008237232289950577},
 ('one', 'shelves'): {'passed': 0.0008237232289950577},
 ('shelves', 'passed'): {'labelled': 0.0008237232289950577},
 ('passed', 'labelled'): {'orange': 0.0008237232289950577},
 ('labelled', 'orange'): {'marmalade': 0.0008237232289950577},
 ('orange', 'marmalade'): {'great': 0.0008237232289950577},
 ('marmalade', 'great'): {'disappointment': 0.0008237232289950577},
 ('great', 'disappointment'): {'empty': 0.0008237232289950577},
 ('disappointment', 'empty'): {'like': 0.0008237232289950577},
 ('empty', 'like'): {'drop': 0.0008237232289950577},
 ('like', 'drop'): {'jar': 0.0008237232289950577},
 ('drop', 'jar'): {'fear': 0.0008237232289950577},
 ('jar', 'fear'): {'killing': 0.0008237232289950577},
 ('fear', 'killing'): {'somebody': 0.0008237232289950577},
 ('killing', 'somebody'): {'underneath': 0.0008237232289950577},
 ('somebody', 'underneath'): {'managed': 0.0008237232289950577},
 ('underneath', 'managed'): {'put': 0.0008237232289950577},
 ('managed', 'put'): {'one': 0.0008237232289950577},
 ('put', 'one'): {'cupboards': 0.0008230452674897119,
  'rabbit': 0.0008230452674897119,
  'arm': 0.0008230452674897119},
 ('one', 'cupboards'): {'fell': 0.0008237232289950577},
 ('cupboards', 'fell'): {'past': 0.0008237232289950577},
 ('fell', 'past'): {'.': 0.0008237232289950577},
 ('past', '.'): {'</s>': 0.0008237232289950577},
 ('<s>', 'well'): {'thought': 0.0008163265306122449,
  'say': 0.0008163265306122449,
  'eat': 0.0008163265306122449,
  'perhaps': 0.0016326530612244899,
  'got': 0.0008163265306122449,
  'tried': 0.0008163265306122449,
  'like': 0.0008163265306122449,
  '?': 0.0008163265306122449,
  'said': 0.0008163265306122449,
  'cat': 0.0008163265306122449,
  'often': 0.0008163265306122449,
  'hardly': 0.0008163265306122449,
  'alice': 0.0008163265306122449,
  'must': 0.0012244897959183673,
  'gryphon': 0.0008163265306122449,
  'mystery': 0.0008163265306122449,
  'show': 0.0008163265306122449,
  'never': 0.0008163265306122449,
  'rate': 0.0008163265306122449,
  'go': 0.0008163265306122449},
 ('well', 'thought'): {'alice': 0.0008237232289950577},
 ('alice', 'fall'): {'shall': 0.0008237232289950577},
 ('fall', 'shall'): {'think': 0.0008237232289950577},
 ('shall', 'think'): {'nothing': 0.0008237232289950577},
 ('think', 'nothing'): {'tumbling': 0.0008230452674897119,
  'better': 0.0008230452674897119,
  'else': 0.0008230452674897119},
 ('nothing', 'tumbling'): {'stairs': 0.0008237232289950577},
 ('tumbling', 'stairs'): {'brave': 0.0008237232289950577},
 ('stairs', 'brave'): {'think': 0.0008237232289950577},
 ('brave', 'think'): {'home': 0.0008237232289950577},
 ('think', 'home'): {'say': 0.0008237232289950577},
 ('home', 'say'): {'anything': 0.0008237232289950577},
 ('say', 'anything'): {'even': 0.0008233841086867024,
  '.': 0.0008233841086867024},
 ('anything', 'even'): {'fell': 0.0008237232289950577},
 ('even', 'fell'): {'top': 0.0008237232289950577},
 ('fell', 'top'): {'house': 0.0008237232289950577},
 ('top', 'house'): {'likely': 0.0008237232289950577},
 ('house', 'likely'): {'true': 0.0008237232289950577},
 ('likely', 'true'): {'..': 0.0008237232289950577},
 ('true', '..'): {'would': 0.0008237232289950577},
 ('..', 'would'): {'fall': 0.0008237232289950577},
 ('would', 'fall'): {'never': 0.0008237232289950577},
 ('fall', 'never'): {'come': 0.0008237232289950577},
 ('never', 'come'): {'end': 0.0008233841086867024,
  'upon': 0.0008233841086867024},
 ('come', 'end'): {'?': 0.0008233841086867024, 'stop': 0.0008233841086867024},
 ('end', '?'): {'</s>': 0.0008237232289950577},
 ('<s>', 'wonder'): {'many': 0.0008223684210526315,
  'shall': 0.0008223684210526315,
  'like': 0.0008223684210526315,
  'changed': 0.0008223684210526315,
  'next': 0.0008223684210526315},
 ('wonder', 'many'): {'miles': 0.0008237232289950577},
 ('many', 'miles'): {'fallen': 0.0008237232289950577},
 ('miles', 'fallen'): {'time': 0.0008237232289950577},
 ('fallen', 'time'): {'?': 0.0008237232289950577},
 ('time', '?'): {'</s>': 0.0008237232289950577},
 ('<s>', 'said'): {'aloud': 0.0007964954201513341,
  'lory': 0.0011947431302270011,
  'duck': 0.0007964954201513341,
  'alice': 0.009557945041816009,
  'dodo': 0.0007964954201513341,
  'mouse': 0.0007964954201513341,
  'came': 0.0011947431302270011,
  'caterpillar': 0.0035842293906810036,
  'nibbled': 0.0007964954201513341,
  'pigeon': 0.0007964954201513341,
  'footman': 0.0007964954201513341,
  'duchess': 0.0007964954201513341,
  'last': 0.0011947431302270011,
  'cat': 0.001991238550378335,
  'looked': 0.0007964954201513341,
  'pig': 0.0007964954201513341,
  'march': 0.001991238550378335,
  'turning': 0.0007964954201513341,
  'one': 0.0011947431302270011,
  'knave': 0.0007964954201513341,
  'queen': 0.001991238550378335,
  '?': 0.0007964954201513341,
  'king': 0.001991238550378335,
  'gryphon': 0.001991238550378335,
  'mock': 0.0023894862604540022,
  'whiting': 0.0007964954201513341,
  'dormouse': 0.0007964954201513341,
  'hatter': 0.0007964954201513341,
  'cook': 0.0007964954201513341,
  'white': 0.0007964954201513341,
  'could': 0.0007964954201513341,
  '.': 0.0007964954201513341},
 ('said', 'aloud'): {'.': 0.0008237232289950577},
 ('aloud', '.'): {'</s>': 0.0016460905349794238},
 ('<s>', 'must'): {'getting': 0.000819672131147541,
  'go': 0.001639344262295082,
  'growing': 0.000819672131147541,
  'prize': 0.000819672131147541,
  'burn': 0.000819672131147541,
  'said': 0.0012295081967213116,
  'pretty': 0.000819672131147541,
  'remember': 0.000819672131147541,
  'imitated': 0.000819672131147541,
  'meant': 0.000819672131147541},
 ('must', 'getting'): {'somewhere': 0.0008233841086867024,
  'home': 0.0008233841086867024},
 ('getting', 'somewhere'): {'near': 0.0008237232289950577},
 ('somewhere', 'near'): {'centre': 0.0008237232289950577},
 ('near', 'centre'): {'earth': 0.0008237232289950577},
 ('centre', 'earth'): {'.': 0.0008237232289950577},
 ('earth', '.'): {'</s>': 0.0012350761630300535},
 ('<s>', 'let'): {'see': 0.0012330456226880395,
  'think': 0.0008220304151253596,
  'alone': 0.0008220304151253596,
  'go': 0.0008220304151253596,
  'know': 0.0008220304151253596},
 ('let', 'see'): {'would': 0.0008227067050596463,
  'give': 0.0008227067050596463,
  'four': 0.0008227067050596463,
  'managed': 0.0008227067050596463},
 ('see', 'would'): {'four': 0.0008230452674897119,
  'happen': 0.0008230452674897119,
  'deny': 0.0008230452674897119},
 ('would', 'four'): {'thousand': 0.0008237232289950577},
 ('four', 'thousand'): {'miles': 0.0008237232289950577},
 ('thousand', 'miles'): {'think': 0.0008237232289950577},
 ('miles', 'think'): {'see': 0.0008237232289950577},
 ('think', 'see'): {'alice': 0.0008237232289950577},
 ('see', 'alice'): {'learnt': 0.0008237232289950577},
 ('alice', 'learnt'): {'several': 0.0008237232289950577},
 ('learnt', 'several'): {'things': 0.0008237232289950577},
 ('several', 'things'): {'sort': 0.0008237232289950577},
 ('things', 'sort'): {'lessons': 0.0008237232289950577},

In [75]:
data = [{'Input': context, 'output': next, 'prob (laplace)': prob}
        for context, next_word_freq in laplace.items()
        for next, prob in next_word_freq.items()]
freqLap = pd.DataFrame(data)
freqLap

                           Input      output  prob (laplace)
0             (<s>, rabbit-hole)       alice        0.000823
1             (<s>, rabbit-hole)        went        0.000823
2           (rabbit-hole, alice)   beginning        0.000824
3             (alice, beginning)         get        0.000823
4             (alice, beginning)         see        0.000823
...                          ...         ...             ...
12205        (joys, remembering)  child-life        0.000824
12206  (remembering, child-life)       happy        0.000824
12207        (child-life, happy)      summer        0.000824
12208            (happy, summer)        days        0.000824
12209             (summer, days)           .        0.000824

[12210 rows x 3 columns]

In [76]:
genSent = []
for i in range(5):
  print("\n\tGenerating sentence",i+1,"\n:")
  first = input("Enter first word: ").lower()
  second = input("Enter second word: ").lower()
  sentence = [first,second]
  while len(sentence) <= 10:
      context = tuple(sentence[-2:])

      if context not in laplace:
        break

      next = max(laplace[context], key=laplace[context].get)
      sentence.append(next)

  generatedText = ' '.join(sentence)
  genSent.append(generatedText)
  print("generated text:", generatedText)

	Generating sentence 1
:
Enter first word: rabbit-hole
Enter second word: alice
generated text: rabbit-hole alice beginning get tired sitting sister bank nothing twice

	Generating sentence 2
:
Enter first word: white
Enter second word: rabbit
generated text: white rabbit blew three blasts trumpet unrolled parchment scroll read

	Generating sentence 3
:
Enter first word: stupid
Enter second word: things
generated text: stupid things alice thought might well say added march hare

	Generating sentence 4
:
Enter first word: could
Enter second word: see
generated text: could see quite plainly glass tried best climb one legs

	Generating sentence 5
:
Enter first word: alice
Enter second word: began
generated text: alice began get rather sleepy went saying dreamy sort way

In [144]:
def perplexityCalc(test_set, triModel):
    N = len(test_set)
    logSum = 0

    for i in range(2, N):
        trigram = (test_set[i-2], test_set[i-1], test_set[i])
        if trigram in triModel:
            triProb = triModel[trigram[0:2]][trigram[2]]
        else:
            triProb = 1 / len(triModel)

        logSum += math.log(triProb)

    perplexity = math.exp(-logSum / N)
    return perplexity

print("Perplexity:", perplexityCalc(genSent, laplace))

Perplexity: 255.50451172083947